#!/usr/bin/env python3
"""gen_ed_matvec.py — generate matrix-free ED power-iteration programs.

Emits two variants of the ternary-rotor-chain matvec (original gauge,
B=0.25 so the field term V = K_PHASE - B*K_BIAS = 0 and H is real):
  resident : full V/W on GPU (N <= 17; V+W f64 <= ~2.1 GB)
  streamed : V resident, W produced through a QT-element window buffer
             per tile and downloaded to a host array (N = 18; V ~3.1 GB
             stays put, W streams through the host)

  out[x] = (diag(x) - SHIFT) v[x]
           - JH sum_i [ (d_i>=1, d_j<=1) v[x-3^i+3^j]
                      + (d_i<=1, d_j>=1) v[x+3^i-3^j] ]
  diag(x) = sum_i ((d_i-1)^2)/2,  d_i = (x // 3^i) % 3,  j = i+1 mod N

Index safety: masked bond reads use a MOD-wrapped index so mask=0 reads
stay in-bounds (when the digit mask is 1 the wrapped index provably
equals the raw one — no value change). The field term (-halfV) is
omitted at B=0.25 (V=0 identically; the generator notes this).

Power iteration on H~ = H - SHIFT*I (SHIFT=3 keeps the ground state
dominant, |E0-3|=5.86 > |Emax-3|~4), Rayleigh rho = v.w with v
normalized, E0 = rho + SHIFT. Reductions are the Inc-1 ordered combine
(deterministic). Seed: V(K) := 0.5 + REAL(MOD(K, 9973)) * 0.0001 —
must match min/phase_ed/ed_ref.py.

Usage: python3 min/phase_ed/gen_ed_matvec.py N [resident|streamed] > ed_power_N{n}.ergo
"""
import sys


def matvec_body(N, out_arr, in_arr, tb, indent, qt_dim="DIM"):
    """Unrolled matrix-free matvec for output element K (1-based).
    tb: "" for resident (global x = K-1) or "+TB" for windowed."""
    p = " " * indent
    L = []
    L.append(f"{p}Q := K - 1{tb}")
    for i in range(N):
        L.append(f"{p}D{i} := MOD(Q, 3)")
        if i < N - 1:
            L.append(f"{p}Q := Q / 3")
    dg = " + ".join(f"(D{i} - 1) * (D{i} - 1)" for i in range(N))
    L.append(f"{p}DG := {dg}")
    L.append(f"{p}{out_arr}(K) := (REAL(DG) * 0.5 - SHIFT) * {in_arr}(K{tb})")
    for i in range(N):
        j = (i + 1) % N
        pi, pj = 3 ** i, 3 ** j
        # (d_i>=1, d_j<=1): v[x - 3^i + 3^j]
        L.append(f"{p}SX := K{tb} - {pi} + {pj}")
        L.append(f"{p}SX := MOD(SX - 1 + {qt_dim}, {qt_dim}) + 1")
        L.append(f"{p}{out_arr}(K) := {out_arr}(K) - JH * "
                 f"REAL(MIN(D{i}, 1) * MIN(2 - D{j}, 1)) * {in_arr}(SX)")
        # (d_i<=1, d_j>=1): v[x + 3^i - 3^j]
        L.append(f"{p}SX := K{tb} + {pi} - {pj}")
        L.append(f"{p}SX := MOD(SX - 1 + {qt_dim}, {qt_dim}) + 1")
        L.append(f"{p}{out_arr}(K) := {out_arr}(K) - JH * "
                 f"REAL(MIN(2 - D{i}, 1) * MIN(D{j}, 1)) * {in_arr}(SX)")
    return L


def header(N, variant, extra):
    return f"""! ed_power_N{N}.ergo — GENERATED by gen_ed_matvec.py ({variant}); do not edit.
! Matrix-free power iteration, ternary rotor chain, N={N}, dim=3^{N}.
! Original gauge at B=0.25, J=1.0 (V = K_PHASE - B*K_BIAS = 0: real
! Hamiltonian, no field terms — see gen_ed_matvec.py). SHIFT = 2N baked
! into the diagonal: Emax <= 1.5N < 2N makes H~ negative definite so
! the ground state dominates power iteration at any N (the stage0
! shift-3 dominance is N=8-specific — it fails for N>=10, measured:
! N=14 converged to the spectrum top +11.68). E0 = rho + SHIFT.
! Oracles: stage0_check.md (N=8) and ed_ref.py (matvec + eigsh E0).
! First matvec is checksummed before the iteration loop (raw seed) so
! the full matvec vector can be compared against the numba bridge.
{extra}"""


def resident(N):
    DIM = 3 ** N
    L = [header(N, "resident",
                "! Resident variant: full V/W on the GPU (no tiling —\n"
                "! single whole-range dispatches; deterministic reductions).")]
    L += [
        "IMPLICIT NONE",
        f"INTEGER, PARAMETER :: N = {N}",
        f"INTEGER, PARAMETER :: DIM = {DIM}",
        "INTEGER, PARAMETER :: NITER = 3000",
        f"REAL, PARAMETER :: SHIFT = {2.0 * N:.1f}, JH = 0.5, TOLC = 1.0e-12",
        f"STATIC REAL :: V({DIM}), W({DIM})",
        "REAL :: RHO, NRM, NRM2T, RHOOLD, DRHO, C1, C2",
        f"INTEGER :: K, ITER, CONV, Q, SX, DG, {', '.join(f'D{i}' for i in range(N))}",
        "",
        "! deterministic seed",
        "DO K = 1, DIM",
        "  V(K) := 0.5 + REAL(MOD(K, 9973)) * 0.0001",
        "  W(K) := 0.0",
        "ENDDO",
        "",
        "! first matvec (raw seed) + checksum for the numba-bridge compare",
        "DO K = 1, DIM",
    ]
    L += matvec_body(N, "W", "V", "", 2)
    L += [
        "ENDDO",
        "C1 := 0.0",
        "C2 := 0.0",
        "DO K = 1, DIM",
        "  C1 := C1 + W(K)",
        "  C2 := C2 + W(K) * REAL(1 + MOD(K, 7))",
        "ENDDO",
        'WRITE(*, "mv1 c1=%.17e c2=%.17e") C1, C2',
        'WRITE(*, "mv1 w0=%.17e wmid=%.17e wlast=%.17e") '
        "W(1), W(DIM / 2 + 1), W(DIM)",
        "",
        "! normalize into V, then power-iterate",
        "NRM2T := 0.0",
        "DO K = 1, DIM",
        "  NRM2T := NRM2T + W(K) * W(K)",
        "ENDDO",
        "NRM := SQRT(NRM2T)",
        "DO K = 1, DIM",
        "  V(K) := W(K) / NRM",
        "ENDDO",
        "RHOOLD := RHO",
        "CONV := 0",
        "DO ITER = 1, NITER",
        "  IF (CONV == 0) THEN",
        "    DO K = 1, DIM",
    ]
    L += matvec_body(N, "W", "V", "", 6)
    L += [
        "    ENDDO",
        "    RHO := 0.0",
        "    NRM2T := 0.0",
        "    DO K = 1, DIM",
        "      RHO := RHO + V(K) * W(K)",
        "      NRM2T := NRM2T + W(K) * W(K)",
        "    ENDDO",
        "    NRM := SQRT(NRM2T)",
        "    DO K = 1, DIM",
        "      V(K) := W(K) / NRM",
        "    ENDDO",
        "    DRHO := ABS(RHO - RHOOLD)",
        "    RHOOLD := RHO",
        '    IF (MOD(ITER, 100) == 0) THEN',
        '      WRITE(*, "iter %d  E0 %.10f  drho %.3e") ITER, RHO + SHIFT, DRHO',
        "    ENDIF",
        "    IF (DRHO < TOLC) THEN",
        "      CONV := 1",
        "    ENDIF",
        "  ENDIF",
        "ENDDO",
        'WRITE(*, "E0 = %.10f  iters %d") RHO + SHIFT, ITER - 1',
    ]
    return "\n".join(L) + "\n"


def streamed(N):
    DIM = 3 ** N
    QT = 3 ** 16
    NT = DIM // QT
    assert DIM % QT == 0
    L = [header(N, "streamed",
                "! Streamed variant: V resident (~3.1 GB), W produced per\n"
                "! tile into the QT window WWIN and downloaded to host HW\n"
                "! (Inc-2B gather-window streaming v1 — one remote (the\n"
                "! window is the output, not the gather halo; V is fully\n"
                "! resident so all bond gathers hit it directly).\n"
                "! HW/V copies stay on the CPU via WRITE disqualifiers so\n"
                "! the host arrays never become GPU-resident (VRAM).\n"
                "! RHO/NRM2T accumulate across per-tile multi-reductions\n"
                "! (host combine adds onto the CPU accumulators in tile\n"
                "! order — deterministic).")]
    L += [
        "IMPLICIT NONE",
        f"INTEGER, PARAMETER :: N = {N}",
        f"INTEGER, PARAMETER :: DIM = {DIM}",
        f"INTEGER, PARAMETER :: QT = {QT}, NT = {NT}",
        "INTEGER, PARAMETER :: NITER = 3000",
        f"REAL, PARAMETER :: SHIFT = {2.0 * N:.1f}, JH = 0.5, TOLC = 1.0e-12",
        f"STATIC REAL :: V({DIM}), HW({DIM})",
        f"STATIC REAL :: WWIN({QT})",
        "REAL :: RHO, NRM, RHOOLD, DRHO, C1, C2, RHOP, NRM2T, RHO2",
        f"INTEGER :: K, T, TB, ITER, CONV, Q, SX, DG, {', '.join(f'D{i}' for i in range(N))}",
        "",
        "! deterministic seed",
        "DO K = 1, DIM",
        "  V(K) := 0.5 + REAL(MOD(K, 9973)) * 0.0001",
        "ENDDO",
        "",
        "! first matvec (raw seed) + checksum; HW assembled on the host",
        "DO T = 1, NT",
        "  TB := (T - 1) * QT",
        "  DO K = 1, QT",
    ]
    L += matvec_body(N, "WWIN", "V", " + TB", 4)
    L += [
        "  ENDDO",
        "  DO K = 1, QT",
        "    IF (K == 1) THEN",
        "      IF (T == 999999) THEN",
        '        WRITE(*, "unreachable") ',
        "      ENDIF",
        "    ENDIF",
        "    HW(K + TB) := WWIN(K)",
        "  ENDDO",
        "ENDDO",
        "C1 := 0.0",
        "C2 := 0.0",
        "DO K = 1, DIM",
        "  IF (K == 1) THEN",
        "    IF (DIM == 999999) THEN",
        '      WRITE(*, "unreachable") ',
        "    ENDIF",
        "  ENDIF",
        "  C1 := C1 + HW(K)",
        "  C2 := C2 + HW(K) * REAL(1 + MOD(K, 7))",
        "ENDDO",
        'WRITE(*, "mv1 c1=%.17e c2=%.17e") C1, C2',
        'WRITE(*, "mv1 w0=%.17e wmid=%.17e wlast=%.17e") '
        "HW(1), HW(DIM / 2 + 1), HW(DIM)",
        "",
        "NRM2T := 0.0",
        "DO K = 1, DIM",
        "  IF (K == 1) THEN",
        "    IF (DIM == 999999) THEN",
        '      WRITE(*, "unreachable") ',
        "    ENDIF",
        "  ENDIF",
        "  NRM2T := NRM2T + HW(K) * HW(K)",
        "ENDDO",
        "NRM := SQRT(NRM2T)",
        "RHOOLD := 0.0",
        "CONV := 0",
        "DO ITER = 1, NITER",
        "  IF (CONV == 0) THEN",
        "    ! V <- HW / NRM (CPU pass; kept out of the GPU by the WRITE)",
        "    DO K = 1, DIM",
        "      IF (K == 1) THEN",
        "        IF (ITER == 999999) THEN",
        '          WRITE(*, "unreachable") ',
        "        ENDIF",
        "      ENDIF",
        "      V(K) := HW(K) / NRM",
        "    ENDDO",
        "    RHO := 0.0",
        "    NRM2T := 0.0",
        "    DO T = 1, NT",
        "      TB := (T - 1) * QT",
        "      DO K = 1, QT",
    ]
    L += matvec_body(N, "WWIN", "V", " + TB", 8)
    L += [
        "      ENDDO",
        "      RHOP := 0.0",
        "      RHO2 := 0.0",
        "      DO K = 1, QT",
        "        RHOP := RHOP + V(K + TB) * WWIN(K)",
        "        RHO2 := RHO2 + WWIN(K) * WWIN(K)",
        "      ENDDO",
        "      RHO := RHO + RHOP",
        "      NRM2T := NRM2T + RHO2",
        "      DO K = 1, QT",
        "        IF (K == 1) THEN",
        "          IF (ITER == 999999) THEN",
        '            WRITE(*, "unreachable") ',
        "          ENDIF",
        "        ENDIF",
        "        HW(K + TB) := WWIN(K)",
        "      ENDDO",
        "    ENDDO",
        "    NRM := SQRT(NRM2T)",
        "    DRHO := ABS(RHO - RHOOLD)",
        "    RHOOLD := RHO",
        "    IF (MOD(ITER, 100) == 0) THEN",
        '      WRITE(*, "iter %d  E0 %.10f  drho %.3e") ITER, RHO + SHIFT, DRHO',
        "    ENDIF",
        "    IF (DRHO < TOLC) THEN",
        "      CONV := 1",
        "    ENDIF",
        "  ENDIF",
        "ENDDO",
        'WRITE(*, "E0 = %.10f  iters %d") RHO + SHIFT, ITER - 1',
    ]
    return "\n".join(L) + "\n"


def main():
    N = int(sys.argv[1])
    variant = sys.argv[2] if len(sys.argv) > 2 else (
        "resident" if N <= 17 else "streamed")
    if variant == "resident":
        sys.stdout.write(resident(N))
    elif variant == "streamed":
        sys.stdout.write(streamed(N))
    elif variant == "streamed19":
        niter = int(sys.argv[3]) if len(sys.argv) > 3 else 300
        sys.stdout.write(streamed19(N, niter))
    else:
        sys.exit(f"unknown variant {variant}")




def streamed19(N, niter=300):
    """N=19-class full gather-window streaming (works at any N>=6 for
    validation; sizes scale as powers of 3).

    Memory (N=19, f64): V/HW host-resident (9.3 GB each); on device:
      VA   ring window, WINA = 5*QT (halo 2*QT covers bonds i<=N-3)
      RA17A/B, RA18A/B  remote QT slices for bonds i=N-2, N-1
      WWIN output tile
      ~= 1.72 + 1.38 + 0.34 GB = 3.45 GB (fits the 6 GB card;
      maxStorageBufferRange 4.29 GB asserted per buffer).
    Ring slot of global g is MOD(g-1,WINA)+1 — no base tracking; per
    tile the host stages only the advancing QT slice plus 4 remote
    slices, all via VK_STAGE (no host array copies), then dispatches
    kernel B (top bonds), kernel A (diag + low bonds, accumulates onto
    WWIN), the tiled multi-reduction (RHO/NRM2 accumulate in tile
    order), and VK_FETCHes WWIN into the host HW slice.
    """
    DIM = 3 ** N
    QT = 3 ** (N - 3)
    NT = 27
    WINA = 5 * QT
    L = [header(N, "streamed19",
                "! Full gather-window streaming (see gen_ed_matvec.py "
                "docstring):\n! V/HW host-resident; device holds only a "
                "5*QT ring window (bonds i<=N-3),\n! 4 remote QT slices "
                "(bonds N-2, N-1) and the QT output window. Host stages\n"
                "! slices with VK_STAGE / fetches with VK_FETCH "
                "(frame-draining intrinsics).")]
    L += [
        "IMPLICIT NONE",
        f"INTEGER, PARAMETER :: N = {N}",
        f"INTEGER, PARAMETER :: DIM = {DIM}",
        f"INTEGER, PARAMETER :: QT = {QT}, NT = {NT}",
        f"INTEGER, PARAMETER :: WINA = {WINA}",
        f"INTEGER, PARAMETER :: NITER = {niter}",
        f"REAL, PARAMETER :: SHIFT = {2.0 * N:.1f}, JH = 0.5, TOLC = 1.0e-12",
        f"STATIC REAL :: V({DIM}), HW({DIM})",
        f"STATIC REAL :: VA({WINA}), WWIN({QT})",
        f"STATIC REAL :: RA17A({QT}), RA17B({QT}), RA18A({QT}), RA18B({QT})",
        "REAL :: RHO, NRM, NRM2T, RHOOLD, DRHO, C1, C2, RHOP, R2",
        "INTEGER :: K, T, TB, ITER, CONV, Q, SX, SL, DG",
        "INTEGER :: S, A0, A1",
        f"INTEGER :: {', '.join(f'D{i}' for i in range(N))}",
        "",
        "! deterministic seed (host-only: WRITE disqualifier keeps it off GPU)",
        "DO K = 1, DIM",
        "  IF (K == 1) THEN",
        "    IF (DIM == 999999) THEN",
        '      WRITE(*, "unreachable") ',
        "    ENDIF",
        "  ENDIF",
        "  V(K) := 0.5 + REAL(MOD(K, 9973)) * 0.0001",
        "ENDDO",
        "RHOOLD := 0.0",
        "CONV := 0",
        "DO ITER = 1, NITER",
        "  IF (CONV == 0) THEN",
        "    RHO := 0.0",
        "    NRM2T := 0.0",
        "    DO T = 1, NT",
        "      TB := (T - 1) * QT",
        "      ! ── stage A ring ──",
        "      IF (T == 1) THEN",
        "        CALL VK_STAGE(VA, V, 1, 1, 3 * QT)",
        "      ELSE",
        "        S := TB + 2 * QT",
        "        A0 := S + 1",
        "        IF (A0 + QT - 1 > DIM) THEN",
        "          A1 := DIM",
        "        ELSE",
        "          A1 := S + QT",
        "        ENDIF",
        "        IF (A1 >= A0) THEN",
        "          CALL VK_STAGE(VA, V, A0, MOD(S, WINA) + 1, A1 - A0 + 1)",
        "        ENDIF",
        "      ENDIF",
        "      ! ── stage B remote slices (top bonds N-2, N-1) ──",
    ]
    for name, off in (("RA17A", "6 * QT"), ("RA17B", "0 - 6 * QT"),
                      ("RA18A", "0 - 9 * QT + 1"), ("RA18B", "9 * QT - 1")):
        L += [
            f"      S := TB + {off}",
            "      A0 := S + 1",
            "      A1 := S + QT",
            "      IF (A0 < 1) THEN",
            "        A0 := 1",
            "      ENDIF",
            "      IF (A1 > DIM) THEN",
            "        A1 := DIM",
            "      ENDIF",
            "      IF (A1 >= A0) THEN",
            f"        CALL VK_STAGE({name}, V, A0, A0 - S, A1 - A0 + 1)",
            "      ENDIF",
        ]
    L += [
        "      ! ── kernel B: top bonds (i=N-2, i=N-1) from remote slices ──",
        "      DO K = 1, QT",
        "        Q := K - 1 + TB",
    ]
    for i in range(N):
        L.append(f"        D{i} := MOD(Q, 3)")
        if i < N - 1:
            L.append("        Q := Q / 3")
    i, j = N - 2, N - 1
    L += [
        f"        WWIN(K) := 0.0 - JH * REAL(MIN(D{i}, 1) * MIN(2 - D{j}, 1)) * RA17A(K)",
        f"        WWIN(K) := WWIN(K) - JH * REAL(MIN(2 - D{i}, 1) * MIN(D{j}, 1)) * RA17B(K)",
    ]
    i, j = N - 1, 0
    L += [
        f"        WWIN(K) := WWIN(K) - JH * REAL(MIN(D{i}, 1) * MIN(2 - D{j}, 1)) * RA18A(K)",
        f"        WWIN(K) := WWIN(K) - JH * REAL(MIN(2 - D{i}, 1) * MIN(D{j}, 1)) * RA18B(K)",
        "      ENDDO",
        "      ! ── kernel A: diag + bonds i<=N-3 from the ring, accumulate ──",
        "      DO K = 1, QT",
        "        Q := K - 1 + TB",
    ]
    for i in range(N):
        L.append(f"        D{i} := MOD(Q, 3)")
        if i < N - 1:
            L.append("        Q := Q / 3")
    dg = " + ".join(f"(D{i} - 1) * (D{i} - 1)" for i in range(N))
    L.append(f"        DG := {dg}")
    L.append("        SL := MOD(K + TB - 1 + WINA, WINA) + 1")
    L.append("        WWIN(K) := WWIN(K) + (REAL(DG) * 0.5 - SHIFT) * VA(SL)")
    for i in range(N - 2):
        j = i + 1
        pi, pj = 3 ** i, 3 ** j
        for sign, m1, m2 in (("-", i, j), ("+", j, i)):
            off = f"- {pi} + {pj}" if sign == "-" else f"+ {pi} - {pj}"
            L.append(f"        SL := MOD(K + TB {off} - 1 + WINA, WINA) + 1")
            L.append(f"        WWIN(K) := WWIN(K) - JH * "
                     f"REAL(MIN({'2 - D' + str(j) if sign == '-' else 'D' + str(j)}, 1) * "
                     f"MIN({'D' + str(i) if sign == '-' else '2 - D' + str(i)}, 1)) * VA(SL)")
    L += [
        "      ENDDO",
        "      ! ── per-tile reduction (RHO/NRM2T accumulate in tile order) ──",
        "      RHOP := 0.0",
        "      R2 := 0.0",
        "      DO K = 1, QT",
        "        SL := MOD(K + TB - 1 + WINA, WINA) + 1",
        "        RHOP := RHOP + VA(SL) * WWIN(K)",
        "        R2 := R2 + WWIN(K) * WWIN(K)",
        "      ENDDO",
        "      RHO := RHO + RHOP",
        "      NRM2T := NRM2T + R2",
        "      ! ── fetch the tile output to the host ──",
        "      CALL VK_FETCH(HW, WWIN, 1, TB + 1, QT)",
        "    ENDDO",
        "    NRM := SQRT(NRM2T)",
        "    ! first pass: checksum the raw-seed matvec, then fall through",
        "    IF (ITER == 1) THEN",
        "      C1 := 0.0",
        "      C2 := 0.0",
        "      DO K = 1, DIM",
        "        IF (K == 1) THEN",
        "          IF (DIM == 999999) THEN",
        '            WRITE(*, "unreachable") ',
        "          ENDIF",
        "        ENDIF",
        "        C1 := C1 + HW(K)",
        "        C2 := C2 + HW(K) * REAL(1 + MOD(K, 7))",
        "      ENDDO",
        '      WRITE(*, "mv1 c1=%.17e c2=%.17e") C1, C2',
        '      WRITE(*, "mv1 w0=%.17e wmid=%.17e wlast=%.17e") '
        "HW(1), HW(DIM / 2 + 1), HW(DIM)",
        "    ENDIF",
        "    ! V <- HW / NRM (CPU pass; WRITE disqualifier keeps it off GPU)",
        "    DO K = 1, DIM",
        "      IF (K == 1) THEN",
        "        IF (ITER == 999999) THEN",
        '          WRITE(*, "unreachable") ',
        "        ENDIF",
        "      ENDIF",
        "      V(K) := HW(K) / NRM",
        "    ENDDO",
        "    DRHO := ABS(RHO - RHOOLD)",
        "    RHOOLD := RHO",
        "    IF (MOD(ITER, 50) == 0) THEN",
        '      WRITE(*, "iter %d  E0 %.10f  drho %.3e") ITER, RHO + SHIFT, DRHO',
        "    ENDIF",
        "    IF (ITER > 1) THEN",
        "      IF (DRHO < TOLC) THEN",
        "        CONV := 1",
        "      ENDIF",
        "    ENDIF",
        "  ENDIF",
        "ENDDO",
        'WRITE(*, "E0 = %.10f  iters %d") RHO + SHIFT, ITER - 1',
    ]
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    main()
