#!/usr/bin/env python3
"""gen_ed_matvec.py — generate matrix-free ED power-iteration programs.

Emits two variants of the ternary-rotor-chain matvec (original gauge,
B=0.25 so the field term V = K_PHASE - B*K_BIAS = 0 and H is real):
  resident : full V/W on GPU (N <= 17; V+W f64 <= ~2.1 GB)
  streamed : V resident, W produced through a QT-element window buffer
             per tile and downloaded to a host array (N = 18; V ~3.1 GB
             stays put, W streams through the host)

  out[x] = (diag(x) - SHIFT) v[x]
           - JH sum_i [ (d_i>=1, d_j<=1) v[x-3^i+3^j]
                      + (d_i<=1, d_j>=1) v[x+3^i-3^j] ]
  diag(x) = sum_i ((d_i-1)^2)/2,  d_i = (x // 3^i) % 3,  j = i+1 mod N

Index safety: masked bond reads use a MOD-wrapped index so mask=0 reads
stay in-bounds (when the digit mask is 1 the wrapped index provably
equals the raw one — no value change). The field term (-halfV) is
omitted at B=0.25 (V=0 identically; the generator notes this).

Power iteration on H~ = H - SHIFT*I (SHIFT=3 keeps the ground state
dominant, |E0-3|=5.86 > |Emax-3|~4), Rayleigh rho = v.w with v
normalized, E0 = rho + SHIFT. Reductions are the Inc-1 ordered combine
(deterministic). Seed: V(K) := 0.5 + REAL(MOD(K, 9973)) * 0.0001 —
must match min/phase_ed/ed_ref.py.

Usage: python3 min/phase_ed/gen_ed_matvec.py N [resident|streamed] > ed_power_N{n}.ergo
"""
import sys


def matvec_body(N, out_arr, in_arr, tb, indent, qt_dim="DIM"):
    """Unrolled matrix-free matvec for output element K (1-based).
    tb: "" for resident (global x = K-1) or "+TB" for windowed."""
    p = " " * indent
    L = []
    L.append(f"{p}Q := K - 1{tb}")
    for i in range(N):
        L.append(f"{p}D{i} := MOD(Q, 3)")
        if i < N - 1:
            L.append(f"{p}Q := Q / 3")
    dg = " + ".join(f"(D{i} - 1) * (D{i} - 1)" for i in range(N))
    L.append(f"{p}DG := {dg}")
    L.append(f"{p}{out_arr}(K) := (REAL(DG) * 0.5 - SHIFT) * {in_arr}(K{tb})")
    for i in range(N):
        j = (i + 1) % N
        pi, pj = 3 ** i, 3 ** j
        # (d_i>=1, d_j<=1): v[x - 3^i + 3^j]
        L.append(f"{p}SX := K{tb} - {pi} + {pj}")
        L.append(f"{p}SX := MOD(SX - 1 + {qt_dim}, {qt_dim}) + 1")
        L.append(f"{p}{out_arr}(K) := {out_arr}(K) - JH * "
                 f"REAL(MIN(D{i}, 1) * MIN(2 - D{j}, 1)) * {in_arr}(SX)")
        # (d_i<=1, d_j>=1): v[x + 3^i - 3^j]
        L.append(f"{p}SX := K{tb} + {pi} - {pj}")
        L.append(f"{p}SX := MOD(SX - 1 + {qt_dim}, {qt_dim}) + 1")
        L.append(f"{p}{out_arr}(K) := {out_arr}(K) - JH * "
                 f"REAL(MIN(2 - D{i}, 1) * MIN(D{j}, 1)) * {in_arr}(SX)")
    return L


def header(N, variant, extra):
    return f"""! ed_power_N{N}.ergo — GENERATED by gen_ed_matvec.py ({variant}); do not edit.
! Matrix-free power iteration, ternary rotor chain, N={N}, dim=3^{N}.
! Original gauge at B=0.25, J=1.0 (V = K_PHASE - B*K_BIAS = 0: real
! Hamiltonian, no field terms — see gen_ed_matvec.py). SHIFT = 2N baked
! into the diagonal: Emax <= 1.5N < 2N makes H~ negative definite so
! the ground state dominates power iteration at any N (the stage0
! shift-3 dominance is N=8-specific — it fails for N>=10, measured:
! N=14 converged to the spectrum top +11.68). E0 = rho + SHIFT.
! Oracles: stage0_check.md (N=8) and ed_ref.py (matvec + eigsh E0).
! First matvec is checksummed before the iteration loop (raw seed) so
! the full matvec vector can be compared against the numba bridge.
{extra}"""


def resident(N):
    DIM = 3 ** N
    L = [header(N, "resident",
                "! Resident variant: full V/W on the GPU (no tiling —\n"
                "! single whole-range dispatches; deterministic reductions).")]
    L += [
        "IMPLICIT NONE",
        f"INTEGER, PARAMETER :: N = {N}",
        f"INTEGER, PARAMETER :: DIM = {DIM}",
        "INTEGER, PARAMETER :: NITER = 3000",
        f"REAL, PARAMETER :: SHIFT = {2.0 * N:.1f}, JH = 0.5, TOLC = 1.0e-12",
        f"STATIC REAL :: V({DIM}), W({DIM})",
        "REAL :: RHO, NRM, NRM2T, RHOOLD, DRHO, C1, C2",
        f"INTEGER :: K, ITER, CONV, Q, SX, DG, {', '.join(f'D{i}' for i in range(N))}",
        "",
        "! deterministic seed",
        "DO K = 1, DIM",
        "  V(K) := 0.5 + REAL(MOD(K, 9973)) * 0.0001",
        "  W(K) := 0.0",
        "ENDDO",
        "",
        "! first matvec (raw seed) + checksum for the numba-bridge compare",
        "DO K = 1, DIM",
    ]
    L += matvec_body(N, "W", "V", "", 2)
    L += [
        "ENDDO",
        "C1 := 0.0",
        "C2 := 0.0",
        "DO K = 1, DIM",
        "  C1 := C1 + W(K)",
        "  C2 := C2 + W(K) * REAL(1 + MOD(K, 7))",
        "ENDDO",
        'WRITE(*, "mv1 c1=%.17e c2=%.17e") C1, C2',
        'WRITE(*, "mv1 w0=%.17e wmid=%.17e wlast=%.17e") '
        "W(1), W(DIM / 2 + 1), W(DIM)",
        "",
        "! normalize into V, then power-iterate",
        "NRM2T := 0.0",
        "DO K = 1, DIM",
        "  NRM2T := NRM2T + W(K) * W(K)",
        "ENDDO",
        "NRM := SQRT(NRM2T)",
        "DO K = 1, DIM",
        "  V(K) := W(K) / NRM",
        "ENDDO",
        "RHOOLD := RHO",
        "CONV := 0",
        "DO ITER = 1, NITER",
        "  IF (CONV == 0) THEN",
        "    DO K = 1, DIM",
    ]
    L += matvec_body(N, "W", "V", "", 6)
    L += [
        "    ENDDO",
        "    RHO := 0.0",
        "    NRM2T := 0.0",
        "    DO K = 1, DIM",
        "      RHO := RHO + V(K) * W(K)",
        "      NRM2T := NRM2T + W(K) * W(K)",
        "    ENDDO",
        "    NRM := SQRT(NRM2T)",
        "    DO K = 1, DIM",
        "      V(K) := W(K) / NRM",
        "    ENDDO",
        "    DRHO := ABS(RHO - RHOOLD)",
        "    RHOOLD := RHO",
        '    IF (MOD(ITER, 100) == 0) THEN',
        '      WRITE(*, "iter %d  E0 %.10f  drho %.3e") ITER, RHO + SHIFT, DRHO',
        "    ENDIF",
        "    IF (DRHO < TOLC) THEN",
        "      CONV := 1",
        "    ENDIF",
        "  ENDIF",
        "ENDDO",
        'WRITE(*, "E0 = %.10f  iters %d") RHO + SHIFT, ITER - 1',
    ]
    return "\n".join(L) + "\n"


def streamed(N):
    DIM = 3 ** N
    QT = 3 ** 16
    NT = DIM // QT
    assert DIM % QT == 0
    L = [header(N, "streamed",
                "! Streamed variant: V resident (~3.1 GB), W produced per\n"
                "! tile into the QT window WWIN and downloaded to host HW\n"
                "! (Inc-2B gather-window streaming v1 — one remote (the\n"
                "! window is the output, not the gather halo; V is fully\n"
                "! resident so all bond gathers hit it directly).\n"
                "! HW/V copies stay on the CPU via WRITE disqualifiers so\n"
                "! the host arrays never become GPU-resident (VRAM).\n"
                "! RHO/NRM2T accumulate across per-tile multi-reductions\n"
                "! (host combine adds onto the CPU accumulators in tile\n"
                "! order — deterministic).")]
    L += [
        "IMPLICIT NONE",
        f"INTEGER, PARAMETER :: N = {N}",
        f"INTEGER, PARAMETER :: DIM = {DIM}",
        f"INTEGER, PARAMETER :: QT = {QT}, NT = {NT}",
        "INTEGER, PARAMETER :: NITER = 3000",
        f"REAL, PARAMETER :: SHIFT = {2.0 * N:.1f}, JH = 0.5, TOLC = 1.0e-12",
        f"STATIC REAL :: V({DIM}), HW({DIM})",
        f"STATIC REAL :: WWIN({QT})",
        "REAL :: RHO, NRM, RHOOLD, DRHO, C1, C2, RHOP, NRM2T, RHO2",
        f"INTEGER :: K, T, TB, ITER, CONV, Q, SX, DG, {', '.join(f'D{i}' for i in range(N))}",
        "",
        "! deterministic seed",
        "DO K = 1, DIM",
        "  V(K) := 0.5 + REAL(MOD(K, 9973)) * 0.0001",
        "ENDDO",
        "",
        "! first matvec (raw seed) + checksum; HW assembled on the host",
        "DO T = 1, NT",
        "  TB := (T - 1) * QT",
        "  DO K = 1, QT",
    ]
    L += matvec_body(N, "WWIN", "V", " + TB", 4)
    L += [
        "  ENDDO",
        "  DO K = 1, QT",
        "    IF (K == 1) THEN",
        "      IF (T == 999999) THEN",
        '        WRITE(*, "unreachable") ',
        "      ENDIF",
        "    ENDIF",
        "    HW(K + TB) := WWIN(K)",
        "  ENDDO",
        "ENDDO",
        "C1 := 0.0",
        "C2 := 0.0",
        "DO K = 1, DIM",
        "  IF (K == 1) THEN",
        "    IF (DIM == 999999) THEN",
        '      WRITE(*, "unreachable") ',
        "    ENDIF",
        "  ENDIF",
        "  C1 := C1 + HW(K)",
        "  C2 := C2 + HW(K) * REAL(1 + MOD(K, 7))",
        "ENDDO",
        'WRITE(*, "mv1 c1=%.17e c2=%.17e") C1, C2',
        'WRITE(*, "mv1 w0=%.17e wmid=%.17e wlast=%.17e") '
        "HW(1), HW(DIM / 2 + 1), HW(DIM)",
        "",
        "NRM2T := 0.0",
        "DO K = 1, DIM",
        "  IF (K == 1) THEN",
        "    IF (DIM == 999999) THEN",
        '      WRITE(*, "unreachable") ',
        "    ENDIF",
        "  ENDIF",
        "  NRM2T := NRM2T + HW(K) * HW(K)",
        "ENDDO",
        "NRM := SQRT(NRM2T)",
        "RHOOLD := 0.0",
        "CONV := 0",
        "DO ITER = 1, NITER",
        "  IF (CONV == 0) THEN",
        "    ! V <- HW / NRM (CPU pass; kept out of the GPU by the WRITE)",
        "    DO K = 1, DIM",
        "      IF (K == 1) THEN",
        "        IF (ITER == 999999) THEN",
        '          WRITE(*, "unreachable") ',
        "        ENDIF",
        "      ENDIF",
        "      V(K) := HW(K) / NRM",
        "    ENDDO",
        "    RHO := 0.0",
        "    NRM2T := 0.0",
        "    DO T = 1, NT",
        "      TB := (T - 1) * QT",
        "      DO K = 1, QT",
    ]
    L += matvec_body(N, "WWIN", "V", " + TB", 8)
    L += [
        "      ENDDO",
        "      RHOP := 0.0",
        "      RHO2 := 0.0",
        "      DO K = 1, QT",
        "        RHOP := RHOP + V(K + TB) * WWIN(K)",
        "        RHO2 := RHO2 + WWIN(K) * WWIN(K)",
        "      ENDDO",
        "      RHO := RHO + RHOP",
        "      NRM2T := NRM2T + RHO2",
        "      DO K = 1, QT",
        "        IF (K == 1) THEN",
        "          IF (ITER == 999999) THEN",
        '            WRITE(*, "unreachable") ',
        "          ENDIF",
        "        ENDIF",
        "        HW(K + TB) := WWIN(K)",
        "      ENDDO",
        "    ENDDO",
        "    NRM := SQRT(NRM2T)",
        "    DRHO := ABS(RHO - RHOOLD)",
        "    RHOOLD := RHO",
        "    IF (MOD(ITER, 100) == 0) THEN",
        '      WRITE(*, "iter %d  E0 %.10f  drho %.3e") ITER, RHO + SHIFT, DRHO',
        "    ENDIF",
        "    IF (DRHO < TOLC) THEN",
        "      CONV := 1",
        "    ENDIF",
        "  ENDIF",
        "ENDDO",
        'WRITE(*, "E0 = %.10f  iters %d") RHO + SHIFT, ITER - 1',
    ]
    return "\n".join(L) + "\n"


def main():
    N = int(sys.argv[1])
    variant = sys.argv[2] if len(sys.argv) > 2 else (
        "resident" if N <= 17 else "streamed")
    if variant == "resident":
        sys.stdout.write(resident(N))
    elif variant == "streamed":
        sys.stdout.write(streamed(N))
    else:
        sys.exit(f"unknown variant {variant}")


if __name__ == "__main__":
    main()
