"""Stage B generator: stageB_observables.ergo — correlators and entanglement
entropy (Jacobi eigensolver on the Gram matrix) in Ergo.

Reuses the Stage A machinery (tables, complex power iteration, ground
state only). Per point:
  C(r) = <v|Tm_i Tp_j|v>, r = 1..6, averaged over 12 cyclic pairs
  (complex expectation of the real shift operator).
  S(l), l = 1..4: reshape psi to A (3^l x 3^(N-l)) complex, Gram
  G = A_r A_r^T + A_i A_i^T (81x81 max), cyclic Jacobi eigen-solve,
  S = -sum p_k ln p_k; CC fit c = 3 * slope of S vs
  log[(N/pi) sin(pi l / N)] over the 4 cuts.
"""

import os

N = 12
DIM = 3 ** N
TT = 6 * N
NB = 2 * N
SHIFT = 4.0
HERE = os.path.dirname(os.path.abspath(__file__))

# reuse the table build + eigensolver body from stageA by extraction
src = open(os.path.join(HERE, "stageA_complex.ergo")).read()
tbl_start = src.index("! ============ table build")
tbl_end = src.index("! ============ per-point loop")
TABLE_BUILD = src[tbl_start:tbl_end]

ergo = f"""! stageB_observables.ergo - GENERATED by gen_ergo_stageB.py (do not edit)
! Ground state + C(r) correlators + entanglement entropy via Jacobi.
IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: DIM = {DIM}
INTEGER, PARAMETER :: TT = {TT}
INTEGER, PARAMETER :: NB = {NB}
INTEGER, PARAMETER :: MAXIT = 20000
REAL, PARAMETER :: SHIFT = {SHIFT}

STATIC INTEGER :: SRC(DIM, TT)
STATIC REAL :: CFAC(TT), SFAC(TT)
STATIC REAL :: DIAG(DIM)
STATIC REAL :: VR(DIM + 1), VI(DIM + 1), WR(DIM + 1), WI(DIM + 1)
STATIC REAL :: YR(DIM + 1), YI(DIM + 1), ZR(DIM + 1), ZI(DIM + 1)
STATIC REAL :: BJ2 = 0.0
STATIC REAL :: VV = 0.0
STATIC REAL :: AR(81, 6561), AI(81, 6561), G(81, 81)
STATIC REAL :: SS(4), XX(4)

REAL :: RHO, RHO_OLD, NRM, E0, A0, A1, CR, CI, CR2, CI2, TH
REAL :: CSUM, SCALE, TH, C, SN, APP, AQQ, APQ
INTEGER :: I, X, T, Q, D, J, DI, DJ, PI, PJ, B, KB, K, NCONV, DG({N})
INTEGER :: R, L, RL, CL, R0, C0, P0, Q0, SWEEP

REAL :: BTAB2(3), JTAB2(3)
DATA BTAB2 / 0.25, 0.1, 0.1 /
DATA JTAB2 / 1.0, 1.0, 2.0 /

! ============ table build ============
{TABLE_BUILD}
VR(DIM + 1) := 0.0
VI(DIM + 1) := 0.0

! ============ per-point loop (3 points) ============
DO KB = 1, 3
  BJ2 := JTAB2(KB) / 2.0
  VV := 0.5 - 2.0 * BTAB2(KB)
  DO T = 1, TT
    CFAC(T) := 0.0
    SFAC(T) := 0.0
  ENDDO
  DO I = 1, N
    CFAC(2 * {N} + 2 * I - 1) := 0.0 - VV * COS(6.283185307179586 * REAL(I - 1) / REAL({N})) / 2.0
    CFAC(2 * {N} + 2 * I) := CFAC(2 * {N} + 2 * I - 1)
    SFAC(4 * {N} + 2 * I - 1) := VV * SIN(6.283185307179586 * REAL(I - 1) / REAL({N})) / 2.0
    SFAC(4 * {N} + 2 * I) := 0.0 - SFAC(4 * {N} + 2 * I - 1)
  ENDDO

  ! ---- ground state ----
  DO I = 1, DIM
    VR(I) := MOD(37*I, 101) / 101.0 - 0.5
    VI(I) := MOD(53*I + 7, 101) / 101.0 - 0.5
  ENDDO
  NRM := SQRT(DOT_PRODUCT(VR, VR) + DOT_PRODUCT(VI, VI))
  DO I = 1, DIM
    VR(I) := VR(I) / NRM
    VI(I) := VI(I) / NRM
  ENDDO
  RHO_OLD := 0.0
  RHO := 0.0
  K := 1
  DO WHILE (K <= MAXIT)
    DO I = 1, DIM
      A0 := DIAG(I) * VR(I)
      A1 := DIAG(I) * VI(I)
      DO T = 1, NB
        A0 := A0 - BJ2 * VR(SRC(I,T))
        A1 := A1 - BJ2 * VI(SRC(I,T))
      ENDDO
      DO T = NB + 1, 2 * NB
        A0 := A0 + CFAC(T) * VR(SRC(I,T))
        A1 := A1 + CFAC(T) * VI(SRC(I,T))
      ENDDO
      YR(I) := A0
      YI(I) := A1
    ENDDO
    DO I = 1, DIM
      A0 := 0.0
      A1 := 0.0
      DO T = 2 * NB + 1, TT
        A0 := A0 + SFAC(T) * VR(SRC(I,T))
        A1 := A1 + SFAC(T) * VI(SRC(I,T))
      ENDDO
      ZR(I) := A0
      ZI(I) := A1
    ENDDO
    DO I = 1, DIM
      WR(I) := YR(I) - ZI(I)
      WI(I) := YI(I) + ZR(I)
    ENDDO
    RHO := DOT_PRODUCT(VR, WR) + DOT_PRODUCT(VI, WI) + SHIFT
    NRM := SQRT(DOT_PRODUCT(WR, WR) + DOT_PRODUCT(WI, WI))
    DO I = 1, DIM
      VR(I) := WR(I) / NRM
      VI(I) := WI(I) / NRM
    ENDDO
    IF (ABS(RHO - RHO_OLD) < 1E-12) THEN
      K := MAXIT + 1
    ENDIF
    RHO_OLD := RHO
    K := K + 1
  ENDDO
  E0 := RHO

  ! ---- correlators C(r), r = 1..6 ----
  DO R = 1, 6
    CR := 0.0
    CI := 0.0
    DO I = 1, N
      J := I + R
      IF (J > {N}) THEN
        J := J - {N}
      ENDIF
      PI := 3 ** (I - 1)
      PJ := 3 ** (J - 1)
      ! TMP = Tm_i Tp_j V : source X - PI + PJ when (di>=1, dj<=1)
      DO X = 1, DIM
        DI := MOD((X - 1) / PI, 3)
        DJ := MOD((X - 1) / PJ, 3)
        IF (DI >= 1) THEN
          IF (DJ <= 1) THEN
            YR(X) := VR(X - PI + PJ)
            YI(X) := VI(X - PI + PJ)
          ELSE
            YR(X) := 0.0
            YI(X) := 0.0
          ENDIF
        ELSE
          YR(X) := 0.0
          YI(X) := 0.0
        ENDIF
      ENDDO
      CR := CR + DOT_PRODUCT(VR, YR) + DOT_PRODUCT(VI, YI)
      CI := CI + DOT_PRODUCT(VR, YI) - DOT_PRODUCT(VI, YR)
    ENDDO
    CR := CR / REAL({N})
    CI := CI / REAL({N})
    WRITE(*, "C B=%.2f J=%.1f r=%d %.6f %.6f %.6f") BTAB2(KB), JTAB2(KB), R, CR, CI, SQRT(CR*CR + CI*CI)
  ENDDO

  ! ---- entanglement entropy S(l), l = 1..4 ----
  DO L = 1, 4
    RL := 3 ** L
    CL := 3 ** ({N} - L)
    ! build A (complex): row = config of sites 1..L, col = rest
    DO R0 = 1, 81
      DO C0 = 1, 6561
        AR(R0, C0) := 0.0
        AI(R0, C0) := 0.0
      ENDDO
    ENDDO
    DO X = 1, DIM
      R0 := MOD(X - 1, RL) + 1
      C0 := (X - 1) / RL + 1
      AR(R0, C0) := VR(X)
      AI(R0, C0) := VI(X)
    ENDDO
    ! Gram G = AR AR^T + AI AI^T (RL x RL)
    DO R0 = 1, RL
      DO Q0 = 1, RL
        A0 := 0.0
        DO C0 = 1, CL
          A0 := A0 + AR(R0, C0) * AR(Q0, C0) + AI(R0, C0) * AI(Q0, C0)
        ENDDO
        G(R0, Q0) := A0
      ENDDO
    ENDDO
    ! cyclic Jacobi eigen-solve (symmetric, RL x RL)
    DO SWEEP = 1, 12
      SCALE := 0.0
      DO P0 = 1, RL
        DO Q0 = P0 + 1, RL
          IF (ABS(G(P0, Q0)) > SCALE) THEN
            SCALE := ABS(G(P0, Q0))
          ENDIF
        ENDDO
      ENDDO
      IF (SCALE > 1E-12) THEN
        DO P0 = 1, RL
          DO Q0 = P0 + 1, RL
            IF (ABS(G(P0, Q0)) > 1E-14) THEN
              APP := G(P0, P0)
              AQQ := G(Q0, Q0)
              APQ := G(P0, Q0)
              TAU := (AQQ - APP) / (2.0 * APQ)
              IF (TAU >= 0.0) THEN
                TH := 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
              ELSE
                TH := 0.0 - 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
              ENDIF
              C := 1.0 / SQRT(1.0 + TH * TH)
              SN := TH * C
              ! rotate rows/cols P0,Q0
              DO C0 = 1, RL
                A0 := G(C0, P0)
                A1 := G(C0, Q0)
                G(C0, P0) := C * A0 - SN * A1
                G(C0, Q0) := SN * A0 + C * A1
              ENDDO
              DO C0 = 1, RL
                A0 := G(P0, C0)
                A1 := G(Q0, C0)
                G(P0, C0) := C * A0 - SN * A1
                G(Q0, C0) := SN * A0 + C * A1
              ENDDO
            ENDIF
          ENDDO
        ENDDO
      ENDIF
    ENDDO
    ! S = -sum p ln p
    SS(L) := 0.0
    DO R0 = 1, RL
      IF (G(R0, R0) > 1E-15) THEN
        SS(L) := SS(L) - G(R0, R0) * LOG(G(R0, R0))
      ENDIF
    ENDDO
    XX(L) := LOG((REAL({N}) / 3.14159265358979) * SIN(3.14159265358979 * REAL(L) / REAL({N})))
    WRITE(*, "S B=%.2f J=%.1f l=%d %.6f") BTAB2(KB), JTAB2(KB), L, SS(L)
  ENDDO

  ! ---- CC fit over l = 1..4 ----
  ! 2-param least squares by hand: c = 3 * cov/var
  A0 := 0.0
  A1 := 0.0
  CR := 0.0
  CI := 0.0
  DO L = 1, 4
    A0 := A0 + XX(L)
    A1 := A1 + SS(L)
    CR := CR + XX(L) * XX(L)
    CI := CI + XX(L) * SS(L)
  ENDDO
  A0 := A0 / 4.0
  A1 := A1 / 4.0
  CSUM := (CI - 4.0 * A0 * A1) / (CR - 4.0 * A0 * A0)
  WRITE(*, "CC B=%.2f J=%.1f E0=%.10f c=%.4f") BTAB2(KB), JTAB2(KB), E0, 3.0 * CSUM
ENDDO

WRITE(*, "# DONE")
"""

with open(os.path.join(HERE, "stageB_observables.ergo"), "w") as f:
    f.write(ergo)
print("wrote stageB_observables.ergo")
