"""Stage 5 generator v2: stage4_n14.ergo — N=14 packed sweep (extractable form).

Memory budget (N=14, DIM = 3^14 = 4 782 969, NP = 21*DIM = 100 442 349):
  vectors V, W, GS (phase-shared; V2/W2 eliminated)   3 x 803 MB = 2.41 GB
  packed tables LOCOF/BLKOF int32 + BJ2E f64                    1.61 GB
  block tables SRC int32 (4.78M x 28) + DIAG f64                0.57 GB
  total device ~4.6 GB (fits 5.4 GB free).
Tricks:
  - mask table eliminated: SRC sentinel = NP+1 with V(NP+1) := 0, and
    every term is A := A - BJ2E(I) * V(SRC(...) + offset) since the mask
    was uniformly -1 (bond coefficient -J/2 = -(JTAB/2)).
  - shift sigma = 4.0 stays past the N=14 spectral midpoint
    (Emax(J=0) = 14*0.5 = 7, |Emax-4| = 3 < |E0-4| = 4).
  - per-element lookup tables avoid ALL division in kernel indices
    (the stage-4 form that extracts cleanly); offset = I - LOCOF(I).
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
N = 14
DIM = 3 ** N
NB = 21
TT = 2 * N
NBATCH = 120
SHIFT = 4.0
NP = NB * DIM


def matvec(vin, vout):
    terms = "\n".join(
        f"      A := A - BJ2E(I) * {vin}(SRC(LOCOF(I),{t}) + I - LOCOF(I))"
        for t in range(1, TT + 1))
    return f"""    DO I = 1, NP
      A := DIAG(LOCOF(I)) * {vin}(I)
{terms}
      {vout}(I) := A
    ENDDO"""


def reduct(arr1, arr2, target):
    return f"""      ACC := 0.0
      DO I = 1, DIM
        ACC := ACC + {arr1}(I + (B-1)*DIM) * {arr2}(I + (B-1)*DIM)
      ENDDO
      {target}(B) := ACC"""


ergo = f"""! stage4_n14.ergo - GENERATED by gen_ergo_stage5.py v2 (do not edit)
! N=14 packed sweep (21 J-points), single packed matvec, phase-shared
! vectors, sentinel-zero mask elimination. Shift sigma = 4.0 (past N=14
! spectral midpoint). NBATCH = 120.
IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: DIM = {DIM}
INTEGER, PARAMETER :: NP = {NP}
INTEGER, PARAMETER :: NB = {NB}
INTEGER, PARAMETER :: TT = {TT}
INTEGER, PARAMETER :: NBATCH = {NBATCH}
REAL, PARAMETER :: SHIFT = {SHIFT}

STATIC INTEGER :: SRC(DIM, TT)
STATIC REAL :: DIAG(DIM)
STATIC REAL :: JTAB(NB)
STATIC INTEGER :: LOCOF(NP), BLKOF(NP)
STATIC REAL :: BJ2E(NP)
STATIC REAL :: V(NP + 1), W(NP + 1), GS(NP + 1)
STATIC REAL :: E0(NB), E1(NB), RH(NB), RHOLD(NB)
STATIC REAL :: NRT(NB), DV(NB), S1(NB), S2(NB), S3(NB), S4(NB)
STATIC INTEGER :: CONV(NB), CONV2(NB)
STATIC REAL :: ACC = 0.0
STATIC REAL :: A = 0.0

DATA JTAB / 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, &
  1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0 /

REAL :: GAPV
INTEGER :: I, X, T, Q, D, J, DI, DJ, PI, PJ, B, KB, KP, NCONV, DG({N})

! ============ runtime table build (host, once) ============
DO I = 1, NP
  LOCOF(I) := MOD(I - 1, DIM) + 1
  BLKOF(I) := (I - 1) / DIM + 1
ENDDO
DO I = 1, NP
  BJ2E(I) := JTAB(BLKOF(I)) / 2.0
ENDDO
V(NP + 1) := 0.0
W(NP + 1) := 0.0
GS(NP + 1) := 0.0
DO X = 1, DIM
  Q := X - 1
  DIAG(X) := 0.0 - SHIFT
  DO I = 1, N
    D := MOD(Q, 3)
    Q := Q / 3
    DIAG(X) := DIAG(X) + REAL((D - 1) * (D - 1)) / 2.0
  ENDDO
ENDDO
DO X = 1, DIM
  DO T = 1, TT
    SRC(X, T) := NP + 1
  ENDDO
ENDDO
DO X = 1, DIM
  Q := X - 1
  DO I = 1, N
    DG(I) := MOD(Q, 3)
    Q := Q / 3
  ENDDO
  T := 1
  DO I = 1, N
    J := I + 1
    IF (J > {N}) THEN
      J := 1
    ENDIF
    DI := DG(I)
    DJ := DG(J)
    PI := 3 ** (I - 1)
    PJ := 3 ** (J - 1)
    IF (DI >= 1) THEN
      IF (DJ <= 1) THEN
        SRC(X, T) := X - PI + PJ
        T := T + 1
      ENDIF
    ENDIF
    IF (DI <= 1) THEN
      IF (DJ >= 1) THEN
        SRC(X, T) := X + PI - PJ
        T := T + 1
      ENDIF
    ENDIF
  ENDDO
ENDDO

! ============ cold deterministic seeds (packed) ============
DO I = 1, NP
  V(I) := MOD(37*I, 101) / 101.0 - 0.5
ENDDO
DO B = 1, NB
  CONV(B) := 0
  CONV2(B) := 0
  RH(B) := 0.0
  RHOLD(B) := 0.0
ENDDO
NCONV := 0

! ============ PHASE 1: ground states ============
DO KB = 1, NBATCH
  IF (NCONV < NB) THEN
    DO KP = 1, 8
{matvec("V", "W")}
{matvec("W", "V")}
    ENDDO
{matvec("V", "W")}
    DO B = 1, NB
{reduct("V", "W", "S1")}
{reduct("W", "W", "S2")}
{reduct("V", "V", "S3")}
    ENDDO
    DO B = 1, NB
      RH(B) := S1(B) / S3(B) + SHIFT
      NRT(B) := 1.0 / SQRT(S2(B))
      IF (CONV(B) == 0) THEN
        IF (ABS(RH(B) - RHOLD(B)) < 1E-12) THEN
          CONV(B) := KB
          NCONV := NCONV + 1
        ENDIF
      ENDIF
      RHOLD(B) := RH(B)
    ENDDO
    DO I = 1, NP
      V(I) := W(I) * NRT(BLKOF(I))
    ENDDO
  ENDIF
ENDDO
DO B = 1, NB
  E0(B) := RH(B)
ENDDO
DO I = 1, NP
  GS(I) := V(I)
ENDDO

! ============ PHASE 2: deflated (E1), reuses V/W ============
NCONV := 0
DO B = 1, NB
  RHOLD(B) := 0.0
ENDDO
DO I = 1, NP
  V(I) := MOD(53*I + 7, 101) / 101.0 - 0.5
ENDDO
DO KB = 1, NBATCH
  IF (NCONV < NB) THEN
    DO KP = 1, 8
{matvec("V", "W")}
{matvec("W", "V")}
    ENDDO
{matvec("V", "W")}
    DO B = 1, NB
{reduct("V", "W", "S1")}
{reduct("W", "W", "S2")}
{reduct("V", "V", "S3")}
{reduct("W", "GS", "S4")}
    ENDDO
    DO B = 1, NB
      DV(B) := S4(B)
      RH(B) := S1(B) / S3(B) + SHIFT
      NRT(B) := 1.0 / SQRT(S2(B))
      IF (CONV2(B) == 0) THEN
        IF (ABS(RH(B) - RHOLD(B)) < 1E-12) THEN
          CONV2(B) := KB
          NCONV := NCONV + 1
        ENDIF
      ENDIF
      RHOLD(B) := RH(B)
    ENDDO
    DO I = 1, NP
      A := W(I) - DV(BLKOF(I)) * GS(I)
      W(I) := A
      V(I) := A * NRT(BLKOF(I))
    ENDDO
  ENDIF
ENDDO
DO B = 1, NB
  E1(B) := RH(B)
ENDDO

! ============ output ============
DO B = 1, NB
  GAPV := E1(B) - E0(B)
  WRITE(*, "%.2f %.10f %.6f %d %d") JTAB(B), E0(B), GAPV, CONV(B), CONV2(B)
ENDDO
"""

with open(os.path.join(HERE, "stage4_n14.ergo"), "w") as f:
    f.write(ergo)
print("wrote stage4_n14.ergo")
