"""Stage 3b generator v2: emit stage3_gpu.ergo — the 21-point J-sweep
restructured so the HOT loops actually extract to SPIR-V.

Compiler facts driving this structure (ir_gpu.py):
  - extract_kernels "scans main_body" only: SUBROUTINE loops are never
    extracted -> the matvec is INLINED at both call sites.
  - WHILE loops are not traversed for extraction -> the convergence loop
    becomes a fixed-count DO K = 1, KMAX. Correctness is preserved
    because the power-iteration fixed point is IDEMPOTENT: once
    converged, further iterations leave the vector unchanged, so running
    extra iterations is harmless. A CONV flag records the iteration at
    which |d rho| < 1e-12 was first reached (reported per point; a point
    with CONV = 0 at the end FAILED to converge and is flagged).
  - Nested DO loops: the outer loop is rejected but the pass recurses
    into its body, so inner DO loops (matvec, reductions, normalize)
    extract as long as no DO/WHILE/IF-wraps them.
  - Dot/norm are explicit accumulator loops (REDUCTION extraction);
    DOT_PRODUCT/NORM2 intrinsics are deliberately not used.
  - Warm starts dropped: all 21 points independent (INJECTIVE batch).
"""

import os

N = 8
DIM = 3 ** N
SHIFT = 3.0
TT = 2 * N
NPTS = 21
KMAX1 = 2500   # ground runs (cold: 618 at J=1.0; headroom for slow points)
KMAX2 = 3000   # deflated runs (cold worst ~750 warm at J=0.1, headroom)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "stage3_gpu.ergo")

p3 = [3 ** i for i in range(N)]
src = [[1] * TT for _ in range(DIM)]
mask = [[0.0] * TT for _ in range(DIM)]
diag = [0.0] * DIM
for x in range(DIM):
    digits = [(x // p3[i]) % 3 for i in range(N)]
    diag[x] = sum((d - 1) ** 2 for d in digits) / 2.0 - SHIFT
    t = 0
    for i in range(N):
        j = (i + 1) % N
        di, dj = digits[i], digits[j]
        if di >= 1 and dj <= 1:
            src[x][t] = x - p3[i] + p3[j] + 1
            mask[x][t] = -1.0
            t += 1
        if di <= 1 and dj >= 1:
            src[x][t] = x + p3[i] - p3[j] + 1
            mask[x][t] = -1.0
            t += 1


def data_block(name, flat, fmt, per_line=16):
    lines = [f"DATA {name} / &"]
    for k in range(0, len(flat), per_line):
        chunk = ", ".join(fmt(v) for v in flat[k:k + per_line])
        lines.append("  " + chunk + (", &" if k + per_line < len(flat) else " /"))
    return "\n".join(lines)


src_flat = [src[x][t] for t in range(TT) for x in range(DIM)]
mask_flat = [mask[x][t] for t in range(TT) for x in range(DIM)]
jtab = [round(0.1 * k, 10) for k in range(NPTS)]

mv1 = "\n".join(
    f"      A := A + BJ2 * COEF(I,{t}) * V(SRC(I,{t}))"
    for t in range(1, TT + 1))
mv2 = "\n".join(
    f"      A := A + BJ2 * COEF(I,{t}) * V2(SRC(I,{t}))"
    for t in range(1, TT + 1))

ergo = f"""! stage3_gpu.ergo - GENERATED by gen_ergo_stage3.py v2 (do not edit)
! Stage 3b: batch J-sweep, rotor chain N=8, B=0.25, GPU-structured.
! Hot loops are inlined in main_body under plain DO loops so the SPIR-V
! extractor (main_body scan + recursion through non-extractable outer
! loops) can reach them. Convergence uses fixed-count DO K loops with an
! idempotent fixed point + CONV flag (see generator docstring).
IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: DIM = {DIM}
INTEGER, PARAMETER :: TT = {TT}
INTEGER, PARAMETER :: KMAX1 = {KMAX1}
INTEGER, PARAMETER :: KMAX2 = {KMAX2}
INTEGER, PARAMETER :: NPTS = {NPTS}
REAL, PARAMETER :: SHIFT = {SHIFT}

STATIC INTEGER :: SRC(DIM, TT)
STATIC REAL :: COEF(DIM, TT)
STATIC REAL :: DIAG(DIM)
STATIC REAL :: JTAB(NPTS)
STATIC REAL :: V(DIM), W(DIM), GS(DIM), V2(DIM), W2(DIM)
STATIC REAL :: BJ2 = 0.0
STATIC REAL :: ACC = 0.0
STATIC REAL :: ACCN = 0.0

{data_block("SRC", src_flat, str)}

{data_block("COEF", mask_flat, lambda v: f"{v:.1f}")}

{data_block("DIAG", diag, lambda v: f"{v:.17e}".replace("e", "E"))}

DATA JTAB / {", ".join(f"{v:.1f}" for v in jtab)} /

REAL :: RHO, RHO_OLD, RHO2, RHO2_OLD, NRM, E0, E1, GAPV, A
INTEGER :: I, K, P, ITERS1, ITERS2, CONV1, CONV2

DO P = 1, NPTS
  BJ2 := JTAB(P) / 2.0

  ! cold deterministic seeds -- every point independent
  DO I = 1, DIM
    V(I) := MOD(37*I, 101) / 101.0 - 0.5
    V2(I) := MOD(53*I + 7, 101) / 101.0 - 0.5
  ENDDO

  ! ---- ground state: fixed-count power iteration ----
  ACC := 0.0
  DO I = 1, DIM
    ACC := ACC + V(I) * V(I)
  ENDDO
  NRM := SQRT(ACC)
  DO I = 1, DIM
    V(I) := V(I) / NRM
  ENDDO
  RHO_OLD := 0.0
  RHO := 0.0
  ITERS1 := KMAX1 + 1
  CONV1 := 0
  DO K = 1, KMAX1
    DO I = 1, DIM
      A := DIAG(I) * V(I)
{mv1}
      W(I) := A
    ENDDO
    ACC := 0.0
    DO I = 1, DIM
      ACC := ACC + V(I) * W(I)
    ENDDO
    RHO := ACC + SHIFT
    ACCN := 0.0
    DO I = 1, DIM
      ACCN := ACCN + W(I) * W(I)
    ENDDO
    NRM := SQRT(ACCN)
    DO I = 1, DIM
      V(I) := W(I) / NRM
    ENDDO
    IF (CONV1 == 0) THEN
      IF (ABS(RHO - RHO_OLD) < 1E-12) THEN
        ITERS1 := K
        CONV1 := 1
      ENDIF
    ENDIF
    RHO_OLD := RHO
  ENDDO
  E0 := RHO
  DO I = 1, DIM
    GS(I) := V(I)
  ENDDO

  ! ---- deflated run: fixed-count power iteration ----
  ACC := 0.0
  DO I = 1, DIM
    ACC := ACC + V2(I) * V2(I)
  ENDDO
  NRM := SQRT(ACC)
  DO I = 1, DIM
    V2(I) := V2(I) / NRM
  ENDDO
  RHO2_OLD := 0.0
  RHO2 := 0.0
  ITERS2 := KMAX2 + 1
  CONV2 := 0
  DO K = 1, KMAX2
    DO I = 1, DIM
      A := DIAG(I) * V2(I)
{mv2}
      W2(I) := A
    ENDDO
    ACC := 0.0
    DO I = 1, DIM
      ACC := ACC + W2(I) * GS(I)
    ENDDO
    DO I = 1, DIM
      W2(I) := W2(I) - ACC * GS(I)
    ENDDO
    ACCN := 0.0
    DO I = 1, DIM
      ACCN := ACCN + V2(I) * W2(I)
    ENDDO
    RHO2 := ACCN + SHIFT
    ACCN := 0.0
    DO I = 1, DIM
      ACCN := ACCN + W2(I) * W2(I)
    ENDDO
    NRM := SQRT(ACCN)
    DO I = 1, DIM
      V2(I) := W2(I) / NRM
    ENDDO
    IF (CONV2 == 0) THEN
      IF (ABS(RHO2 - RHO2_OLD) < 1E-12) THEN
        ITERS2 := K
        CONV2 := 1
      ENDIF
    ENDIF
    RHO2_OLD := RHO2
  ENDDO
  E1 := RHO2
  GAPV := E1 - E0

  WRITE(*, "%.2f %.10f %.6f %d %d %d %d") JTAB(P), E0, GAPV, ITERS1, ITERS2, CONV1, CONV2
ENDDO
"""

with open(OUT, "w") as f:
    f.write(ergo)
print("wrote", OUT, "%.1f MB" % (len(ergo) / 1e6))
