"""Stage 4 generator: emit packed-batch Ergo sweeps (N=8 and N=12).

DESIGN (pack the batch into the data; no compiler changes):
  - All 21 J-points packed into one 1D vector of size NP = 21*DIMP.
    Packed H is block-diagonal: block b uses bond coefficient -JTAB(b)/2.
  - DIMP pads DIM to a multiple of 256 (the GPU workgroup size) so the
    segmented reductions (below) never straddle a block boundary within
    one workgroup. Pad elements stay exactly 0: pad table rows have
    COEF = 0, DIAG = 0, SRC = 1 (in-bounds dummy), pad seeds are 0.
  - No division in any kernel index: per-element lookup tables
    LOCOF(I) = MOD(I-1,DIMP)+1 (local index), BLKOF(I) = (I-1)/DIMP+1
    (block), BJ2E(I) = +JTAB(blk)/2 (bond coefficient), built at RUNTIME
    by host init loops (identical content to DATA tables; runtime build
    chosen because N=12 tables would be ~200 MB of source). The
    extraction question (division in a READ index) is thereby moot --
    reported in stage4_check.md.
  - Packed matvec is ONE INJECTIVE kernel:
      W(I) := DIAG(LOCOF(I))*V(I)
              + BJ2E(I)*COEF(LOCOF(I),t)*V(SRC(LOCOF(I),t) + I - LOCOF(I))
    (I - LOCOF(I) = block offset, arithmetic, no division).
  - Iterations batched by 16 (numeric safety: |lambda|^16 ~ 2e12, fine in
    f64): 8 ping-pong matvec pairs (V->W, W->V -- two kernels, no copy),
    1 eval matvec, then SEGMENTED REDUCTION kernels — one kernel per
    sum computes all 21 block sums at once:
      S1(BLKOF(I)) := S1(BLKOF(I)) + V(I)*W(I)   (etc.)
    extracted as REDUCTION by the compiler (group partials, ordered host
    combine onto the zeroed per-block accumulators) — per-block norm
    upload, packed normalize. Phase 2 adds the GS overlap product +
    deflate kernel.
  - Convergence: per-block |d rho| < 1e-12 at batch granularity, CONV(B)
    records the batch; batches become no-ops once all 21 blocks converge
    (IF guard on the whole batch body -- host branch, extraction-safe).
  - Emit two variants: N=8 (NP=139776) and N=12 (NP=11.4M).
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
NB = 21
BATCH = 16
NBATCH_DEFAULT = 60
WGSZ = 256  # GPU workgroup size — segment padding unit



def terms(vin, vout, indent, tt):
    return "\n".join(
        f"{indent}A := A + BJ2E(I) * COEF(LOCOF(I),{t}) * "
        f"{vin}(SRC(LOCOF(I),{t}) + I - LOCOF(I))"
        for t in range(1, tt + 1))


def matvec_loop(vin, vout, tt):
    return f"""      DO I = 1, NP
        A := DIAG(LOCOF(I)) * {vin}(I)
{terms(vin, vout, "        ", tt)}
        {vout}(I) := A
      ENDDO"""


def gen(N, shift, nbatch):
    DIM = 3 ** N
    DIMP = ((DIM + WGSZ - 1) // WGSZ) * WGSZ
    NP = NB * DIMP
    TT = 2 * N
    NBATCH = nbatch
    SHIFT = shift
    return f"""! stage4 (N={N}) - GENERATED by gen_ergo_stage4.py (do not edit)
! Packed on-device batch: 21 J-points in one NP = {NP} vector.
! Blocks padded DIM={DIM} -> DIMP={DIMP} (multiple of 256) for the
! segmented reductions; pad elements stay exactly 0.
! Block-diagonal H; per-element lookup tables (runtime-built).
IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: DIM = {DIM}
INTEGER, PARAMETER :: DIMP = {DIMP}
INTEGER, PARAMETER :: NP = {NP}
INTEGER, PARAMETER :: NB = {NB}
INTEGER, PARAMETER :: TT = {TT}
INTEGER, PARAMETER :: NBATCH = {NBATCH}
REAL, PARAMETER :: SHIFT = {SHIFT}

STATIC INTEGER :: SRC(DIMP, TT)
STATIC REAL :: COEF(DIMP, TT)
STATIC REAL :: DIAG(DIMP)
STATIC REAL :: JTAB(NB)
STATIC INTEGER :: LOCOF(NP), BLKOF(NP)
STATIC REAL :: BJ2E(NP)
STATIC REAL :: V(NP), W(NP), GS(NP), V2(NP), W2(NP)
STATIC REAL :: JOUT(NB), E0(NB), E1(NB), RH(NB), RHOLD(NB)
STATIC REAL :: NRT(NB), DV(NB), S1(NB), S2(NB), S3(NB), S4(NB)
STATIC INTEGER :: CONV(NB), CONV2(NB)
STATIC REAL :: A = 0.0

DATA JTAB / 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, &
  1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0 /

REAL :: RHO, NRM, GAPV, DNRM
INTEGER :: I, X, T, Q, D, J, DI, DJ, PI, PJ, B, KB, KP, NCONV, DG({N})

! ============ runtime table build (host, once) ============
DO I = 1, NP
  LOCOF(I) := MOD(I - 1, DIMP) + 1
  BLKOF(I) := (I - 1) / DIMP + 1
ENDDO
DO I = 1, NP
  BJ2E(I) := JTAB(BLKOF(I)) / 2.0
ENDDO
DO X = 1, DIM
  Q := X - 1
  DIAG(X) := 0.0 - SHIFT
  DO I = 1, N
    D := MOD(Q, 3)
    Q := Q / 3
    DIAG(X) := DIAG(X) + REAL((D - 1) * (D - 1)) / 2.0
  ENDDO
ENDDO
DO X = 1, DIM
  DO T = 1, TT
    SRC(X, T) := 1
    COEF(X, T) := 0.0
  ENDDO
ENDDO
DO X = 1, DIM
  Q := X - 1
  DO I = 1, N
    DG(I) := MOD(Q, 3)
    Q := Q / 3
  ENDDO
  T := 1
  DO I = 1, N
    J := I + 1
    IF (J > {N}) THEN
      J := 1
    ENDIF
    DI := DG(I)
    DJ := DG(J)
    PI := 3 ** (I - 1)
    PJ := 3 ** (J - 1)
    IF (DI >= 1) THEN
      IF (DJ <= 1) THEN
        SRC(X, T) := X - PI + PJ
        COEF(X, T) := -1.0
        T := T + 1
      ENDIF
    ENDIF
    IF (DI <= 1) THEN
      IF (DJ >= 1) THEN
        SRC(X, T) := X + PI - PJ
        COEF(X, T) := -1.0
        T := T + 1
      ENDIF
    ENDIF
  ENDDO
ENDDO
! Pad rows [DIM+1, DIMP]: COEF/DIAG stay BSS-zero; SRC must be a valid
! in-block index so matvec neighbor reads stay in bounds (coeff is 0).
DO X = DIM + 1, DIMP
  DO T = 1, TT
    SRC(X, T) := 1
  ENDDO
ENDDO

! ============ cold deterministic seeds (packed) ============
! Same per-(block, local) seeds as the unpadded layout; pads stay 0.
DO B = 1, NB
  DO I = 1, DIM
    V((B-1)*DIMP + I) := MOD(37*((B-1)*DIM + I), 101) / 101.0 - 0.5
    V2((B-1)*DIMP + I) := MOD(53*((B-1)*DIM + I) + 7, 101) / 101.0 - 0.5
  ENDDO
ENDDO
DO B = 1, NB
  CONV(B) := 0
  CONV2(B) := 0
  RH(B) := 0.0
  RHOLD(B) := 0.0
ENDDO
NCONV := 0

! ============ PHASE 1: ground states ============
DO KB = 1, NBATCH
  IF (NCONV < NB) THEN
    DO KP = 1, 8
{matvec_loop("V", "W", TT)}
{matvec_loop("W", "V", TT)}
    ENDDO
{matvec_loop("V", "W", TT)}
    DO B = 1, NB
      S1(B) := 0.0
      S2(B) := 0.0
      S3(B) := 0.0
    ENDDO
    DO I = 1, NP
      S1(BLKOF(I)) := S1(BLKOF(I)) + V(I) * W(I)
    ENDDO
    DO I = 1, NP
      S2(BLKOF(I)) := S2(BLKOF(I)) + W(I) * W(I)
    ENDDO
    DO I = 1, NP
      S3(BLKOF(I)) := S3(BLKOF(I)) + V(I) * V(I)
    ENDDO
    DO B = 1, NB
      RH(B) := S1(B) / S3(B) + SHIFT
      NRT(B) := 1.0 / SQRT(S2(B))
      IF (CONV(B) == 0) THEN
        IF (ABS(RH(B) - RHOLD(B)) < 1E-12) THEN
          CONV(B) := KB
          NCONV := NCONV + 1
        ENDIF
      ENDIF
      RHOLD(B) := RH(B)
    ENDDO
    DO I = 1, NP
      V(I) := W(I) * NRT(BLKOF(I))
    ENDDO
  ENDIF
ENDDO
DO B = 1, NB
  E0(B) := RH(B)
ENDDO
DO I = 1, NP
  GS(I) := V(I)
ENDDO

! ============ PHASE 2: deflated (E1) ============
NCONV := 0
DO B = 1, NB
  RHOLD(B) := 0.0
ENDDO
DO KB = 1, NBATCH
  IF (NCONV < NB) THEN
    DO KP = 1, 8
{matvec_loop("V2", "W2", TT)}
{matvec_loop("W2", "V2", TT)}
    ENDDO
{matvec_loop("V2", "W2", TT)}
    DO B = 1, NB
      S1(B) := 0.0
      S2(B) := 0.0
      S3(B) := 0.0
      S4(B) := 0.0
    ENDDO
    DO I = 1, NP
      S1(BLKOF(I)) := S1(BLKOF(I)) + V2(I) * W2(I)
    ENDDO
    DO I = 1, NP
      S2(BLKOF(I)) := S2(BLKOF(I)) + W2(I) * W2(I)
    ENDDO
    DO I = 1, NP
      S3(BLKOF(I)) := S3(BLKOF(I)) + V2(I) * V2(I)
    ENDDO
    DO I = 1, NP
      S4(BLKOF(I)) := S4(BLKOF(I)) + W2(I) * GS(I)
    ENDDO
    DO B = 1, NB
      DV(B) := S4(B)
      RH(B) := S1(B) / S3(B) + SHIFT
      NRT(B) := 1.0 / SQRT(S2(B))
      IF (CONV2(B) == 0) THEN
        IF (ABS(RH(B) - RHOLD(B)) < 1E-12) THEN
          CONV2(B) := KB
          NCONV := NCONV + 1
        ENDIF
      ENDIF
      RHOLD(B) := RH(B)
    ENDDO
    DO I = 1, NP
      A := W2(I) - DV(BLKOF(I)) * GS(I)
      W2(I) := A
      V2(I) := A * NRT(BLKOF(I))
    ENDDO
  ENDIF
ENDDO
DO B = 1, NB
  E1(B) := RH(B)
ENDDO

! ============ output ============
DO B = 1, NB
  GAPV := E1(B) - E0(B)
  WRITE(*, "%.2f %.10f %.6f %d %d") JTAB(B), E0(B), GAPV, CONV(B), CONV2(B)
ENDDO
"""


for N, fname, shift, nbatch in ((8, "stage4_batch.ergo", 3.0, 60),
                                 (12, "stage4_n12.ergo", 4.0, 150)):
    with open(os.path.join(HERE, fname), "w") as f:
        f.write(gen(N, shift, nbatch))
    print("wrote", fname, "shift", shift, "nbatch", nbatch)
