"""Stage 2 generator: emit stage2_sweep.ergo — a 21-point J-sweep of the
rotor chain (N=8, B=0.25) in Ergo, CPU path, structured for later GPU
extraction.

Structural facts used:
  - At B = 0.25 the onsite first harmonic vanishes exactly, so H is real
    and the arena INDEX maps are parameter-independent.
  - Only the bond coefficient varies: -J/2 per point. The DATA tables are
    therefore a -1/0 MASK (COEF), scaled at runtime by BJ2 := JTAB(p)/2.
  - DIAG carries the shift H~ = H - 3.0*I baked in (parameter-independent).
  - J = 0.0 reduces to the kinetic-only operator: H~ spectrum [-3, +1],
    E0 = 0 dominant (|0-3| = 3 > |Emax-3| = 1), ratio 5/6 -- the Python
    ARPACK pathology point is trivial for power iteration.

GPU STRUCTURE NOTE (also in the .ergo header): the batch loop over
parameter points is the INJECTIVE map intended for later GPU extraction.
The warm-start chain (each point seeds from the previous converged
vectors) is a sequential dependency -- for the GPU stage the points must
be independent, so warm starts must be dropped or restructured
(e.g., fixed seed per point, or two-phase: independent cold starts on
GPU, polish on CPU). Noted here and in the file by design.
"""

import os

N = 8
DIM = 3 ** N
J = 1.0  # mask table uses -1 for real terms; bond coeff = -JTAB(p)/2
SHIFT = 3.0
TT = 2 * N
NPTS = 21

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "stage2_sweep.ergo")

p3 = [3 ** i for i in range(N)]
src = [[1] * TT for _ in range(DIM)]
mask = [[0.0] * TT for _ in range(DIM)]
diag = [0.0] * DIM
for x in range(DIM):
    digits = [(x // p3[i]) % 3 for i in range(N)]
    diag[x] = sum((d - 1) ** 2 for d in digits) / 2.0 - SHIFT
    t = 0
    for i in range(N):
        j = (i + 1) % N
        di, dj = digits[i], digits[j]
        if di >= 1 and dj <= 1:
            src[x][t] = x - p3[i] + p3[j] + 1
            mask[x][t] = -1.0
            t += 1
        if di <= 1 and dj >= 1:
            src[x][t] = x + p3[i] - p3[j] + 1
            mask[x][t] = -1.0
            t += 1


def data_block(name, flat, fmt, per_line=16):
    lines = [f"DATA {name} / &"]
    for k in range(0, len(flat), per_line):
        chunk = ", ".join(fmt(v) for v in flat[k:k + per_line])
        lines.append("  " + chunk + (", &" if k + per_line < len(flat) else " /"))
    return "\n".join(lines)


src_flat = [src[x][t] for t in range(TT) for x in range(DIM)]
mask_flat = [mask[x][t] for t in range(TT) for x in range(DIM)]
jtab = [round(0.1 * k, 10) for k in range(NPTS)]

terms = "\n".join(
    f"    ACC := ACC + BJ2 * COEF(I,{t}) * V(SRC(I,{t}))"
    for t in range(1, TT + 1))
terms2 = "\n".join(
    f"    ACC := ACC + BJ2 * COEF(I,{t}) * V2(SRC(I,{t}))"
    for t in range(1, TT + 1))

ergo = f"""! stage2_sweep.ergo - GENERATED by gen_ergo_stage2.py (do not edit)
! Stage 2: batch J-sweep, rotor chain N=8, B=0.25, CPU path.
! 21 points J = 0.0..2.0 step 0.1; per point: power iteration (ground),
! deflated power iteration (E1), write (J, E0, gap).
!
! GPU STRUCTURE NOTE: the batch loop over parameter points is the
! INJECTIVE map intended for later GPU extraction. The warm-start chain
! (each point seeds from the previous point's converged vectors) is a
! sequential dependency across points -- for the GPU stage the points
! must be independent, so warm starts must be dropped or restructured
! (e.g., fixed deterministic seed per point, or two-phase cold-GPU +
! polish-CPU). This dependency is deliberate on CPU: it cuts iterations
! per point roughly 5-10x.
IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: DIM = {DIM}
INTEGER, PARAMETER :: TT = {TT}
INTEGER, PARAMETER :: MAXIT = 20000
INTEGER, PARAMETER :: NPTS = {NPTS}
REAL, PARAMETER :: SHIFT = {SHIFT}

STATIC INTEGER :: SRC(DIM, TT)
STATIC REAL :: COEF(DIM, TT)
STATIC REAL :: DIAG(DIM)
STATIC REAL :: JTAB(NPTS)
STATIC REAL :: V(DIM), W(DIM), GS(DIM), V2(DIM), W2(DIM)

{data_block("SRC", src_flat, str)}

{data_block("COEF", mask_flat, lambda v: f"{v:.1f}")}

{data_block("DIAG", diag, lambda v: f"{v:.17e}".replace("e", "E"))}

DATA JTAB / {", ".join(f"{v:.1f}" for v in jtab)} /

STATIC REAL :: BJ2 = 0.0

SUBROUTINE MATVEC()
  INTEGER :: I
  REAL :: ACC
  DO I = 1, DIM
    ACC := DIAG(I) * V(I)
{terms}
    W(I) := ACC
  ENDDO
  RETURN
END

SUBROUTINE MATVEC2()
  INTEGER :: I
  REAL :: ACC
  DO I = 1, DIM
    ACC := DIAG(I) * V2(I)
{terms2}
    W2(I) := ACC
  ENDDO
  RETURN
END

REAL :: RHO, RHO_OLD, NRM, E0, E1, GAPV, D
INTEGER :: I, K, P, ITERS1, ITERS2

! deterministic seeds for the FIRST point only (warm starts after)
DO I = 1, DIM
  V(I) := MOD(37*I, 101) / 101.0 - 0.5
  V2(I) := MOD(53*I + 7, 101) / 101.0 - 0.5
ENDDO

DO P = 1, NPTS
  BJ2 := JTAB(P) / 2.0

  ! ---- ground state (warm-started from previous point) ----
  NRM := NORM2(V)
  DO I = 1, DIM
    V(I) := V(I) / NRM
  ENDDO
  RHO_OLD := 0.0
  RHO := 0.0
  K := 1
  ITERS1 := MAXIT
  DO WHILE (K <= MAXIT)
    CALL MATVEC()
    RHO := DOT_PRODUCT(V, W) + SHIFT
    NRM := NORM2(W)
    DO I = 1, DIM
      V(I) := W(I) / NRM
    ENDDO
    IF (ABS(RHO - RHO_OLD) < 1E-12) THEN
      ITERS1 := K
      K := MAXIT + 1
    ENDIF
    RHO_OLD := RHO
    K := K + 1
  ENDDO
  E0 := RHO
  DO I = 1, DIM
    GS(I) := V(I)
  ENDDO

  ! ---- deflated run for E1 (warm-started from previous V2) ----
  NRM := NORM2(V2)
  DO I = 1, DIM
    V2(I) := V2(I) / NRM
  ENDDO
  RHO_OLD := 0.0
  RHO := 0.0
  K := 1
  ITERS2 := MAXIT
  DO WHILE (K <= MAXIT)
    CALL MATVEC2()
    D := DOT_PRODUCT(W2, GS)
    DO I = 1, DIM
      W2(I) := W2(I) - D * GS(I)
    ENDDO
    RHO := DOT_PRODUCT(V2, W2) + SHIFT
    NRM := NORM2(W2)
    DO I = 1, DIM
      V2(I) := W2(I) / NRM
    ENDDO
    IF (ABS(RHO - RHO_OLD) < 1E-12) THEN
      ITERS2 := K
      K := MAXIT + 1
    ENDIF
    RHO_OLD := RHO
    K := K + 1
  ENDDO
  E1 := RHO
  GAPV := E1 - E0

  WRITE(*, "%.2f %.10f %.6f %d %d") JTAB(P), E0, GAPV, ITERS1, ITERS2

  ! restore ground vector into V for the next point's warm start
  DO I = 1, DIM
    V(I) := GS(I)
  ENDDO
ENDDO
"""

with open(OUT, "w") as f:
    f.write(ergo)
print("wrote", OUT, "%.1f MB" % (len(ergo) / 1e6))
