"""Stage 0-1 generator: emit stage0_power.ergo — a power-iteration
eigensolver for the rotor chain at N=8, B=0.25, J=1.0.

Gauge/physics note: at B = 0.25 the first harmonic V = K_PHASE - B*K_BIAS
vanishes identically, so the Hamiltonian is REAL in the original gauge
(kinetic diagonal + real bond coefficients -J/2). The generator asserts
this and emits only the real terms; complex split (two real matvecs) is
deferred to later stages.

Tables (V22 pattern — everything precomputed, DATA statements,
column-major fill order):
  SRC(DIM, TT)  int32 source index per (state, term), sentinel 1
  COEF(DIM, TT) real coefficient per (state, term), sentinel 0.0
  DIAG(DIM)     kinetic diagonal with the shift H~ = H - 3.0*I baked in
TT = 2N = 16 (bonds only; onsite terms vanish at this oracle point).

Output: engine/stage0_power.ergo
"""

import os

N = 8
DIM = 3 ** N
B, J = 0.25, 1.0
K_PHASE, K_BIAS = 0.5, 2.0
SHIFT = 3.0
TT = 2 * N

V = K_PHASE - B * K_BIAS
assert abs(V) < 1e-15, "generator currently assumes the real V=0 point"

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "stage0_power.ergo")

p3 = [3 ** i for i in range(N)]

# term tables (0-based python, emitted 1-based)
src = [[1] * TT for _ in range(DIM)]
coef = [[0.0] * TT for _ in range(DIM)]
diag = [0.0] * DIM
for x in range(DIM):
    digits = [(x // p3[i]) % 3 for i in range(N)]
    diag[x] = sum((d - 1) ** 2 for d in digits) / 2.0 - SHIFT  # m = d-1
    t = 0
    for i in range(N):
        j = (i + 1) % N
        di, dj = digits[i], digits[j]
        if di >= 1 and dj <= 1:
            src[x][t] = x - p3[i] + p3[j] + 1
            coef[x][t] = -J / 2.0
            t += 1
        if di <= 1 and dj >= 1:
            src[x][t] = x + p3[i] - p3[j] + 1
            coef[x][t] = -J / 2.0
            t += 1


def data_block(name, flat, fmt, per_line=16):
    """DATA name / v, v, ... / with & continuations (col-major order —
    `flat` must already be in column-major sequence)."""
    lines = [f"DATA {name} / &"]
    for k in range(0, len(flat), per_line):
        chunk = ", ".join(fmt(v) for v in flat[k:k + per_line])
        if k + per_line < len(flat):
            lines.append("  " + chunk + ", &")
        else:
            lines.append("  " + chunk + " /")
    return "\n".join(lines)


# column-major flatten: element (x, t) at sequence x + DIM*(t-1)
src_flat = [src[x][t] for t in range(TT) for x in range(DIM)]
coef_flat = [coef[x][t] for t in range(TT) for x in range(DIM)]

terms = "\n".join(
    f"    ACC := ACC + COEF(I,{t}) * V(SRC(I,{t}))" for t in range(1, TT + 1))

ergo = f"""! stage0_power.ergo - GENERATED by gen_ergo_stage0.py (do not edit)
! Rotor chain eigensolver, Stage 0-1 (power iteration + deflation).
! Oracle: N=8, B=0.25, J=1.0 -> E0 = -2.8591343125, gap = 0.120548.
! Shift H~ = H - 3.0*I baked into DIAG: ground state is the dominant
! eigenvalue of H~ (|E0-3| = 5.86 > |Emax-3| ~ 4); ratio |E1-3|/|E0-3|
! ~ 0.98, hence the generous MAXIT.
IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: DIM = {DIM}
INTEGER, PARAMETER :: TT = {TT}
INTEGER, PARAMETER :: MAXIT = 20000
REAL, PARAMETER :: SHIFT = {SHIFT}

STATIC INTEGER :: SRC(DIM, TT)
STATIC REAL :: COEF(DIM, TT)
STATIC REAL :: DIAG(DIM)
STATIC REAL :: V(DIM), W(DIM), GS(DIM)

{data_block("SRC", src_flat, lambda v: str(v))}

{data_block("COEF", coef_flat, lambda v: f"{v:.17e}".replace("e", "E"))}

{data_block("DIAG", diag, lambda v: f"{v:.17e}".replace("e", "E"))}

SUBROUTINE MATVEC()
  INTEGER :: I
  REAL :: ACC
  DO I = 1, DIM
    ACC := DIAG(I) * V(I)
{terms}
    W(I) := ACC
  ENDDO
  RETURN
END

REAL :: RHO, RHO_OLD, NRM, E0, E1, GAPV, D
INTEGER :: I, K, ITERS1, ITERS2

! deterministic seed (MOD pseudo-random, min-sim style)
DO I = 1, DIM
  V(I) := MOD(37*I, 101) / 101.0 - 0.5
ENDDO
NRM := NORM2(V)
DO I = 1, DIM
  V(I) := V(I) / NRM
ENDDO

! ---- power iteration for the ground state ----
RHO_OLD := 0.0
RHO := 0.0
K := 1
ITERS1 := MAXIT
DO WHILE (K <= MAXIT)
  CALL MATVEC()
  RHO := DOT_PRODUCT(V, W) + SHIFT
  NRM := NORM2(W)
  DO I = 1, DIM
    V(I) := W(I) / NRM
  ENDDO
  IF (ABS(RHO - RHO_OLD) < 1E-12) THEN
    ITERS1 := K
    K := MAXIT + 1
  ENDIF
  RHO_OLD := RHO
  K := K + 1
ENDDO
E0 := RHO

! ---- deflate: second power run orthogonal to the ground state ----
DO I = 1, DIM
  GS(I) := V(I)
ENDDO
DO I = 1, DIM
  V(I) := MOD(53*I + 7, 101) / 101.0 - 0.5
ENDDO
NRM := NORM2(V)
DO I = 1, DIM
  V(I) := V(I) / NRM
ENDDO
RHO_OLD := 0.0
RHO := 0.0
K := 1
ITERS2 := MAXIT
DO WHILE (K <= MAXIT)
  CALL MATVEC()
  D := DOT_PRODUCT(W, GS)
  DO I = 1, DIM
    W(I) := W(I) - D * GS(I)
  ENDDO
  RHO := DOT_PRODUCT(V, W) + SHIFT
  NRM := NORM2(W)
  DO I = 1, DIM
    V(I) := W(I) / NRM
  ENDDO
  IF (ABS(RHO - RHO_OLD) < 1E-12) THEN
    ITERS2 := K
    K := MAXIT + 1
  ENDIF
  RHO_OLD := RHO
  K := K + 1
ENDDO
E1 := RHO
GAPV := E1 - E0

WRITE(*, "E0 = %.10f") E0
WRITE(*, "E1 = %.10f") E1
WRITE(*, "GAP = %.6f") GAPV
WRITE(*, "ITERS = %d %d") ITERS1, ITERS2
"""

with open(OUT, "w") as f:
    f.write(ergo)
print("wrote", OUT, "%.1f MB" % (len(ergo) / 1e6))
