"""Stage B (v2) generator: cyclic-parallel Jacobi entanglement in Ergo.

Emits stageB_jacobi.ergo with:
  Section 0 — standalone eigensolver validation:
    (a) 5x5 known-eigenvalue matrix (diag {1..5} + orthogonal similarity,
        matrix emitted as DATA from Python; expected eigenvalues printed)
    (b) 81x81 random Gram (emitted as DATA; eigenvalues written out for
        numpy cross-check to 1e-8 relative)
  Section 1 — production: ground states at (B=0.25,J=1.0) and (B=0.1,J=2.0)
    (Stage A complex machinery), cuts l=1..6: Gram built on the fly from
    the ground vector (no A copy), cyclic round-robin Jacobi with inline
    schedule (MOD-based participants, no tables), eigenvalue-only mode,
    S = -sum p ln p, CC fit per point over the 6 cuts.

Jacobi round (size M even): participants a(0)=0, a(s)=MOD(s-1+r, M-1)+1
for s >= 1; pairs k = 0..M/2-1: (a(k), a(M-1-k)). For odd M use M+1 and
skip pairs touching the dummy. Termination: off(A) < 1e-10*sqrt(M),
max 12 sweeps. Rotation: stable tan form (tau/t/c/s).
"""

import json
import os

N = 12
DIM = 3 ** N
TT = 6 * N
NB = 2 * N
SHIFT = 4.0
HERE = os.path.dirname(os.path.abspath(__file__))

mats = json.load(open("/tmp/test_mats.json"))

src = open(os.path.join(HERE, "stageA_complex.ergo")).read()
tbl_start = src.index("! ============ table build")
tbl_end = src.index("! ============ per-point loop")
TABLE_BUILD = src[tbl_start:tbl_end]


def data_block(name, flat, fmt, per_line=8):
    lines = [f"DATA {name} / &"]
    for k in range(0, len(flat), per_line):
        chunk = ", ".join(fmt(v) for v in flat[k:k + per_line])
        lines.append("  " + chunk + (", &" if k + per_line < len(flat) else " /"))
    return "\n".join(lines)


m5flat = [mats["M5"][i][j] for j in range(5) for i in range(5)]  # column-major
g81flat = [mats["G81"][i][j] for j in range(81) for i in range(81)]

ergo = f"""! stageB_jacobi.ergo - GENERATED by gen_ergo_stageB_jacobi.py (do not edit)
! Cyclic round-robin Jacobi (Fawzi & Goulbourne techniques: cyclic
! elimination, parallel rounds, off(A) termination, eigenvalue-only).
IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: DIM = {DIM}
INTEGER, PARAMETER :: TT = {TT}
INTEGER, PARAMETER :: NB = {NB}
INTEGER, PARAMETER :: MAXIT = 20000
REAL, PARAMETER :: SHIFT = {SHIFT}

STATIC INTEGER :: SRC(DIM, TT)
STATIC REAL :: CFAC(TT), SFAC(TT)
STATIC REAL :: DIAG(DIM)
STATIC REAL :: VR(DIM + 1), VI(DIM + 1), WR(DIM + 1), WI(DIM + 1)
STATIC REAL :: YR(DIM + 1), YI(DIM + 1), ZR(DIM + 1), ZI(DIM + 1)
STATIC REAL :: G(729, 729)
STATIC REAL :: SS(6)
STATIC REAL :: BJ2 = 0.0
STATIC REAL :: VV = 0.0
STATIC REAL :: M5(5, 5), EV5(5), G81(81, 81), EV81(81)

STATIC REAL :: OFFA = 0.0, TAU = 0.0, A0 = 0.0, A1 = 0.0
REAL :: RHO, RHO_OLD, NRM, E0, CR, CI
REAL :: CSUM, SCALE, C, SN, APP, AQQ, APQ, TH
INTEGER :: I, X, T, Q, D, J, DI, DJ, PI, PJ, B, KB, K, NCONV, DG({N})
INTEGER :: R, L, RL, CL, R0, C0, P0, Q0, SWEEP, M, MP, S2, K2

{data_block("M5", m5flat, lambda v: f"{v:.17e}".replace("e", "E"))}

{data_block("G81", g81flat, lambda v: f"{v:.17e}".replace("e", "E"))}

! ============ table build ============
{TABLE_BUILD}
VR(DIM + 1) := 0.0
VI(DIM + 1) := 0.0

! ================================================================
! SECTION 0: standalone eigensolver validation
! ================================================================

! --- (a) 5x5 known eigenvalues ---
WRITE(*, "TEST-A 5x5 known spectrum")
M := 5
CALL JACOBI5()
DO I = 1, 5
  WRITE(*, "EV5 %d %.10f") I, M5(I, I)
ENDDO

! --- (b) 81x81 random Gram ---
WRITE(*, "TEST-B 81x81 random Gram")
M := 81
CALL JACOBI81()
DO I = 1, 81
  WRITE(*, "EV81 %d %.10f") I, G81(I, I)
ENDDO

! ================================================================
! SECTION 1: production points
! ================================================================
DO KB = 1, 2
  IF (KB == 1) THEN
    BJ2 := 0.5
    VV := 0.0
  ELSE
    BJ2 := 1.0
    VV := 0.3
  ENDIF
  DO T = 1, TT
    CFAC(T) := 0.0
    SFAC(T) := 0.0
  ENDDO
  DO I = 1, N
    CFAC(2 * {N} + 2 * I - 1) := 0.0 - VV * COS(6.283185307179586 * REAL(I - 1) / REAL({N})) / 2.0
    CFAC(2 * {N} + 2 * I) := CFAC(2 * {N} + 2 * I - 1)
    SFAC(4 * {N} + 2 * I - 1) := VV * SIN(6.283185307179586 * REAL(I - 1) / REAL({N})) / 2.0
    SFAC(4 * {N} + 2 * I) := 0.0 - SFAC(4 * {N} + 2 * I - 1)
  ENDDO

  ! ---- ground state (Stage A complex power iteration) ----
  DO I = 1, DIM
    VR(I) := MOD(37*I, 101) / 101.0 - 0.5
    VI(I) := MOD(53*I + 7, 101) / 101.0 - 0.5
  ENDDO
  NRM := SQRT(DOT_PRODUCT(VR, VR) + DOT_PRODUCT(VI, VI))
  DO I = 1, DIM
    VR(I) := VR(I) / NRM
    VI(I) := VI(I) / NRM
  ENDDO
  RHO_OLD := 0.0
  RHO := 0.0
  K := 1
  DO WHILE (K <= MAXIT)
    DO I = 1, DIM
      A0 := DIAG(I) * VR(I)
      A1 := DIAG(I) * VI(I)
      DO T = 1, NB
        A0 := A0 - BJ2 * VR(SRC(I,T))
        A1 := A1 - BJ2 * VI(SRC(I,T))
      ENDDO
      DO T = NB + 1, 2 * NB
        A0 := A0 + CFAC(T) * VR(SRC(I,T))
        A1 := A1 + CFAC(T) * VI(SRC(I,T))
      ENDDO
      YR(I) := A0
      YI(I) := A1
    ENDDO
    DO I = 1, DIM
      A0 := 0.0
      A1 := 0.0
      DO T = 2 * NB + 1, TT
        A0 := A0 + SFAC(T) * VR(SRC(I,T))
        A1 := A1 + SFAC(T) * VI(SRC(I,T))
      ENDDO
      ZR(I) := A0
      ZI(I) := A1
    ENDDO
    DO I = 1, DIM
      WR(I) := YR(I) - ZI(I)
      WI(I) := YI(I) + ZR(I)
    ENDDO
    RHO := DOT_PRODUCT(VR, WR) + DOT_PRODUCT(VI, WI) + SHIFT
    NRM := SQRT(DOT_PRODUCT(WR, WR) + DOT_PRODUCT(WI, WI))
    DO I = 1, DIM
      VR(I) := WR(I) / NRM
      VI(I) := WI(I) / NRM
    ENDDO
    IF (ABS(RHO - RHO_OLD) < 1E-12) THEN
      K := MAXIT + 1
    ENDIF
    RHO_OLD := RHO
    K := K + 1
  ENDDO
  E0 := RHO
  WRITE(*, "PT %d E0 %.10f K %d") KB, E0, K

  ! ---- cuts l = 1..6 ----
  DO L = 1, 6
    RL := 3 ** L
    CL := 3 ** ({N} - L)
    ! Gram on the fly: G(r,q) = sum_c V(r+(c-1)*RL) . V(q+(c-1)*RL)
    DO R0 = 1, RL
      DO Q0 = R0, RL
        A0 := 0.0
        DO C0 = 1, CL
          A0 := A0 + VR(R0 + (C0 - 1) * RL) * VR(Q0 + (C0 - 1) * RL) &
                  + VI(R0 + (C0 - 1) * RL) * VI(Q0 + (C0 - 1) * RL)
        ENDDO
        G(R0, Q0) := A0
        G(Q0, R0) := A0
      ENDDO
    ENDDO
    ! cyclic round-robin Jacobi (inline schedule, eigenvalue-only)
    M := RL
    IF (MOD(M, 2) == 0) THEN
      MP := M
    ELSE
      MP := M + 1
    ENDIF
    OFFA := 1.0
    SWEEP := 0
    DO WHILE (SWEEP < 12)
      IF (OFFA < 1E-10 * SQRT(REAL(M))) THEN
        SWEEP := 100
      ELSE
        DO R = 0, MP - 2
          DO K2 = 0, MP / 2 - 1
            IF (K2 == 0) THEN
              P0 := 1
            ELSE
              P0 := MOD(K2 - 1 + R, MP - 1) + 2
            ENDIF
            S2 := MP - 1 - K2
            IF (S2 == 0) THEN
              Q0 := 1
            ELSE
              Q0 := MOD(S2 - 1 + R, MP - 1) + 2
            ENDIF
            ! skip dummy pair for odd M (dummy index = M+1)
            IF (P0 <= M) THEN
              IF (Q0 <= M) THEN
                APQ := G(P0, Q0)
                IF (ABS(APQ) > 1E-16) THEN
                  APP := G(P0, P0)
                  AQQ := G(Q0, Q0)
                  TAU := (AQQ - APP) / (2.0 * APQ)
                  IF (TAU >= 0.0) THEN
                    TH := 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
                  ELSE
                    TH := 0.0 - 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
                  ENDIF
                  C := 1.0 / SQRT(1.0 + TH * TH)
                  SN := TH * C
                  DO C0 = 1, M
                    A0 := G(C0, P0)
                    A1 := G(C0, Q0)
                    G(C0, P0) := C * A0 - SN * A1
                    G(C0, Q0) := SN * A0 + C * A1
                  ENDDO
                  DO C0 = 1, M
                    A0 := G(P0, C0)
                    A1 := G(Q0, C0)
                    G(P0, C0) := C * A0 - SN * A1
                    G(Q0, C0) := SN * A0 + C * A1
                  ENDDO
                ENDIF
              ENDIF
            ENDIF
          ENDDO
        ENDDO
        OFFA := 0.0
        DO P0 = 1, M
          DO Q0 = P0 + 1, M
            OFFA := OFFA + G(P0, Q0) * G(P0, Q0)
          ENDDO
        ENDDO
        OFFA := SQRT(2.0 * OFFA)
        SWEEP := SWEEP + 1
      ENDIF
    ENDDO
    IF (SWEEP >= 100) THEN
      SWEEP := SWEEP - 100
    ENDIF
    SS(L) := 0.0
    DO R0 = 1, M
      IF (G(R0, R0) > 1E-15) THEN
        SS(L) := SS(L) - G(R0, R0) * LOG(G(R0, R0))
      ENDIF
    ENDDO
    WRITE(*, "PT %d L %d S %.6f SWEEP %d") KB, L, SS(L), SWEEP
  ENDDO

  ! ---- CC fit over l = 1..6 ----
  CR := 0.0
  CI := 0.0
  A0 := 0.0
  A1 := 0.0
  DO L = 1, 6
    SCALE := LOG((REAL({N}) / 3.14159265358979) * SIN(3.14159265358979 * REAL(L) / REAL({N})))
    CR := CR + SCALE * SCALE
    CI := CI + SCALE * SS(L)
    A0 := A0 + SCALE
    A1 := A1 + SS(L)
  ENDDO
  A0 := A0 / 6.0
  A1 := A1 / 6.0
  CSUM := (CI - 6.0 * A0 * A1) / (CR - 6.0 * A0 * A0)
  WRITE(*, "PT %d CC %.4f") KB, 3.0 * CSUM
ENDDO

WRITE(*, "# DONE")
STOP

! ============ JACOBI5: cyclic Jacobi on the 5x5 test matrix ============
SUBROUTINE JACOBI5()
  INTEGER :: MM, RR, KK, SS2, PP, QQ, SW, C0
  REAL :: AA, BB, CC2, TT2, CC, SS2R
  MM := 6
  OFFA := 1.0
  SW := 0
  DO WHILE (SW < 12)
    IF (OFFA < 1E-10 * SQRT(5.0)) THEN
      SW := 100
    ELSE
      DO RR = 0, MM - 2
        DO KK = 0, MM / 2 - 1
          IF (KK == 0) THEN
            PP := 1
          ELSE
            PP := MOD(KK - 1 + RR, MM - 1) + 2
          ENDIF
          SS2 := MM - 1 - KK
          IF (SS2 == 0) THEN
            QQ := 1
          ELSE
            QQ := MOD(SS2 - 1 + RR, MM - 1) + 2
          ENDIF
          IF (PP <= 5) THEN
            IF (QQ <= 5) THEN
              AA := M5(PP, QQ)
              IF (ABS(AA) > 1E-16) THEN
                TAU := (M5(QQ, QQ) - M5(PP, PP)) / (2.0 * AA)
                IF (TAU >= 0.0) THEN
                  TT2 := 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
                ELSE
                  TT2 := 0.0 - 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
                ENDIF
                CC := 1.0 / SQRT(1.0 + TT2 * TT2)
                SS2R := TT2 * CC
                DO C0 = 1, 5
                  A0 := M5(C0, PP)
                  A1 := M5(C0, QQ)
                  M5(C0, PP) := CC * A0 - SS2R * A1
                  M5(C0, QQ) := SS2R * A0 + CC * A1
                ENDDO
                DO C0 = 1, 5
                  A0 := M5(PP, C0)
                  A1 := M5(QQ, C0)
                  M5(PP, C0) := CC * A0 - SS2R * A1
                  M5(QQ, C0) := SS2R * A0 + CC * A1
                ENDDO
              ENDIF
            ENDIF
          ENDIF
        ENDDO
      ENDDO
      OFFA := 0.0
      DO PP = 1, 5
        DO QQ = PP + 1, 5
          OFFA := OFFA + M5(PP, QQ) * M5(PP, QQ)
        ENDDO
      ENDDO
      OFFA := SQRT(2.0 * OFFA)
      SW := SW + 1
    ENDIF
  ENDDO
  RETURN
END

! ============ JACOBI81: cyclic Jacobi on the 81x81 test Gram ============
SUBROUTINE JACOBI81()
  INTEGER :: MM, RR, KK, SS2, PP, QQ, SW, C0
  REAL :: AA, BB, CC2, TT2, CC, SS2R
  MM := 82
  OFFA := 1.0
  SW := 0
  DO WHILE (SW < 12)
    IF (OFFA < 1E-10 * SQRT(81.0)) THEN
      SW := 100
    ELSE
      DO RR = 0, MM - 2
        DO KK = 0, MM / 2 - 1
          IF (KK == 0) THEN
            PP := 1
          ELSE
            PP := MOD(KK - 1 + RR, MM - 1) + 2
          ENDIF
          SS2 := MM - 1 - KK
          IF (SS2 == 0) THEN
            QQ := 1
          ELSE
            QQ := MOD(SS2 - 1 + RR, MM - 1) + 2
          ENDIF
          IF (PP <= 81) THEN
            IF (QQ <= 81) THEN
              AA := G81(PP, QQ)
              IF (ABS(AA) > 1E-16) THEN
                TAU := (G81(QQ, QQ) - G81(PP, PP)) / (2.0 * AA)
                IF (TAU >= 0.0) THEN
                  TT2 := 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
                ELSE
                  TT2 := 0.0 - 1.0 / (ABS(TAU) + SQRT(1.0 + TAU * TAU))
                ENDIF
                CC := 1.0 / SQRT(1.0 + TT2 * TT2)
                SS2R := TT2 * CC
                DO C0 = 1, 81
                  A0 := G81(C0, PP)
                  A1 := G81(C0, QQ)
                  G81(C0, PP) := CC * A0 - SS2R * A1
                  G81(C0, QQ) := SS2R * A0 + CC * A1
                ENDDO
                DO C0 = 1, 81
                  A0 := G81(PP, C0)
                  A1 := G81(QQ, C0)
                  G81(PP, C0) := CC * A0 - SS2R * A1
                  G81(QQ, C0) := SS2R * A0 + CC * A1
                ENDDO
              ENDIF
            ENDIF
          ENDIF
        ENDDO
      ENDDO
      OFFA := 0.0
      DO PP = 1, 81
        DO QQ = PP + 1, 81
          OFFA := OFFA + G81(PP, QQ) * G81(PP, QQ)
        ENDDO
      ENDDO
      OFFA := SQRT(2.0 * OFFA)
      SW := SW + 1
    ENDIF
  ENDDO
  RETURN
END
"""

with open(os.path.join(HERE, "stageB_jacobi.ergo"), "w") as f:
    f.write(ergo)
print("wrote stageB_jacobi.ergo")
