#!/usr/bin/env python3
"""gen_tuning_relax.py — emit allocator/tuning_relax.ergo (Level 2 geodesy).

The emitted Ergo program:
  1. Builds the 8-bin x 32-ring torus graph. Edge weights from the
     allocator's own constants (documented metric, sensitivity-checked
     in tuning_check.py):
       ring step (b,r)<->(b,r+1 mod 32):
         WR(r) = 1 + (|FLOWW[r]| + |FLOWW[r+1]) / 2   (flow inertia)
       bin step  (b,r)<->(b+-1 mod 8, r):
         WB = SCLRAT = 27/16                           (shell scale)
  2. All-pairs geodesic distances DD(256,256) via 256 Dijkstras
     (the Dijkstra-in-Ergo pattern from min/hopfion).
  3. Bakes the design visitation walk: ID i=1..32 visits
     (SCATLT[i], per-bin visit ordinal). Action = collision energy
       E = sum_i 1 / (1 + DD(node_i, node_{i+1}))
     (nearby consecutive visits are expensive; a well-spread sequence
     minimizes E). Also reports raw distance sum DSUM.
  4. Local-relax checker: single-swap descent (preserves the bin
     multiset) from the design walk. If the design is a 1-swap local
     optimum, ERELAXED == EDESIGN (deficit 0 at swap level).
  5. Prints DD for tuning_check.py's perturbation statistics.

Determinism: fixed baked data, strict-decrease acceptance, no RNG.
"""
import numpy as np

FLOWW = [0.000000, 0.263371, 0.231222, 0.227317,
         0.340459, 0.163085, -0.216041, -0.319410,
         -0.259259, -0.319410, -0.216041, 0.163086,
         0.340459, 0.227318, 0.231222, 0.263371,
         -0.000000, -0.263371, -0.231222, -0.227317,
         -0.340459, -0.163085, 0.216041, 0.319410,
         0.259259, 0.319410, 0.216041, -0.163086,
         -0.340459, -0.227317, -0.231222, -0.263371]
SCATLT = [6, 4, 6, 2, 7, 4, 3, 0, 2, 0, 3, 4, 7, 2, 6, 4] * 2


def emit():
    L = []
    L.append("! tuning_relax.ergo — GENERATED by gen_tuning_relax.py "
             "(do not edit)")
    L.append("! Level 2 geodesy: SCATLT visitation walk on the 8x32 torus.")
    L.append("! Metric: ring step WR(r)=1+(|FLOWW[r]|+|FLOWW[r+1]|)/2, "
             "bin step WB=SCLRAT=27/16.")
    L.append("! Action E = sum 1/(1+DD(n_i,n_i+1)) (collision energy; "
             "spread sequences minimize).")
    L.append("IMPLICIT NONE")
    L.append("INTEGER, PARAMETER :: NB = 8, NR = 32, NP = 256, NW = 32")
    L.append("INTEGER, PARAMETER :: NSWEEP = 200")
    L.append("REAL, PARAMETER :: WB = 1.6875")
    L.append("STATIC REAL :: FLOWW(NR), WR(NR), DIST(NP), DD(NP, NP)")
    L.append("STATIC INTEGER :: SCAT(NW), SEQ(NW), NODE(NW), CNT(NB)")
    L.append("STATIC INTEGER :: PREV(NP), VIS(NP)")
    # DATA statements
    fw = ", ".join(f"{v:.6f}" for v in FLOWW)
    L.append(f"DATA FLOWW / {fw} /")
    sc = ", ".join(str(v) for v in SCATLT)
    L.append(f"DATA SCAT / {sc} /")
    L.append("REAL :: C1, DB, EB, E2, DSUM")
    L.append("INTEGER :: I, J, K, S, T, U, V, CHANGED, B, R, RP, RM")
    L.append("INTEGER :: BP, BM, N1, N2, TMP, CONV")
    L.append("")
    # ring weights
    L.append("DO I = 1, NR")
    L.append("  RP := MOD(I, NR) + 1")   # r+1 (1-based)
    L.append("  WR(I) := 1.0 + 0.5 * (ABS(FLOWW(I)) + ABS(FLOWW(RP)))")
    L.append("ENDDO")
    L.append("")
    # ---- all-pairs Dijkstra ----
    L.append("DO S = 1, NP")
    L.append("  DO I = 1, NP")
    L.append("    DIST(I) := 1.0e30")
    L.append("    VIS(I) := 0")
    L.append("  ENDDO")
    L.append("  DIST(S) := 0.0")
    L.append("  DO T = 1, NP")
    L.append("    U := 0")
    L.append("    DB := 1.0e29")
    L.append("    DO I = 1, NP")
    L.append("      IF (VIS(I) == 0) THEN")
    L.append("        IF (DIST(I) < DB) THEN")
    L.append("          DB := DIST(I)")
    L.append("          U := I")
    L.append("        ENDIF")
    L.append("      ENDIF")
    L.append("    ENDDO")
    L.append("    IF (U > 0) THEN")
    L.append("      VIS(U) := 1")
    L.append("      B := (U - 1) / NR")          # 0-based bin
    L.append("      R := MOD(U - 1, NR)")        # 0-based ring
    L.append("      RP := MOD(R + 1, NR)")
    L.append("      RM := MOD(R + NR - 1, NR)")
    L.append("      BP := MOD(B + 1, NB)")
    L.append("      BM := MOD(B + NB - 1, NB)")
    # ring+ : edge r->r+1 weight WR(r+1 1based = R+1)
    L.append("      V := B * NR + RP + 1")
    L.append("      C1 := DIST(U) + WR(R + 1)")
    L.append("      IF (C1 < DIST(V)) THEN")
    L.append("        DIST(V) := C1")
    L.append("      ENDIF")
    # ring- : edge r-1->r weight WR(r 1based = RM+1)
    L.append("      V := B * NR + RM + 1")
    L.append("      C1 := DIST(U) + WR(RM + 1)")
    L.append("      IF (C1 < DIST(V)) THEN")
    L.append("        DIST(V) := C1")
    L.append("      ENDIF")
    # bin+-
    L.append("      V := BP * NR + R + 1")
    L.append("      C1 := DIST(U) + WB")
    L.append("      IF (C1 < DIST(V)) THEN")
    L.append("        DIST(V) := C1")
    L.append("      ENDIF")
    L.append("      V := BM * NR + R + 1")
    L.append("      C1 := DIST(U) + WB")
    L.append("      IF (C1 < DIST(V)) THEN")
    L.append("        DIST(V) := C1")
    L.append("      ENDIF")
    L.append("    ENDIF")
    L.append("  ENDDO")
    L.append("  DO I = 1, NP")
    L.append("    DD(S, I) := DIST(I)")
    L.append("  ENDDO")
    L.append("ENDDO")
    L.append('WRITE(*, "dd done")')
    # dump DD
    L.append("DO I = 1, NP")
    L.append("  DO J = 1, NP")
    L.append('    WRITE(*, "DD %d %d %.12e") I, J, DD(I, J)')
    L.append("  ENDDO")
    L.append("ENDDO")
    L.append("")
    # ---- design walk nodes + action (subroutine inlined twice: design) ----
    # init SEQ from SCAT
    L.append("DO I = 1, NW")
    L.append("  SEQ(I) := SCAT(I)")
    L.append("ENDDO")
    # node assignment + action as inline block (design)
    L += _action_block("EB", "DSUM")
    L.append('WRITE(*, "EDESIGN %.12e") EB')
    L.append('WRITE(*, "DSUM %.12e") DSUM')
    L.append("")
    # ---- swap descent ----
    L.append("CONV := 0")
    L.append("DO T = 1, NSWEEP")
    L.append("  CHANGED := 0")
    L.append("  DO I = 1, NW - 1")
    L.append("    DO J = I + 1, NW")
    L.append("      TMP := SEQ(I)")
    L.append("      SEQ(I) := SEQ(J)")
    L.append("      SEQ(J) := TMP")
    L += _action_block("E2", None, indent="      ")
    L.append("      IF (E2 < EB - 1.0e-12) THEN")
    L.append("        EB := E2")
    L.append("        CHANGED := 1")
    L.append("      ELSE")
    L.append("        TMP := SEQ(I)")
    L.append("        SEQ(I) := SEQ(J)")
    L.append("        SEQ(J) := TMP")
    L.append("      ENDIF")
    L.append("    ENDDO")
    L.append("  ENDDO")
    L.append("  IF (CHANGED == 0) THEN")
    L.append("    CONV := T")
    L.append("    T := NSWEEP")
    L.append("  ENDIF")
    L.append("ENDDO")
    L.append('WRITE(*, "converged at sweep %d") CONV')
    L.append('WRITE(*, "ERELAXED %.12e") EB')
    L.append("DO I = 1, NW")
    L.append('  WRITE(*, "RSEQ %d %d") I, SEQ(I)')
    L.append("ENDDO")
    return "\n".join(L) + "\n"


def _action_block(ename, dname, indent=""):
    """Assign NODE() from SEQ() (per-bin ordinals) and compute action."""
    L = []
    L.append(f"{indent}DO K = 1, NB")
    L.append(f"{indent}  CNT(K) := 0")
    L.append(f"{indent}ENDDO")
    L.append(f"{indent}DO K = 1, NW")
    L.append(f"{indent}  B := SEQ(K) + 1")
    L.append(f"{indent}  R := CNT(B)")
    L.append(f"{indent}  CNT(B) := R + 1")
    L.append(f"{indent}  NODE(K) := (B - 1) * NR + R + 1")
    L.append(f"{indent}ENDDO")
    L.append(f"{indent}{ename} := 0.0")
    if dname:
        L.append(f"{indent}{dname} := 0.0")
    L.append(f"{indent}DO K = 1, NW - 1")
    L.append(f"{indent}  N1 := NODE(K)")
    L.append(f"{indent}  N2 := NODE(K + 1)")
    L.append(f"{indent}  {ename} := {ename} + 1.0 / (1.0 + DD(N1, N2))")
    if dname:
        L.append(f"{indent}  {dname} := {dname} + DD(N1, N2)")
    L.append(f"{indent}ENDDO")
    return L


def main():
    out = emit()
    path = "allocator/tuning_relax.ergo"
    with open(path, "w") as f:
        f.write(out)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
