#!/bin/bash
# build_shaders.sh — Compile GLSL shaders to SPIR-V and embed in render_shaders.h
#
# Run from mcl/runtime/ after editing any .vert or .frag file.
# Requires: glslc (from the Vulkan SDK or shaderc package)
#
# Usage: ./build_shaders.sh

set -euo pipefail
cd "$(dirname "$0")"

echo "Compiling shaders..."
glslc -fshader-stage=vertex   render.vert        -o render.vert.spv
glslc -fshader-stage=fragment render.frag        -o render.frag.spv
glslc -fshader-stage=vertex   render_points.vert -o render_points.vert.spv
glslc -fshader-stage=fragment render_points.frag -o render_points.frag.spv
glslc -fshader-stage=vertex   render_gauss.vert  -o render_gauss.vert.spv
glslc -fshader-stage=fragment render_gauss.frag  -o render_gauss.frag.spv

echo "Generating render_shaders.h..."
python3 -c "
def emit_array(name, filepath):
    with open(filepath, 'rb') as f:
        data = f.read()
    lines = []
    lines.append(f'static const unsigned char {name}[] = {{')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_bytes = ','.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'    {hex_bytes},')
    lines.append('};')
    lines.append(f'static const size_t {name}_size = sizeof({name});')
    return '\n'.join(lines)

header = '''/*
 * render_shaders.h — Embedded SPIR-V for render pass shaders.
 * Auto-generated by build_shaders.sh. Do not edit by hand.
 */
#ifndef ERGO_RENDER_SHADERS_H
#define ERGO_RENDER_SHADERS_H
#include <stddef.h>

/* ── Grid mesh shaders ── */

'''
header += emit_array('render_vert_spv', 'render.vert.spv')
header += '\n\n'
header += emit_array('render_frag_spv', 'render.frag.spv')
header += '\n\n/* ── Point cloud shaders ── */\n\n'
header += emit_array('render_points_vert_spv', 'render_points.vert.spv')
header += '\n\n'
header += emit_array('render_points_frag_spv', 'render_points.frag.spv')
header += '\n\n/* ── Gaussian splat shaders ── */\n\n'
header += emit_array('render_gauss_vert_spv', 'render_gauss.vert.spv')
header += '\n\n'
header += emit_array('render_gauss_frag_spv', 'render_gauss.frag.spv')
header += '\n\n#endif /* ERGO_RENDER_SHADERS_H */\n'

with open('render_shaders.h', 'w') as f:
    f.write(header)
"

echo "Done."
ls -la render.vert.spv render.frag.spv render_points.vert.spv render_points.frag.spv render_gauss.vert.spv render_gauss.frag.spv render_shaders.h
