#!/usr/bin/env python3
"""gen_packed_bba5.py — emit a packed multi-seed BBA5 folding sim.

Reads tests/waveform_bba5_seed_0.0.ergo (the sequential-oracle variant:
MAXFRAME=48000, QUENCH=12000, TORSK=0.2, HB_CAP=0) and splices its
shared tables (native coords, Go contacts, register torsions, per-residue
angle/torsion/hydrophobic params) into a packed template:

  - NB = 8 blocks (seeds 0.0..7.0), state packed into 1D arrays of
    NB*NRES with block offset OFF = (B-1)*NRES.
  - Force-field tables stay SHARED (block-independent), indexed by
    LOCAL residue number — the stage-4 packed pattern.
  - Per-frame noise hashes use the LOCAL residue index, identical to the
    sequential runs (SEED enters ONLY the initial coil hash-walk and the
    initial THETA phases in the source — per-frame noise is
    seed-independent there, so packed blocks must share it to reproduce
    the oracle; see packed_check.md).
  - Per-block RMSD_NATIVE via the same quaternion power-iteration
    Kabsch, with a block-offset argument.

Usage: python3 min/pmargin/gen_packed_bba5.py
Output: min/pmargin/packed_bba5.ergo
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "tests" / "waveform_bba5_seed_0.0.ergo"
OUT = ROOT / "min" / "pmargin" / "packed_bba5.ergo"

src = SRC.read_text()

# ── splice 1: shared per-residue params from INIT_CHAIN ("Sequence design"
# section: ANGK/TORSK loop + ANGT0/TORSP0/HYDRO assignments) ─────────────
m = re.search(r"(  ! Sequence design.*?)\nEND\n", src, flags=re.DOTALL)
assert m, "sequence-design section not found"
seq_params = m.group(1).rstrip()
# the splice ends with the original subroutine's RETURN — strip it,
# INIT_SHARED must continue into the native-table init
assert seq_params.endswith("RETURN")
seq_params = seq_params[: -len("RETURN")].rstrip()

# ── splice 2: INIT_NATIVE body (shared native/contact/register tables) ──
m = re.search(r"SUBROUTINE INIT_NATIVE\(\)\n(.*?)\nEND\n", src, flags=re.DOTALL)
assert m, "INIT_NATIVE not found"
init_native_body = m.group(1).rstrip()

# ── packed template ──────────────────────────────────────────────────────
TEMPLATE = r"""! PACKED_BBA5 — 8 folding trajectories (seeds 0.0..7.0) in ONE program.
! Packed stage-4 form: per-block state in 1D arrays (block offset
! OFF = (B-1)*NRES), force-field tables shared (local indexing).
! Generated by min/pmargin/gen_packed_bba5.py from
! tests/waveform_bba5_seed_0.0.ergo (tables spliced verbatim).
! Oracle: sequential seed sweep at 48000 frames (TRANSFERABILITY.md).
!
! SEED enters ONLY the initial coil hash-walk and the initial THETA
! phases (verified in tests/generate_protein_ergo.py + the source);
! per-frame noise is seed-independent and therefore identical across
! blocks BY ORACLE DESIGN.

IMPLICIT NONE

! ── Chain / run ─────────────────────────────────────────────
PARAMETER INTEGER :: NRES = 23
PARAMETER INTEGER :: NBLK = 8
PARAMETER INTEGER :: NPTS = 184
PARAMETER INTEGER :: MAXFRAME = 48000

! ── Time stepping / coupling ──────────────────────────────────
PARAMETER REAL :: DT = 0.01
PARAMETER REAL :: FORCE_SCALE = 6.0
PARAMETER REAL :: VELOCITY_DAMP = 0.9
PARAMETER REAL :: BASE_OMEGA = 1.0
PARAMETER REAL :: COUPLING_K = 5.0
PARAMETER REAL :: PHASE_NOISE_SCALE = 10.0

! ── Thermal schedule ─────────────────────────────────────────
PARAMETER REAL :: HEAT_START = 0.001
PARAMETER REAL :: HEAT_PEAK = 1.0

! ── Backbone (permanent) ─────────────────────────────────────
PARAMETER REAL :: BACKBONE_R0 = 1.52
PARAMETER REAL :: BACKBONE_D = 1.4
PARAMETER REAL :: MORSE_A = 1.0

! ── H-bonds (dynamic contacts) ────────────────────────────────
PARAMETER REAL :: HB_R0 = 2.2
PARAMETER REAL :: HB_D = 0.30
PARAMETER REAL :: HB_FORM = 2.5
PARAMETER REAL :: HB_BREAK = 2.8
PARAMETER INTEGER :: HB_CAP = 0
PARAMETER REAL :: HB_PHASE_FORM = 0.80
PARAMETER REAL :: HB_PHASE_STABLE = 0.95

! ── Steric exclusion ─────────────────────────────────────────
PARAMETER REAL :: STERIC_SIG = 1.60
PARAMETER REAL :: STERIC_EPS = 0.1
PARAMETER REAL :: STERIC_CUT = 2.5

! ── Hydrophobic attraction ───────────────────────────────────
PARAMETER REAL :: HYDRO_STRENGTH = 0.0020
PARAMETER REAL :: HYDRO_R0 = 4.0
PARAMETER REAL :: HYDRO_CUTOFF = 8.0
PARAMETER REAL :: HYDRO_ALPHA = 1.0

! ── Native contact potential (Go-like) ─────────────────────────
PARAMETER REAL :: NATIVE_K = 1.00
PARAMETER REAL :: NATIVE_CUTOFF = 2.522943

! ── Cross-strand register torsion ────────────────────────────
PARAMETER INTEGER :: MAXREG = 6
PARAMETER INTEGER :: NREG = 6
PARAMETER INTEGER :: EXTRA_TORSIONS_FROM = 1200

! ── Packed residue state (block offset OFF = (B-1)*NRES) ─────
STATIC REAL :: RES_X(184)
STATIC REAL :: RES_Y(184)
STATIC REAL :: RES_Z(184)
STATIC REAL :: RES_VX(184)
STATIC REAL :: RES_VY(184)
STATIC REAL :: RES_VZ(184)
STATIC REAL :: RES_THETA(184)
STATIC REAL :: RES_OMEGA(184)

! ── Shared per-residue sequence parameters (block-independent) ─
STATIC REAL :: RES_ANGK(23)
STATIC REAL :: RES_ANGT0(23)
STATIC REAL :: RES_TORSK(23)
STATIC REAL :: RES_TORSP0(23)
STATIC REAL :: RES_HYDRO(23)

! ── Shared native coordinates ─────────────────────────────────
STATIC REAL :: NATIVE_X(23)
STATIC REAL :: NATIVE_Y(23)
STATIC REAL :: NATIVE_Z(23)

! ── Shared native contact tables ─────────────────────────────
STATIC INTEGER :: NATIVE_CONTACT(23, 23)
STATIC REAL :: NATIVE_R0(23, 23)

! ── Per-block H-bond state (packed rows; HB_CAP=0 => stays zero) ─
STATIC INTEGER :: HBOND_MATRIX(184, 184)

! ── Per-block seeds and results ──────────────────────────────
STATIC REAL :: SEED_TAB(8)
DATA SEED_TAB / 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0 /
STATIC REAL :: RMSD_B(8)

! ── Diagnostics / working scalars ────────────────────────────
STATIC REAL :: E_NATIVE
STATIC REAL :: THERMAL_CURRENT
STATIC REAL :: RMSD_NATIVE
STATIC INTEGER :: HB_FORMS
STATIC INTEGER :: HB_BREAKS

STATIC INTEGER :: I, J, K, FRAME, B, OFF
STATIC REAL :: X, Y, Z, R, D, E, F
STATIC REAL :: DX, DY, DZ, CS, ALIGN, FM, TEMP_X
STATIC REAL :: SIN_AVG, COS_AVG, THETA_MEAN
STATIC REAL :: ANG, COSA, BX, CX, BY, CY, BZ, CZ
STATIC REAL :: UX, UY, UZ, WX, WY, WZ, UN, VN, B1X, B1Y, B1Z
STATIC REAL :: B2X, B2Y, B2Z, B3X, B3Y, B3Z, N1X, N1Y, N1Z
STATIC REAL :: N2X, N2Y, N2Z, B2MAG, PHI, DPHI_DR1X, DPHI_DR1Y, DPHI_DR1Z
STATIC REAL :: DPHI_DR4X, DPHI_DR4Y, DPHI_DR4Z, DPHI_DR2X, DPHI_DR2Y, DPHI_DR2Z
STATIC REAL :: DPHI_DR3X, DPHI_DR3Y, DPHI_DR3Z, N1MAG2, N2MAG2, N1MAG, N2MAG
STATIC REAL :: B1DOT, B3DOT, SCALE_B2, SCALE_B1, SCALE_B3

STATIC INTEGER :: REG_A(MAXREG)
STATIC INTEGER :: REG_B(MAXREG)
STATIC INTEGER :: REG_C(MAXREG)
STATIC INTEGER :: REG_D(MAXREG)
STATIC REAL :: REG_K(MAXREG)
STATIC REAL :: REG_P0(MAXREG)
STATIC INTEGER :: IA, IB, IC, ID

! ── Initialize ─────────────────────────────────────────────
CALL INIT_SHARED()
DO B = 1, NBLK
  OFF := (B - 1) * NRES
  CALL INIT_COIL(OFF, SEED_TAB(B))
ENDDO

WRITE(*, "# PACKED_BBA5 NBLK=8 NRES=23 MAXFRAME=48000 QUENCH=12000")
WRITE(*, "# TRACE cols: block seed frame rmsd_native (blocks 1,2,5 every 100)")
WRITE(*, "# FINAL cols: block seed rmsd_native (all blocks, frame 48000)")

! ════════════════════════════════════════════════════════════
! MAIN LOOP: frame outer, block inner (per-block dynamics are the
! sequential program verbatim with OFF-shifted state accesses and
! LOCAL residue indices in the noise hashes — see header note)
! ════════════════════════════════════════════════════════════
DO FRAME = 1, MAXFRAME

  DO B = 1, NBLK
    OFF := (B - 1) * NRES

    ! Phase dynamics: intrinsic advance + Kuramoto coupling + noise
    DO I = 1, NRES
      RES_THETA(OFF + I) := RES_THETA(OFF + I) + RES_OMEGA(OFF + I) * DT
    ENDDO

    SIN_AVG := 0.0
    COS_AVG := 0.0
    DO I = 1, NRES
      SIN_AVG := SIN_AVG + SIN(RES_THETA(OFF + I))
      COS_AVG := COS_AVG + COS(RES_THETA(OFF + I))
    ENDDO
    THETA_MEAN := ATAN2(SIN_AVG, COS_AVG)
    DO I = 1, NRES
      RES_THETA(OFF + I) := RES_THETA(OFF + I) + COUPLING_K * SIN(THETA_MEAN - RES_THETA(OFF + I)) * DT
    ENDDO

    ! Phase noise (LOCAL index — identical to sequential oracle)
    TEMP_X := THERMAL_CURRENT * PHASE_NOISE_SCALE
    DO I = 1, NRES
      RES_THETA(OFF + I) := RES_THETA(OFF + I) + TEMP_X * SIN((I+1)*11.3 + REAL(FRAME)*0.23) * DT
    ENDDO

    ! Thermal impulses (velocity kicks, LOCAL index)
    DO I = 1, NRES
      RES_VX(OFF + I) := RES_VX(OFF + I) + THERMAL_CURRENT * SIN((I+1)*7.3 + REAL(FRAME)*0.17)
      RES_VY(OFF + I) := RES_VY(OFF + I) + THERMAL_CURRENT * COS((I+1)*5.7 + REAL(FRAME)*0.31)
      RES_VZ(OFF + I) := RES_VZ(OFF + I) + THERMAL_CURRENT * SIN((I+1)*3.1 + REAL(FRAME)*0.09)
    ENDDO

    ! Steric repulsion (|i-j| >= 4, not H-bonded)
    DO I = 1, NRES-4
      DO J = I+4, NRES
        IF HBOND_MATRIX(OFF + I, OFF + J) = 0 THEN
          DX := RES_X(OFF + I) - RES_X(OFF + J)
          DY := RES_Y(OFF + I) - RES_Y(OFF + J)
          DZ := RES_Z(OFF + I) - RES_Z(OFF + J)
          D := SQRT(DX*DX + DY*DY + DZ*DZ)
          IF D > 0.0 .AND. D < STERIC_CUT THEN
            FM := STERIC_EPS * (STERIC_SIG / D) ** 6
            RES_VX(OFF + I) := RES_VX(OFF + I) + FM * DX / D * DT * FORCE_SCALE
            RES_VY(OFF + I) := RES_VY(OFF + I) + FM * DY / D * DT * FORCE_SCALE
            RES_VZ(OFF + I) := RES_VZ(OFF + I) + FM * DZ / D * DT * FORCE_SCALE
            RES_VX(OFF + J) := RES_VX(OFF + J) - FM * DX / D * DT * FORCE_SCALE
            RES_VY(OFF + J) := RES_VY(OFF + J) - FM * DY / D * DT * FORCE_SCALE
            RES_VZ(OFF + J) := RES_VZ(OFF + J) - FM * DZ / D * DT * FORCE_SCALE
          ENDIF
        ENDIF
      ENDDO
    ENDDO

    ! Hydrophobic attraction between Cα beads
    DO I = 1, NRES-4
      DO J = I+4, NRES
        IF RES_HYDRO(I) > 0.0 .AND. RES_HYDRO(J) > 0.0 THEN
          DX := RES_X(OFF + I) - RES_X(OFF + J)
          DY := RES_Y(OFF + I) - RES_Y(OFF + J)
          DZ := RES_Z(OFF + I) - RES_Z(OFF + J)
          D := SQRT(DX*DX + DY*DY + DZ*DZ)
          IF D > 0.0 .AND. D < HYDRO_CUTOFF THEN
            FM := -HYDRO_STRENGTH * RES_HYDRO(I) * RES_HYDRO(J) * EXP(-HYDRO_ALPHA * (D - HYDRO_R0))
            RES_VX(OFF + I) := RES_VX(OFF + I) + FM * DX / D * DT * FORCE_SCALE
            RES_VY(OFF + I) := RES_VY(OFF + I) + FM * DY / D * DT * FORCE_SCALE
            RES_VZ(OFF + I) := RES_VZ(OFF + I) + FM * DZ / D * DT * FORCE_SCALE
            RES_VX(OFF + J) := RES_VX(OFF + J) - FM * DX / D * DT * FORCE_SCALE
            RES_VY(OFF + J) := RES_VY(OFF + J) - FM * DY / D * DT * FORCE_SCALE
            RES_VZ(OFF + J) := RES_VZ(OFF + J) - FM * DZ / D * DT * FORCE_SCALE
          ENDIF
        ENDIF
      ENDDO
    ENDDO

    ! Go-like native contact potential (shared local tables)
    DO I = 1, NRES-3
      DO J = I+3, NRES
        IF NATIVE_CONTACT(I, J) = 1 THEN
          DX := RES_X(OFF + I) - RES_X(OFF + J)
          DY := RES_Y(OFF + I) - RES_Y(OFF + J)
          DZ := RES_Z(OFF + I) - RES_Z(OFF + J)
          D := SQRT(DX*DX + DY*DY + DZ*DZ)
          IF D > 0.0 THEN
            FM := -2.0 * NATIVE_K * (D - NATIVE_R0(I, J))
            RES_VX(OFF + I) := RES_VX(OFF + I) + FM * DX / D * DT * FORCE_SCALE
            RES_VY(OFF + I) := RES_VY(OFF + I) + FM * DY / D * DT * FORCE_SCALE
            RES_VZ(OFF + I) := RES_VZ(OFF + I) + FM * DZ / D * DT * FORCE_SCALE
            RES_VX(OFF + J) := RES_VX(OFF + J) - FM * DX / D * DT * FORCE_SCALE
            RES_VY(OFF + J) := RES_VY(OFF + J) - FM * DY / D * DT * FORCE_SCALE
            RES_VZ(OFF + J) := RES_VZ(OFF + J) - FM * DZ / D * DT * FORCE_SCALE
          ENDIF
        ENDIF
      ENDDO
    ENDDO

    ! Morse bonds (backbone)
    DO I = 1, NRES-1
      DX := RES_X(OFF + I) - RES_X(OFF + I+1)
      DY := RES_Y(OFF + I) - RES_Y(OFF + I+1)
      DZ := RES_Z(OFF + I) - RES_Z(OFF + I+1)
      D := SQRT(DX*DX + DY*DY + DZ*DZ)
      IF D > 0.0 THEN
        E := EXP(-MORSE_A * (D - BACKBONE_R0))
        FM := -2.0 * BACKBONE_D * MORSE_A * (1.0 - E) * E * FORCE_SCALE
        RES_VX(OFF + I) := RES_VX(OFF + I) + FM * DX / D * DT
        RES_VY(OFF + I) := RES_VY(OFF + I) + FM * DY / D * DT
        RES_VZ(OFF + I) := RES_VZ(OFF + I) + FM * DZ / D * DT
        RES_VX(OFF + I+1) := RES_VX(OFF + I+1) - FM * DX / D * DT
        RES_VY(OFF + I+1) := RES_VY(OFF + I+1) - FM * DY / D * DT
        RES_VZ(OFF + I+1) := RES_VZ(OFF + I+1) - FM * DZ / D * DT
      ENDIF
    ENDDO

    ! Angle bending (backbone angles)
    DO I = 2, NRES-1
      BX := RES_X(OFF + I-1) - RES_X(OFF + I)
      BY := RES_Y(OFF + I-1) - RES_Y(OFF + I)
      BZ := RES_Z(OFF + I-1) - RES_Z(OFF + I)
      CX := RES_X(OFF + I+1) - RES_X(OFF + I)
      CY := RES_Y(OFF + I+1) - RES_Y(OFF + I)
      CZ := RES_Z(OFF + I+1) - RES_Z(OFF + I)
      UN := SQRT(BX*BX + BY*BY + BZ*BZ)
      VN := SQRT(CX*CX + CY*CY + CZ*CZ)
      IF UN > 1.0E-12 .AND. VN > 1.0E-12 THEN
        CS := MAX(-1.0, MIN(1.0, (BX*CX + BY*CY + BZ*CZ) / (UN * VN)))
        E := 2.0 * RES_ANGK(I) * (CS - COS(RES_ANGT0(I)))
        UX := (CX / (UN * VN) - CS * BX / UN / UN)
        UY := (CY / (UN * VN) - CS * BY / UN / UN)
        UZ := (CZ / (UN * VN) - CS * BZ / UN / UN)
        WX := (BX / (UN * VN) - CS * CX / VN / VN)
        WY := (BY / (UN * VN) - CS * CY / VN / VN)
        WZ := (BZ / (UN * VN) - CS * CZ / VN / VN)
        RES_VX(OFF + I-1) := RES_VX(OFF + I-1) - E * UX * DT * FORCE_SCALE
        RES_VY(OFF + I-1) := RES_VY(OFF + I-1) - E * UY * DT * FORCE_SCALE
        RES_VZ(OFF + I-1) := RES_VZ(OFF + I-1) - E * UZ * DT * FORCE_SCALE
        RES_VX(OFF + I+1) := RES_VX(OFF + I+1) - E * WX * DT * FORCE_SCALE
        RES_VY(OFF + I+1) := RES_VY(OFF + I+1) - E * WY * DT * FORCE_SCALE
        RES_VZ(OFF + I+1) := RES_VZ(OFF + I+1) - E * WZ * DT * FORCE_SCALE
        RES_VX(OFF + I) := RES_VX(OFF + I) + (E * UX + E * WX) * DT * FORCE_SCALE
        RES_VY(OFF + I) := RES_VY(OFF + I) + (E * UY + E * WY) * DT * FORCE_SCALE
        RES_VZ(OFF + I) := RES_VZ(OFF + I) + (E * UZ + E * WZ) * DT * FORCE_SCALE
      ENDIF
    ENDDO

    ! Torsion (dihedral) angles
    DO I = 2, NRES-2
      B1X := RES_X(OFF + I) - RES_X(OFF + I-1)
      B1Y := RES_Y(OFF + I) - RES_Y(OFF + I-1)
      B1Z := RES_Z(OFF + I) - RES_Z(OFF + I-1)
      B2X := RES_X(OFF + I+1) - RES_X(OFF + I)
      B2Y := RES_Y(OFF + I+1) - RES_Y(OFF + I)
      B2Z := RES_Z(OFF + I+1) - RES_Z(OFF + I)
      B3X := RES_X(OFF + I+2) - RES_X(OFF + I+1)
      B3Y := RES_Y(OFF + I+2) - RES_Y(OFF + I+1)
      B3Z := RES_Z(OFF + I+2) - RES_Z(OFF + I+1)

      N1X := B1Y*B2Z - B1Z*B2Y
      N1Y := B1Z*B2X - B1X*B2Z
      N1Z := B1X*B2Y - B1Y*B2X
      N2X := B2Y*B3Z - B2Z*B3Y
      N2Y := B2Z*B3X - B2X*B3Z
      N2Z := B2X*B3Y - B2Y*B3X

      N1MAG2 := N1X*N1X + N1Y*N1Y + N1Z*N1Z
      N2MAG2 := N2X*N2X + N2Y*N2Y + N2Z*N2Z
      B2MAG := SQRT(B2X*B2X + B2Y*B2Y + B2Z*B2Z)

      IF N1MAG2 > 1.0E-12 .AND. N2MAG2 > 1.0E-12 .AND. B2MAG > 1.0E-12 THEN
        N1MAG := SQRT(N1MAG2)
        N2MAG := SQRT(N2MAG2)
        PHI := ATAN2(B2MAG*(B1X*N2X + B1Y*N2Y + B1Z*N2Z), N1X*N2X + N1Y*N2Y + N1Z*N2Z)
        E := 2.0 * RES_TORSK(I) * (1.0 - COS(PHI - RES_TORSP0(I)))

        DPHI_DR1X := -B2MAG / N1MAG2 * N1X
        DPHI_DR1Y := -B2MAG / N1MAG2 * N1Y
        DPHI_DR1Z := -B2MAG / N1MAG2 * N1Z

        DPHI_DR4X := B2MAG / N2MAG2 * N2X
        DPHI_DR4Y := B2MAG / N2MAG2 * N2Y
        DPHI_DR4Z := B2MAG / N2MAG2 * N2Z

        B1DOT := B1X*B2X + B1Y*B2Y + B1Z*B2Z
        B3DOT := B3X*B2X + B3Y*B2Y + B3Z*B2Z
        SCALE_B2 := 1.0 / (B2MAG * B2MAG)
        SCALE_B1 := B1DOT * SCALE_B2
        SCALE_B3 := B3DOT * SCALE_B2

        DPHI_DR2X := -(1.0 + SCALE_B1) * DPHI_DR1X + SCALE_B3 * DPHI_DR4X
        DPHI_DR2Y := -(1.0 + SCALE_B1) * DPHI_DR1Y + SCALE_B3 * DPHI_DR4Y
        DPHI_DR2Z := -(1.0 + SCALE_B1) * DPHI_DR1Z + SCALE_B3 * DPHI_DR4Z

        DPHI_DR3X := -(DPHI_DR1X + DPHI_DR2X + DPHI_DR4X)
        DPHI_DR3Y := -(DPHI_DR1Y + DPHI_DR2Y + DPHI_DR4Y)
        DPHI_DR3Z := -(DPHI_DR1Z + DPHI_DR2Z + DPHI_DR4Z)

        F := -2.0 * RES_TORSK(I) * SIN(PHI - RES_TORSP0(I))

        RES_VX(OFF + I-1) := RES_VX(OFF + I-1) + F * DPHI_DR1X * DT * FORCE_SCALE
        RES_VY(OFF + I-1) := RES_VY(OFF + I-1) + F * DPHI_DR1Y * DT * FORCE_SCALE
        RES_VZ(OFF + I-1) := RES_VZ(OFF + I-1) + F * DPHI_DR1Z * DT * FORCE_SCALE

        RES_VX(OFF + I) := RES_VX(OFF + I) + F * DPHI_DR2X * DT * FORCE_SCALE
        RES_VY(OFF + I) := RES_VY(OFF + I) + F * DPHI_DR2Y * DT * FORCE_SCALE
        RES_VZ(OFF + I) := RES_VZ(OFF + I) + F * DPHI_DR2Z * DT * FORCE_SCALE

        RES_VX(OFF + I+1) := RES_VX(OFF + I+1) + F * DPHI_DR3X * DT * FORCE_SCALE
        RES_VY(OFF + I+1) := RES_VY(OFF + I+1) + F * DPHI_DR3Y * DT * FORCE_SCALE
        RES_VZ(OFF + I+1) := RES_VZ(OFF + I+1) + F * DPHI_DR3Z * DT * FORCE_SCALE

        RES_VX(OFF + I+2) := RES_VX(OFF + I+2) + F * DPHI_DR4X * DT * FORCE_SCALE
        RES_VY(OFF + I+2) := RES_VY(OFF + I+2) + F * DPHI_DR4Y * DT * FORCE_SCALE
        RES_VZ(OFF + I+2) := RES_VZ(OFF + I+2) + F * DPHI_DR4Z * DT * FORCE_SCALE
      ENDIF
    ENDDO

    ! Cross-strand register torsions (from frame 1200, shared tables)
    IF FRAME > EXTRA_TORSIONS_FROM THEN
      DO K = 1, NREG
        IA := REG_A(K)
        IB := REG_B(K)
        IC := REG_C(K)
        ID := REG_D(K)

        B1X := RES_X(OFF + IB) - RES_X(OFF + IA)
        B1Y := RES_Y(OFF + IB) - RES_Y(OFF + IA)
        B1Z := RES_Z(OFF + IB) - RES_Z(OFF + IA)
        B2X := RES_X(OFF + IC) - RES_X(OFF + IB)
        B2Y := RES_Y(OFF + IC) - RES_Y(OFF + IB)
        B2Z := RES_Z(OFF + IC) - RES_Z(OFF + IB)
        B3X := RES_X(OFF + ID) - RES_X(OFF + IC)
        B3Y := RES_Y(OFF + ID) - RES_Y(OFF + IC)
        B3Z := RES_Z(OFF + ID) - RES_Z(OFF + IC)

        N1X := B1Y*B2Z - B1Z*B2Y
        N1Y := B1Z*B2X - B1X*B2Z
        N1Z := B1X*B2Y - B1Y*B2X
        N2X := B2Y*B3Z - B2Z*B3Y
        N2Y := B2Z*B3X - B2X*B3Z
        N2Z := B2X*B3Y - B2Y*B3X

        N1MAG2 := N1X*N1X + N1Y*N1Y + N1Z*N1Z
        N2MAG2 := N2X*N2X + N2Y*N2Y + N2Z*N2Z
        B2MAG := SQRT(B2X*B2X + B2Y*B2Y + B2Z*B2Z)

        IF N1MAG2 > 1.0E-12 .AND. N2MAG2 > 1.0E-12 .AND. B2MAG > 1.0E-12 THEN
          N1MAG := SQRT(N1MAG2)
          N2MAG := SQRT(N2MAG2)
          PHI := ATAN2(B2MAG*(B1X*N2X + B1Y*N2Y + B1Z*N2Z), N1X*N2X + N1Y*N2Y + N1Z*N2Z)
          F := -2.0 * REG_K(K) * SIN(PHI - REG_P0(K))

          DPHI_DR1X := -B2MAG / N1MAG2 * N1X
          DPHI_DR1Y := -B2MAG / N1MAG2 * N1Y
          DPHI_DR1Z := -B2MAG / N1MAG2 * N1Z

          DPHI_DR4X := B2MAG / N2MAG2 * N2X
          DPHI_DR4Y := B2MAG / N2MAG2 * N2Y
          DPHI_DR4Z := B2MAG / N2MAG2 * N2Z

          B1DOT := B1X*B2X + B1Y*B2Y + B1Z*B2Z
          B3DOT := B3X*B2X + B3Y*B2Y + B3Z*B2Z
          SCALE_B2 := 1.0 / (B2MAG * B2MAG)
          SCALE_B1 := B1DOT * SCALE_B2
          SCALE_B3 := B3DOT * SCALE_B2

          DPHI_DR2X := -(1.0 + SCALE_B1) * DPHI_DR1X + SCALE_B3 * DPHI_DR4X
          DPHI_DR2Y := -(1.0 + SCALE_B1) * DPHI_DR1Y + SCALE_B3 * DPHI_DR4Y
          DPHI_DR2Z := -(1.0 + SCALE_B1) * DPHI_DR1Z + SCALE_B3 * DPHI_DR4Z

          DPHI_DR3X := -(DPHI_DR1X + DPHI_DR2X + DPHI_DR4X)
          DPHI_DR3Y := -(DPHI_DR1Y + DPHI_DR2Y + DPHI_DR4Y)
          DPHI_DR3Z := -(DPHI_DR1Z + DPHI_DR2Z + DPHI_DR4Z)

          RES_VX(OFF + IA) := RES_VX(OFF + IA) + F * DPHI_DR1X * DT * FORCE_SCALE
          RES_VY(OFF + IA) := RES_VY(OFF + IA) + F * DPHI_DR1Y * DT * FORCE_SCALE
          RES_VZ(OFF + IA) := RES_VZ(OFF + IA) + F * DPHI_DR1Z * DT * FORCE_SCALE

          RES_VX(OFF + IB) := RES_VX(OFF + IB) + F * DPHI_DR2X * DT * FORCE_SCALE
          RES_VY(OFF + IB) := RES_VY(OFF + IB) + F * DPHI_DR2Y * DT * FORCE_SCALE
          RES_VZ(OFF + IB) := RES_VZ(OFF + IB) + F * DPHI_DR2Z * DT * FORCE_SCALE

          RES_VX(OFF + IC) := RES_VX(OFF + IC) + F * DPHI_DR3X * DT * FORCE_SCALE
          RES_VY(OFF + IC) := RES_VY(OFF + IC) + F * DPHI_DR3Y * DT * FORCE_SCALE
          RES_VZ(OFF + IC) := RES_VZ(OFF + IC) + F * DPHI_DR3Z * DT * FORCE_SCALE

          RES_VX(OFF + ID) := RES_VX(OFF + ID) + F * DPHI_DR4X * DT * FORCE_SCALE
          RES_VY(OFF + ID) := RES_VY(OFF + ID) + F * DPHI_DR4Y * DT * FORCE_SCALE
          RES_VZ(OFF + ID) := RES_VZ(OFF + ID) + F * DPHI_DR4Z * DT * FORCE_SCALE
        ENDIF
      ENDDO
    ENDIF

    ! Velocity damping
    DO I = 1, NRES
      RES_VX(OFF + I) := RES_VX(OFF + I) * VELOCITY_DAMP
      RES_VY(OFF + I) := RES_VY(OFF + I) * VELOCITY_DAMP
      RES_VZ(OFF + I) := RES_VZ(OFF + I) * VELOCITY_DAMP
    ENDDO

    ! Position update
    DO I = 1, NRES
      RES_X(OFF + I) := RES_X(OFF + I) + RES_VX(OFF + I) * DT
      RES_Y(OFF + I) := RES_Y(OFF + I) + RES_VY(OFF + I) * DT
      RES_Z(OFF + I) := RES_Z(OFF + I) + RES_VZ(OFF + I) * DT
    ENDDO

    ! H-bond update (per block; no-op at HB_CAP=0, kept faithful)
    CALL UPDATE_HBONDS(OFF)

  ENDDO

  ! Thermal schedule (called at END of frame, exactly as the sequential
  ! source: frame F dynamics use the value set at the end of frame F-1,
  ! and frame 1 runs with the BSS-initial 0.0)
  CALL UPDATE_THERMAL(FRAME)

  ! Per-frame RMSD trace for blocks 1, 2, 5 every 100 frames
  IF MOD(FRAME, 100) = 0 THEN
    DO B = 1, NBLK
      IF B = 1 .OR. B = 2 .OR. B = 5 THEN
        OFF := (B - 1) * NRES
        CALL COMPUTE_RMSD(OFF)
        WRITE(*, "TRACE %d %.1f %d %.4f") B, SEED_TAB(B), FRAME, RMSD_NATIVE
      ENDIF
    ENDDO
  ENDIF

ENDDO

! Final per-block RMSD
DO B = 1, NBLK
  OFF := (B - 1) * NRES
  CALL COMPUTE_RMSD(OFF)
  RMSD_B(B) := RMSD_NATIVE
ENDDO
DO B = 1, NBLK
  WRITE(*, "FINAL %d %.1f %.4f") B, SEED_TAB(B), RMSD_B(B)
ENDDO
WRITE(*, "# DONE")

STOP

! ════════════════════════════════════════════════════════════
! INIT_SHARED: shared per-residue params + native/contact/register
! tables (spliced verbatim from waveform_bba5_seed_0.0.ergo)
! ════════════════════════════════════════════════════════════

SUBROUTINE INIT_SHARED()
__SEQ_PARAMS__

__INIT_NATIVE__
END

! ════════════════════════════════════════════════════════════
! INIT_COIL: per-block self-avoiding hash-walk coil + phases.
! Replicates the sequential INIT_CHAIN arithmetic exactly, with
! SEEDB in place of the SEED parameter and OFF-shifted state.
! ════════════════════════════════════════════════════════════

SUBROUTINE INIT_COIL(OFFB, SEEDB)
  INTEGER :: OFFB
  REAL :: SEEDB
  INTEGER :: I, ATT, J2, OK
  REAL :: U1, U2, COSTH, SINTH, PHI2, UX, UY, UZ, CANDX, CANDY, CANDZ, DD

  RES_X(OFFB + 1) := 10.0
  RES_Y(OFFB + 1) := 10.0
  RES_Z(OFFB + 1) := 10.0
  DO I = 2, NRES
    OK := 0
    ATT := 0
    DO WHILE ATT < 20
      ATT := ATT + 1
      U1 := MOD(ABS(SIN(REAL(I) * 12.9898 + REAL(ATT) * 3.7 + SEEDB) * 43758.5453), 1.0)
      U2 := MOD(ABS(SIN(REAL(I) * 78.2330 + REAL(ATT) * 1.3 + SEEDB) * 12543.1230), 1.0)
      COSTH := 2.0 * U1 - 1.0
      SINTH := SQRT(1.0 - COSTH * COSTH)
      PHI2 := 2.0 * 3.14159265 * U2
      UX := SINTH * COS(PHI2)
      UY := SINTH * SIN(PHI2)
      UZ := COSTH
      CANDX := RES_X(OFFB + I - 1) + UX * BACKBONE_R0
      CANDY := RES_Y(OFFB + I - 1) + UY * BACKBONE_R0
      CANDZ := RES_Z(OFFB + I - 1) + UZ * BACKBONE_R0
      OK := 1
      IF I ≥ 5 THEN
        DO J2 = 1, I - 4
          DD := SQRT((CANDX - RES_X(OFFB + J2))**2 + (CANDY - RES_Y(OFFB + J2))**2 + (CANDZ - RES_Z(OFFB + J2))**2)
          IF DD < 1.55 THEN
            OK := 0
          ENDIF
        ENDDO
      ENDIF
      IF OK = 1 THEN
        ATT := 20
      ENDIF
    ENDDO
    RES_X(OFFB + I) := CANDX
    RES_Y(OFFB + I) := CANDY
    RES_Z(OFFB + I) := CANDZ
  ENDDO

  DO I = 1, NRES
    RES_THETA(OFFB + I) := 0.3 * RES_X(OFFB + I) + 0.5 * RES_Y(OFFB + I) + 0.7 * RES_Z(OFFB + I) + SEEDB
    RES_OMEGA(OFFB + I) := BASE_OMEGA + 0.5 * SIN(RES_THETA(OFFB + I))
    RES_VX(OFFB + I) := 0.0
    RES_VY(OFFB + I) := 0.0
    RES_VZ(OFFB + I) := 0.0
  ENDDO
END

! ════════════════════════════════════════════════════════════
! UPDATE_THERMAL (block-independent; verbatim from source)
! ════════════════════════════════════════════════════════════

SUBROUTINE UPDATE_THERMAL(FRAME)
  INTEGER :: FRAME
  REAL :: FRAC

  THERMAL_CURRENT := HEAT_START

  IF FRAME < 300 THEN
    FRAC := REAL(FRAME) / 300.0
    THERMAL_CURRENT := HEAT_START + (HEAT_PEAK - HEAT_START) * FRAC
  ELSEIF FRAME < 600 THEN
    FRAC := REAL(FRAME - 300) / 300.0
    THERMAL_CURRENT := HEAT_PEAK - (HEAT_PEAK - HEAT_START) * FRAC
  ELSEIF FRAME < 900 THEN
    FRAC := REAL(FRAME - 600) / 300.0
    THERMAL_CURRENT := HEAT_START + (HEAT_PEAK - HEAT_START) * FRAC
  ELSEIF FRAME < 1200 THEN
    FRAC := REAL(FRAME - 900) / 300.0
    THERMAL_CURRENT := HEAT_PEAK - (HEAT_PEAK - HEAT_START) * FRAC
  ELSE
    THERMAL_CURRENT := HEAT_START
  ENDIF

  ! Quench tail: zero thermal noise after frame 12000
  IF FRAME > 12000 THEN
    THERMAL_CURRENT := 0.0
  ENDIF

  RETURN
END

! ════════════════════════════════════════════════════════════
! UPDATE_HBONDS (per block, OFFB-shifted; verbatim logic)
! ════════════════════════════════════════════════════════════

SUBROUTINE UPDATE_HBONDS(OFFB)
  INTEGER :: OFFB
  INTEGER :: I, J, DEG_I, DEG_J, NF, NB
  REAL :: DX, DY, DZ, D, ALIGN

  NF := 0
  NB := 0

  DO I = 1, NRES
    DEG_I := 0
    DO J = 1, NRES
      IF HBOND_MATRIX(OFFB + I, OFFB + J) = 1 THEN
        DEG_I := DEG_I + 1
      ENDIF
    ENDDO
  ENDDO

  ! Break weak H-bonds
  DO I = 1, NRES-3
    DO J = I+3, NRES
      IF HBOND_MATRIX(OFFB + I, OFFB + J) = 1 THEN
        DX := RES_X(OFFB + I) - RES_X(OFFB + J)
        DY := RES_Y(OFFB + I) - RES_Y(OFFB + J)
        DZ := RES_Z(OFFB + I) - RES_Z(OFFB + J)
        D := SQRT(DX*DX + DY*DY + DZ*DZ)
        ALIGN := COS(RES_THETA(OFFB + I) - RES_THETA(OFFB + J))
        IF ALIGN < HB_PHASE_STABLE .OR. D > HB_BREAK THEN
          HBOND_MATRIX(OFFB + I, OFFB + J) := 0
          HBOND_MATRIX(OFFB + J, OFFB + I) := 0
          NB := NB + 1
        ENDIF
      ENDIF
    ENDDO
  ENDDO

  ! Form new H-bonds
  DO I = 1, NRES-3
    DEG_I := 0
    DO J = 1, NRES
      IF HBOND_MATRIX(OFFB + I, OFFB + J) = 1 THEN
        DEG_I := DEG_I + 1
      ENDIF
    ENDDO
    IF DEG_I < HB_CAP THEN
      DO J = I+3, NRES
        IF HBOND_MATRIX(OFFB + I, OFFB + J) = 0 THEN
          DEG_J := 0
          DO K = 1, NRES
            IF HBOND_MATRIX(OFFB + J, OFFB + K) = 1 THEN
              DEG_J := DEG_J + 1
            ENDIF
          ENDDO
          IF DEG_J < HB_CAP THEN
            DX := RES_X(OFFB + I) - RES_X(OFFB + J)
            DY := RES_Y(OFFB + I) - RES_Y(OFFB + J)
            DZ := RES_Z(OFFB + I) - RES_Z(OFFB + J)
            D := SQRT(DX*DX + DY*DY + DZ*DZ)
            ALIGN := COS(RES_THETA(OFFB + I) - RES_THETA(OFFB + J))
            IF D < HB_FORM .AND. ALIGN > HB_PHASE_FORM THEN
              HBOND_MATRIX(OFFB + I, OFFB + J) := 1
              HBOND_MATRIX(OFFB + J, OFFB + I) := 1
              NF := NF + 1
            ENDIF
          ENDIF
        ENDIF
      ENDDO
    ENDIF
  ENDDO

  HB_FORMS := NF
  HB_BREAKS := NB

  RETURN
END

! ════════════════════════════════════════════════════════════
! COMPUTE_RMSD (per block, OFFB-shifted; Kabsch via quaternion
! power iteration — verbatim logic from source)
! ════════════════════════════════════════════════════════════

SUBROUTINE COMPUTE_RMSD(OFFB)
  INTEGER :: OFFB
  INTEGER :: I, ITER
  REAL :: XC, YC, ZC, XN, YN, ZN
  REAL :: SXX, SXY, SXZ, SYX, SYY, SYZ, SZX, SZY, SZZ
  REAL :: N44(4,4), VEC(4), NEWVEC(4), LAMBDA, NORM
  REAL :: RX, RY, RZ, NX, NY, NZ
  REAL :: Q0, Q1, Q2, Q3, QQ
  REAL :: R11, R12, R13, R21, R22, R23, R31, R32, R33
  REAL :: TX, TY, TZ, SUM_DIST_SQ

  XC := 0.0
  YC := 0.0
  ZC := 0.0
  DO I = 1, NRES
    XC := XC + RES_X(OFFB + I)
    YC := YC + RES_Y(OFFB + I)
    ZC := ZC + RES_Z(OFFB + I)
  ENDDO
  XC := XC / REAL(NRES)
  YC := YC / REAL(NRES)
  ZC := ZC / REAL(NRES)

  XN := 0.0
  YN := 0.0
  ZN := 0.0
  DO I = 1, NRES
    XN := XN + NATIVE_X(I)
    YN := YN + NATIVE_Y(I)
    ZN := ZN + NATIVE_Z(I)
  ENDDO
  XN := XN / REAL(NRES)
  YN := YN / REAL(NRES)
  ZN := ZN / REAL(NRES)

  SXX := 0.0
  SXY := 0.0
  SXZ := 0.0
  SYX := 0.0
  SYY := 0.0
  SYZ := 0.0
  SZX := 0.0
  SZY := 0.0
  SZZ := 0.0
  DO I = 1, NRES
    RX := RES_X(OFFB + I) - XC
    RY := RES_Y(OFFB + I) - YC
    RZ := RES_Z(OFFB + I) - ZC
    NX := NATIVE_X(I) - XN
    NY := NATIVE_Y(I) - YN
    NZ := NATIVE_Z(I) - ZN
    SXX := SXX + RX * NX
    SXY := SXY + RX * NY
    SXZ := SXZ + RX * NZ
    SYX := SYX + RY * NX
    SYY := SYY + RY * NY
    SYZ := SYZ + RY * NZ
    SZX := SZX + RZ * NX
    SZY := SZY + RZ * NY
    SZZ := SZZ + RZ * NZ
  ENDDO

  N44(1,1) := SXX + SYY + SZZ
  N44(1,2) := SYZ - SZY
  N44(1,3) := SZX - SXZ
  N44(1,4) := SXY - SYX
  N44(2,1) := SYZ - SZY
  N44(2,2) := SXX - SYY - SZZ
  N44(2,3) := SXY + SYX
  N44(2,4) := SXZ + SZX
  N44(3,1) := SZX - SXZ
  N44(3,2) := SXY + SYX
  N44(3,3) := -SXX + SYY - SZZ
  N44(3,4) := SYZ + SZY
  N44(4,1) := SXY - SYX
  N44(4,2) := SXZ + SZX
  N44(4,3) := SYZ + SZY
  N44(4,4) := -SXX - SYY + SZZ

  VEC(1) := 1.0
  VEC(2) := 0.0
  VEC(3) := 0.0
  VEC(4) := 0.0
  DO ITER = 1, 40
    NEWVEC(1) := N44(1,1)*VEC(1) + N44(1,2)*VEC(2) + N44(1,3)*VEC(3) + N44(1,4)*VEC(4)
    NEWVEC(2) := N44(2,1)*VEC(1) + N44(2,2)*VEC(2) + N44(2,3)*VEC(3) + N44(2,4)*VEC(4)
    NEWVEC(3) := N44(3,1)*VEC(1) + N44(3,2)*VEC(2) + N44(3,3)*VEC(3) + N44(3,4)*VEC(4)
    NEWVEC(4) := N44(4,1)*VEC(1) + N44(4,2)*VEC(2) + N44(4,3)*VEC(3) + N44(4,4)*VEC(4)
    NORM := SQRT(NEWVEC(1)*NEWVEC(1) + NEWVEC(2)*NEWVEC(2) + NEWVEC(3)*NEWVEC(3) + NEWVEC(4)*NEWVEC(4))
    IF NORM > 1.0E-12 THEN
      VEC(1) := NEWVEC(1) / NORM
      VEC(2) := NEWVEC(2) / NORM
      VEC(3) := NEWVEC(3) / NORM
      VEC(4) := NEWVEC(4) / NORM
    ENDIF
  ENDDO

  Q0 := VEC(1)
  Q1 := VEC(2)
  Q2 := VEC(3)
  Q3 := VEC(4)
  QQ := Q0*Q0 + Q1*Q1 + Q2*Q2 + Q3*Q3
  IF QQ > 1.0E-12 THEN
    QQ := SQRT(QQ)
    Q0 := Q0 / QQ
    Q1 := Q1 / QQ
    Q2 := Q2 / QQ
    Q3 := Q3 / QQ
  ENDIF
  R11 := Q0*Q0 + Q1*Q1 - Q2*Q2 - Q3*Q3
  R12 := 2.0*(Q1*Q2 - Q0*Q3)
  R13 := 2.0*(Q1*Q3 + Q0*Q2)
  R21 := 2.0*(Q1*Q2 + Q0*Q3)
  R22 := Q0*Q0 - Q1*Q1 + Q2*Q2 - Q3*Q3
  R23 := 2.0*(Q2*Q3 - Q0*Q1)
  R31 := 2.0*(Q1*Q3 - Q0*Q2)
  R32 := 2.0*(Q2*Q3 + Q0*Q1)
  R33 := Q0*Q0 - Q1*Q1 - Q2*Q2 + Q3*Q3

  SUM_DIST_SQ := 0.0
  DO I = 1, NRES
    RX := RES_X(OFFB + I) - XC
    RY := RES_Y(OFFB + I) - YC
    RZ := RES_Z(OFFB + I) - ZC
    TX := R11*RX + R12*RY + R13*RZ
    TY := R21*RX + R22*RY + R23*RZ
    TZ := R31*RX + R32*RY + R33*RZ
    NX := NATIVE_X(I) - XN
    NY := NATIVE_Y(I) - YN
    NZ := NATIVE_Z(I) - ZN
    SUM_DIST_SQ := SUM_DIST_SQ + (TX - NX)**2 + (TY - NY)**2 + (TZ - NZ)**2
  ENDDO
  RMSD_NATIVE := SQRT(SUM_DIST_SQ / REAL(NRES))

  RETURN
END
"""

packed = TEMPLATE.replace("__SEQ_PARAMS__", seq_params).replace(
    "__INIT_NATIVE__", init_native_body
)
OUT.write_text(packed)
print(f"wrote {OUT} ({len(packed.splitlines())} lines)")


# ══════════════════════════════════════════════════════════════════════
# V2: stage-4 packed force kernels — Morse/angle/torsion loops lifted
# out of the per-block loop into ONE packed loop each per frame, with
# block offsets baked into runtime-built index tables (BOND_A/B, ANG_A/B/C,
# TORS_A..D) and packed parameter tables (ANGK_P, ANGT0_P, TORSK_P,
# TORSP0_P). Per-block operation order is unchanged (steric/hydro/native
# in block loop A, then packed Morse -> angles -> torsions, then
# register/damping/position in block loop B), so CPU results are
# bitwise identical to v1. On GPU each packed loop is ONE kernel
# launch per frame (3 total) instead of 3 x NBLK.
# ══════════════════════════════════════════════════════════════════════

OUT2 = ROOT / "min" / "pmargin" / "packed_bba5_v2.ergo"

DECL_ANCHOR = "! ── Per-block seeds and results ──────────────────────────────"
DECL_EXTRA = """! ── Packed force-kernel tables (v2): block offsets baked in ─────
PARAMETER INTEGER :: NBOND = 176
PARAMETER INTEGER :: NANG = 168
PARAMETER INTEGER :: NTORS = 160
STATIC INTEGER :: BOND_A(NBOND)
STATIC INTEGER :: BOND_B(NBOND)
STATIC INTEGER :: ANG_A(NANG)
STATIC INTEGER :: ANG_B(NANG)
STATIC INTEGER :: ANG_C(NANG)
STATIC REAL :: ANGK_P(NANG)
STATIC REAL :: ANGT0_P(NANG)
STATIC INTEGER :: TORS_A(NTORS)
STATIC INTEGER :: TORS_B(NTORS)
STATIC INTEGER :: TORS_C(NTORS)
STATIC INTEGER :: TORS_D(NTORS)
STATIC REAL :: TORSK_P(NTORS)
STATIC REAL :: TORSP0_P(NTORS)
STATIC INTEGER :: I1, I2, I3, I4

"""
assert DECL_ANCHOR in packed
v2 = packed.replace(DECL_ANCHOR, DECL_EXTRA + DECL_ANCHOR)

# call INIT_TABLES after the coils are initialized (params are set by
# INIT_SHARED, tables are pure index/param packing)
COIL_ANCHOR = """ENDDO

WRITE(*, "# PACKED_BBA5 NBLK=8 NRES=23 MAXFRAME=48000 QUENCH=12000")"""
assert COIL_ANCHOR in v2
v2 = v2.replace(COIL_ANCHOR, """ENDDO
CALL INIT_TABLES()

WRITE(*, "# PACKED_BBA5_V2 NBLK=8 NRES=23 MAXFRAME=48000 QUENCH=12000")""")

# ── split the block loop around the three force sections ────────────
M_MORSE = "    ! Morse bonds (backbone)"
M_ANGLE = "    ! Angle bending (backbone angles)"
M_TORS = "    ! Torsion (dihedral) angles"
M_REG = "    ! Cross-strand register torsions"
i_m = v2.index(M_MORSE)
i_a = v2.index(M_ANGLE)
i_t = v2.index(M_TORS)
i_r = v2.index(M_REG)
sec_morse = v2[i_m:i_a]
sec_angle = v2[i_a:i_t]
sec_tors = v2[i_t:i_r]


def dedent2(s):
    return "\n".join(line[2:] if line.startswith("  ") else line
                     for line in s.split("\n"))


def rep_indices(s, pairs):
    # longest keys first so OFF + I+2 etc. bind before OFF + I
    for old, new in sorted(pairs, key=lambda p: -len(p[0])):
        s = s.replace(old, new)
    return s


# Morse: I1 = bond atom a (OFF+I), I2 = atom b (OFF+I+1)
pk_morse = dedent2(sec_morse)
pk_morse = pk_morse.replace(
    "  DO I = 1, NRES-1",
    "  DO K = 1, NBOND\n    I1 := BOND_A(K)\n    I2 := BOND_B(K)")
pk_morse = rep_indices(pk_morse, [("OFF + I+1", "I2"), ("OFF + I", "I1")])

# Angles: I1 = i-1, I2 = i, I3 = i+1; params from packed tables
pk_angle = dedent2(sec_angle)
pk_angle = pk_angle.replace(
    "  DO I = 2, NRES-1",
    "  DO K = 1, NANG\n    I1 := ANG_A(K)\n    I2 := ANG_B(K)\n    I3 := ANG_C(K)")
pk_angle = rep_indices(pk_angle, [("OFF + I-1", "I1"), ("OFF + I+1", "I3"),
                                  ("OFF + I", "I2")])
pk_angle = pk_angle.replace("RES_ANGK(I)", "ANGK_P(K)")
pk_angle = pk_angle.replace("RES_ANGT0(I)", "ANGT0_P(K)")

# Torsions: I1 = i-1, I2 = i, I3 = i+1, I4 = i+2
pk_tors = dedent2(sec_tors)
pk_tors = pk_tors.replace(
    "  DO I = 2, NRES-2",
    "  DO K = 1, NTORS\n    I1 := TORS_A(K)\n    I2 := TORS_B(K)\n"
    "    I3 := TORS_C(K)\n    I4 := TORS_D(K)")
pk_tors = rep_indices(pk_tors, [("OFF + I-1", "I1"), ("OFF + I+1", "I3"),
                                ("OFF + I+2", "I4"), ("OFF + I", "I2")])
pk_tors = pk_tors.replace("RES_TORSK(I)", "TORSK_P(K)")
pk_tors = pk_tors.replace("RES_TORSP0(I)", "TORSP0_P(K)")

# reassemble: block loop A ends after the native section; packed kernels
# run once per frame; block loop B opens for register/damping/position
v2 = (
    v2[:i_m]
    + "  ENDDO\n\n"
    + "  ! ── packed force kernels: ONE loop per force type per frame ──\n"
    + pk_morse + "\n"
    + pk_angle + "\n"
    + pk_tors + "\n"
    + "  DO B = 1, NBLK\n    OFF := (B - 1) * NRES\n\n"
    + v2[i_r:]
)

# INIT_TABLES subroutine (before UPDATE_THERMAL definition)
INIT_TABLES = """! ════════════════════════════════════════════════════════════
! INIT_TABLES: build block-aware packed index tables (offsets baked)
! and packed parameter tables from the shared per-residue params
! ════════════════════════════════════════════════════════════

SUBROUTINE INIT_TABLES()
  INTEGER :: B, I, K
  DO B = 1, NBLK
    DO I = 1, NRES - 1
      K := (B - 1) * 22 + I
      BOND_A(K) := (B - 1) * NRES + I
      BOND_B(K) := (B - 1) * NRES + I + 1
    ENDDO
    DO I = 2, NRES - 1
      K := (B - 1) * 21 + (I - 1)
      ANG_A(K) := (B - 1) * NRES + I - 1
      ANG_B(K) := (B - 1) * NRES + I
      ANG_C(K) := (B - 1) * NRES + I + 1
      ANGK_P(K) := RES_ANGK(I)
      ANGT0_P(K) := RES_ANGT0(I)
    ENDDO
    DO I = 2, NRES - 2
      K := (B - 1) * 20 + (I - 1)
      TORS_A(K) := (B - 1) * NRES + I - 1
      TORS_B(K) := (B - 1) * NRES + I
      TORS_C(K) := (B - 1) * NRES + I + 1
      TORS_D(K) := (B - 1) * NRES + I + 2
      TORSK_P(K) := RES_TORSK(I)
      TORSP0_P(K) := RES_TORSP0(I)
    ENDDO
  ENDDO
END

"""
UT_ANCHOR = "! ════════════════════════════════════════════════════════════\n! UPDATE_THERMAL"
assert UT_ANCHOR in v2
v2 = v2.replace(UT_ANCHOR, INIT_TABLES + UT_ANCHOR)

OUT2.write_text(v2)
print(f"wrote {OUT2} ({len(v2.splitlines())} lines)")


# ══════════════════════════════════════════════════════════════════════
# TEMPER: parallel tempering (replica swap) on the packed v2 form.
#   - per-block temperature multiplier TMUL(B), geometric ladder
#     1.0 -> LADDER_MAX, applied to the noise amplitude inside the
#     existing schedule (TC * TMUL(B) * ...; with TMUL=1.0 this is
#     IEEE-exact, so the swaps-OFF gate is bitwise-identical to v2)
#   - every SWAP_EVERY frames: per-block energies (Morse+angle+torsion+
#     hydro+native, +register when FRAME>1200 — matching the force;
#     torsion energy uses the FORCE's PHI convention, not the
#     diagnostic atan2 variant), Metropolis
#       DELTA = (beta_i - beta_j) * (E_i - E_j), beta = 1/TMUL
#     accept if DELTA > 0 or hash(frame,pair) < exp(DELTA); swap
#     TEMPERATURES (states stay in blocks). Sequential pair sweep 1..7.
#   - hash: MOD(ABS(SIN(frame*12.9898 + pair*78.233 + 3.7)*43758.5453),1)
#     — same MOD family as the sim's noise, deterministic.
# Two outputs: packed_temper.ergo (SWAP_EVERY=500) and
# packed_temper_gate.ergo (SWAP_EVERY=0, validation gate).
# ══════════════════════════════════════════════════════════════════════

TEMPER_DECLS = """
! ── Parallel tempering state ───────────────────────────────────────
PARAMETER INTEGER :: SWAP_EVERY = __SWAP_EVERY__
PARAMETER REAL :: LADDER_MAX = 2.0
STATIC REAL :: TMUL(8)
STATIC REAL :: EBLOCK(8)
STATIC INTEGER :: SWAP_TRY(7)
STATIC INTEGER :: SWAP_ACC(7)
STATIC REAL :: E_TOT, BETA_I, BETA_J, DELTA_M, U_HASH, TM_TMP
"""

LADDER_INIT = """CALL INIT_TABLES()

! Temperature ladder (geometric 1.0 -> LADDER_MAX); uniform 1.0 when
! swaps are off (gate build -> dynamics bitwise-identical to v2)
IF SWAP_EVERY > 0 THEN
  DO B = 1, NBLK
    TMUL(B) := LADDER_MAX ** (REAL(B - 1) / REAL(NBLK - 1))
  ENDDO
ELSE
  DO B = 1, NBLK
    TMUL(B) := 1.0
  ENDDO
ENDIF"""

SWAP_BLOCK = """
  ! ── replica swap step (temperatures swap, states stay) ──
  IF SWAP_EVERY > 0 .AND. MOD(FRAME, SWAP_EVERY) = 0 THEN
    DO B = 1, NBLK
      OFF := (B - 1) * NRES
      CALL COMPUTE_ENERGY(OFF, FRAME)
      EBLOCK(B) := E_TOT
    ENDDO
    DO B = 1, NBLK - 1
      BETA_I := 1.0 / TMUL(B)
      BETA_J := 1.0 / TMUL(B + 1)
      DELTA_M := (BETA_I - BETA_J) * (EBLOCK(B) - EBLOCK(B + 1))
      SWAP_TRY(B) := SWAP_TRY(B) + 1
      U_HASH := MOD(ABS(SIN(REAL(FRAME) * 12.9898 + REAL(B) * 78.233 + 3.7) * 43758.5453), 1.0)
      IF DELTA_M > 0.0 .OR. U_HASH < EXP(DELTA_M) THEN
        TM_TMP := TMUL(B)
        TMUL(B) := TMUL(B + 1)
        TMUL(B + 1) := TM_TMP
        SWAP_ACC(B) := SWAP_ACC(B) + 1
        WRITE(*, "SWACC %d %d %.4f %.4f %.3f %.3f") &
          FRAME, B, EBLOCK(B), EBLOCK(B + 1), TMUL(B), TMUL(B + 1)
      ENDIF
    ENDDO
  ENDIF
"""

SWAP_STATS = """! Swap acceptance statistics
DO B = 1, NBLK - 1
  WRITE(*, "SWAPSTAT %d %d %d %.4f") &
    B, SWAP_TRY(B), SWAP_ACC(B), REAL(SWAP_ACC(B)) / REAL(MAX(1, SWAP_TRY(B)))
ENDDO
WRITE(*, "# DONE")"""

COMPUTE_ENERGY = """! ════════════════════════════════════════════════════════════
! COMPUTE_ENERGY: per-block total potential for Metropolis.
! Components match the forces exactly (torsion PHI via the FORCE
! convention ATAN2(B2MAG*(B1.N2), N1.N2)); register-torsion energy
! included only when FR > EXTRA_TORSIONS_FROM (force is off before).
! ════════════════════════════════════════════════════════════

SUBROUTINE COMPUTE_ENERGY(OFFB, FR)
  INTEGER :: OFFB, FR
  INTEGER :: I, J, K
  REAL :: EM, EA, ET, EH, EN, ER
  REAL :: DX, DY, DZ, D, G, COS_ANG
  REAL :: BX, BY, BZ, CX, CY, CZ, U_MAG, V_MAG
  REAL :: B1X, B1Y, B1Z, B2X, B2Y, B2Z, B3X, B3Y, B3Z
  REAL :: N1X, N1Y, N1Z, N2X, N2Y, N2Z, N1MAG2, N2MAG2, B2MAG
  REAL :: PHI_A

  EM := 0.0
  DO I = 1, NRES - 1
    DX := RES_X(OFFB + I) - RES_X(OFFB + I + 1)
    DY := RES_Y(OFFB + I) - RES_Y(OFFB + I + 1)
    DZ := RES_Z(OFFB + I) - RES_Z(OFFB + I + 1)
    D := SQRT(DX*DX + DY*DY + DZ*DZ)
    G := EXP(-MORSE_A * (D - BACKBONE_R0))
    EM := EM + BACKBONE_D * (1.0 - G) * (1.0 - G)
  ENDDO

  EA := 0.0
  DO I = 2, NRES - 1
    BX := RES_X(OFFB + I - 1) - RES_X(OFFB + I)
    BY := RES_Y(OFFB + I - 1) - RES_Y(OFFB + I)
    BZ := RES_Z(OFFB + I - 1) - RES_Z(OFFB + I)
    CX := RES_X(OFFB + I + 1) - RES_X(OFFB + I)
    CY := RES_Y(OFFB + I + 1) - RES_Y(OFFB + I)
    CZ := RES_Z(OFFB + I + 1) - RES_Z(OFFB + I)
    U_MAG := SQRT(BX*BX + BY*BY + BZ*BZ)
    V_MAG := SQRT(CX*CX + CY*CY + CZ*CZ)
    IF U_MAG > 1.0E-12 .AND. V_MAG > 1.0E-12 THEN
      COS_ANG := MAX(-1.0, MIN(1.0, (BX*CX + BY*CY + BZ*CZ) / (U_MAG * V_MAG)))
      EA := EA + RES_ANGK(I) * (COS_ANG - COS(RES_ANGT0(I))) ** 2
    ENDIF
  ENDDO

  ET := 0.0
  DO I = 2, NRES - 2
    B1X := RES_X(OFFB + I) - RES_X(OFFB + I - 1)
    B1Y := RES_Y(OFFB + I) - RES_Y(OFFB + I - 1)
    B1Z := RES_Z(OFFB + I) - RES_Z(OFFB + I - 1)
    B2X := RES_X(OFFB + I + 1) - RES_X(OFFB + I)
    B2Y := RES_Y(OFFB + I + 1) - RES_Y(OFFB + I)
    B2Z := RES_Z(OFFB + I + 1) - RES_Z(OFFB + I)
    B3X := RES_X(OFFB + I + 2) - RES_X(OFFB + I + 1)
    B3Y := RES_Y(OFFB + I + 2) - RES_Y(OFFB + I + 1)
    B3Z := RES_Z(OFFB + I + 2) - RES_Z(OFFB + I + 1)
    N1X := B1Y*B2Z - B1Z*B2Y
    N1Y := B1Z*B2X - B1X*B2Z
    N1Z := B1X*B2Y - B1Y*B2X
    N2X := B2Y*B3Z - B2Z*B3Y
    N2Y := B2Z*B3X - B2X*B3Z
    N2Z := B2X*B3Y - B2Y*B3X
    N1MAG2 := N1X*N1X + N1Y*N1Y + N1Z*N1Z
    N2MAG2 := N2X*N2X + N2Y*N2Y + N2Z*N2Z
    B2MAG := SQRT(B2X*B2X + B2Y*B2Y + B2Z*B2Z)
    IF N1MAG2 > 1.0E-12 .AND. N2MAG2 > 1.0E-12 .AND. B2MAG > 1.0E-12 THEN
      PHI_A := ATAN2(B2MAG*(B1X*N2X + B1Y*N2Y + B1Z*N2Z), &
                     N1X*N2X + N1Y*N2Y + N1Z*N2Z)
      ET := ET + 2.0 * RES_TORSK(I) * (1.0 - COS(PHI_A - RES_TORSP0(I)))
    ENDIF
  ENDDO

  EH := 0.0
  DO I = 1, NRES - 4
    DO J = I + 4, NRES
      IF RES_HYDRO(I) > 0.0 .AND. RES_HYDRO(J) > 0.0 THEN
        DX := RES_X(OFFB + I) - RES_X(OFFB + J)
        DY := RES_Y(OFFB + I) - RES_Y(OFFB + J)
        DZ := RES_Z(OFFB + I) - RES_Z(OFFB + J)
        D := SQRT(DX*DX + DY*DY + DZ*DZ)
        IF D < HYDRO_CUTOFF .AND. D > 0.0 THEN
          EH := EH - (HYDRO_STRENGTH / HYDRO_ALPHA) * RES_HYDRO(I) * RES_HYDRO(J) * &
               EXP(-HYDRO_ALPHA * (D - HYDRO_R0))
        ENDIF
      ENDIF
    ENDDO
  ENDDO

  EN := 0.0
  DO I = 1, NRES - 3
    DO J = I + 3, NRES
      IF NATIVE_CONTACT(I, J) = 1 THEN
        DX := RES_X(OFFB + I) - RES_X(OFFB + J)
        DY := RES_Y(OFFB + I) - RES_Y(OFFB + J)
        DZ := RES_Z(OFFB + I) - RES_Z(OFFB + J)
        D := SQRT(DX*DX + DY*DY + DZ*DZ)
        IF D > 0.0 THEN
          EN := EN + NATIVE_K * (D - NATIVE_R0(I, J)) ** 2
        ENDIF
      ENDIF
    ENDDO
  ENDDO

  ! Register-torsion energy (force active only after EXTRA_TORSIONS_FROM)
  ER := 0.0
  IF FR > EXTRA_TORSIONS_FROM THEN
    DO K = 1, NREG
      IA := REG_A(K)
      IB := REG_B(K)
      IC := REG_C(K)
      ID := REG_D(K)
      B1X := RES_X(OFFB + IB) - RES_X(OFFB + IA)
      B1Y := RES_Y(OFFB + IB) - RES_Y(OFFB + IA)
      B1Z := RES_Z(OFFB + IB) - RES_Z(OFFB + IA)
      B2X := RES_X(OFFB + IC) - RES_X(OFFB + IB)
      B2Y := RES_Y(OFFB + IC) - RES_Y(OFFB + IB)
      B2Z := RES_Z(OFFB + IC) - RES_Z(OFFB + IB)
      B3X := RES_X(OFFB + ID) - RES_X(OFFB + IC)
      B3Y := RES_Y(OFFB + ID) - RES_Y(OFFB + IC)
      B3Z := RES_Z(OFFB + ID) - RES_Z(OFFB + IC)
      N1X := B1Y*B2Z - B1Z*B2Y
      N1Y := B1Z*B2X - B1X*B2Z
      N1Z := B1X*B2Y - B1Y*B2X
      N2X := B2Y*B3Z - B2Z*B3Y
      N2Y := B2Z*B3X - B2X*B3Z
      N2Z := B2X*B3Y - B2Y*B3X
      N1MAG2 := N1X*N1X + N1Y*N1Y + N1Z*N1Z
      N2MAG2 := N2X*N2X + N2Y*N2Y + N2Z*N2Z
      B2MAG := SQRT(B2X*B2X + B2Y*B2Y + B2Z*B2Z)
      IF N1MAG2 > 1.0E-12 .AND. N2MAG2 > 1.0E-12 .AND. B2MAG > 1.0E-12 THEN
        PHI_A := ATAN2(B2MAG*(B1X*N2X + B1Y*N2Y + B1Z*N2Z), &
                       N1X*N2X + N1Y*N2Y + N1Z*N2Z)
        ER := ER + 2.0 * REG_K(K) * (1.0 - COS(PHI_A - REG_P0(K)))
      ENDIF
    ENDDO
  ENDIF

  E_TOT := EM + EA + ET + EH + EN + ER
END

"""

RMSD_ANCHOR = ("! ════════════════════════════════════════════════════════════\n"
               "! COMPUTE_RMSD")


def make_temper(v2src, swap_every):
    t = v2src
    # declarations
    anchor = "STATIC INTEGER :: I1, I2, I3, I4\n"
    assert anchor in t
    t = t.replace(anchor, anchor + TEMPER_DECLS.replace("__SWAP_EVERY__", str(swap_every)))
    # ladder init
    assert "CALL INIT_TABLES()\n" in t
    t = t.replace("CALL INIT_TABLES()\n", LADDER_INIT + "\n", 1)
    # noise amplitude: multiply by TMUL(B) (exact when TMUL=1.0)
    t = t.replace("TEMP_X := THERMAL_CURRENT * PHASE_NOISE_SCALE",
                  "TEMP_X := THERMAL_CURRENT * TMUL(B) * PHASE_NOISE_SCALE")
    t = t.replace("+ THERMAL_CURRENT * SIN(", "+ THERMAL_CURRENT * TMUL(B) * SIN(")
    t = t.replace("+ THERMAL_CURRENT * COS(", "+ THERMAL_CURRENT * TMUL(B) * COS(")
    # swap step at frame end (after thermal schedule update)
    t = t.replace("  CALL UPDATE_THERMAL(FRAME)\n",
                  "  CALL UPDATE_THERMAL(FRAME)\n" + SWAP_BLOCK, 1)
    # energy subroutine before COMPUTE_RMSD
    assert RMSD_ANCHOR in t
    t = t.replace(RMSD_ANCHOR, COMPUTE_ENERGY + RMSD_ANCHOR)
    # swap stats at the end
    t = t.replace('WRITE(*, "# DONE")', SWAP_STATS, 1)
    # header
    t = t.replace("# PACKED_BBA5_V2 NBLK=8",
                  f"# PACKED_TEMPER SWAP_EVERY={swap_every} NBLK=8")
    return t


temper = make_temper(v2, 500)
OUTT = ROOT / "min" / "pmargin" / "packed_temper.ergo"
OUTT.write_text(temper)
print(f"wrote {OUTT} ({len(temper.splitlines())} lines)")

gate = make_temper(v2, 0)
OUTG = ROOT / "min" / "pmargin" / "packed_temper_gate.ergo"
OUTG.write_text(gate)
print(f"wrote {OUTG} ({len(gate.splitlines())} lines)")
