#!/usr/bin/env python3
"""hhb_probe_unroll.py — probe the bounded-attempt unroll cliff.

Generates hhb_probe_b{B}.ergo (B in 63, 64, 65, 128, 1024) in
min/wigner/ from the hhb_bounded_attempt.ergo shape: a bounded attempt
loop (ATT < B, forced exit ATT := B when B(I) > 0) inside a counted
loop inside a HANDSHAKE block.

Per element i (exact semantics, all bounds):
  B(i) = RAND(i)*2 - 1;  if B(i) > 0: A(i) = B(i)   (1 attempt)
                         else:        A(i) = (1+2+...+B)*B(i)  (B attempts)
S = sum(A). Expected S computed exactly in Python (splitmix64 replica).

Per bound B reports: extraction verdict (kernel-report), compile wall
time (CPU + SPIR-V), run wall time (CPU + SPIR-V), CPU==GPU bitwise,
S vs exact expectation. Per-attempt normalization: mean attempts per
element = P_pos*1 + P_neg*B with P_pos/P_neg measured from the exact
B values (deterministic per backend).

Run from repo root: python3 min/wigner/hhb_probe_unroll.py
GPU serial: one Vulkan job at a time (this script is serial by
construction).
"""

import os
import subprocess
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
HERE = os.path.join(REPO, "min", "wigner")

N = 2048
BOUNDS = [63, 64, 65, 128, 1024]

TEMPLATE = """! HHB_PROBE_B{B} — bounded-attempt probe at bound {B} (generated by
! hhb_probe_unroll.py — do not edit by hand).

IMPLICIT NONE

INTEGER, PARAMETER :: N = {N}
INTEGER, PARAMETER :: MAXATT = {B}
STATIC REAL :: A(N), B(N)
REAL :: S
INTEGER :: I, ATT

DO I = 1, N
  B(I) := RAND(I) * 2.0 - 1.0
  A(I) := 0.0
ENDDO

HANDSHAKE attempt
    DEPTH=1
    FRAME_BYTES=256
    MAXIT={B}
    PAYLOAD=(S)
  DO I = 1, N
    ATT := 0
    DO WHILE ATT < MAXATT
      ATT := ATT + 1
      A(I) := A(I) + B(I) * REAL(ATT)
      IF B(I) > 0.0 THEN
        ATT := {B}
      ENDIF
    ENDDO
  ENDDO
  S := 0.0
  DO I = 1, N
    S := S + A(I)
  ENDDO
  WRITE(*, "('S %.10e')") S
ENDHANDSHAKE

WRITE(*, "('FINAL %.10e')") S
STOP
"""

M64 = (1 << 64) - 1


def splitmix64(x):
    x = (x + 0x9E3779B97F4A7C15) & M64
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & M64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & M64
    return z ^ (z >> 31)


def rand01(i):
    return (splitmix64(i) >> 11) * 2.0 ** -53


def expected_S(bound):
    S = 0.0
    for i in range(1, N + 1):
        b = rand01(i) * 2.0 - 1.0
        S += b if b > 0 else (bound * (bound + 1) // 2) * b
    return S


def mean_attempts(bound):
    pos = sum(1 for i in range(1, N + 1) if rand01(i) * 2.0 - 1.0 > 0)
    neg = N - pos
    return (pos * 1 + neg * bound) / N


def sh(cmd, timeout=600):
    t0 = time.time()
    r = subprocess.run(cmd, capture_output=True, timeout=timeout,
                       cwd=REPO)
    return r, time.time() - t0


def main():
    print("=" * 74)
    print("HHB PROBE — bounded-attempt unroll cliff "
          "(N=%d elements, handshake region)" % N)
    print("=" * 74)
    print(f"{'bound':>6} {'extracted':>10} {'cc_cpu_s':>9} {'cc_gpu_s':>9} "
          f"{'run_cpu_s':>10} {'run_gpu_s':>10} {'bitwise':>8} "
          f"{'S ok':>5} {'ms/att-it cpu':>14}")
    for b in BOUNDS:
        path = os.path.join(HERE, f"hhb_probe_b{b}.ergo")
        with open(path, "w") as f:
            f.write(TEMPLATE.format(B=b, N=N))
        # extraction verdict: is the attempt loop's line a kernel?
        att_line = None
        for i, ln in enumerate(open(path).read().splitlines(), 1):
            if ln.strip() == "DO WHILE ATT < MAXATT":
                att_line = i - 2   # the enclosing DO I = 1, N
        r, _ = sh(["python", "-m", "core", path, "--target", "spirv",
                   "--kernel-report", "-o", "/dev/null"])
        rep = r.stdout.decode()
        extracted = any(f": line {att_line}" in ln and "kernel" in ln
                        for ln in rep.splitlines())
        # compile CPU + GPU, timed
        _, cc_cpu = sh(["python", "-m", "core", path, "-o",
                        f"/tmp/hhbp_{b}_cpu"])
        _, cc_gpu = sh(["python", "-m", "core", path, "--target", "spirv",
                        "-o", f"/tmp/hhbp_{b}_gpu"])
        # run both, timed
        r_cpu, t_cpu = sh([f"/tmp/hhbp_{b}_cpu"], timeout=600)
        r_gpu, t_gpu = sh([f"/tmp/hhbp_{b}_gpu"], timeout=600)
        same = r_cpu.stdout == r_gpu.stdout
        got = float(r_cpu.stdout.decode().splitlines()[0]
                    .split("'")[1].split()[1])
        exp = expected_S(b)
        s_ok = abs(got - exp) / abs(exp) < 1e-9
        per_it = t_cpu * 1e3 / (N * mean_attempts(b))
        print(f"{b:>6} {str(extracted):>10} {cc_cpu:>9.2f} "
              f"{cc_gpu:>9.2f} {t_cpu:>10.3f} {t_gpu:>10.3f} "
              f"{str(same):>8} {str(s_ok):>5} {per_it:>14.4f}")


if __name__ == "__main__":
    main()
