#!/usr/bin/env python3
"""make_zoom.py — build dbm_zoom.ergo from a dbm_zoom_gen.out trace.

Two modes:
  scan   — parse the FIELD dump of a dbm_zoom_gen run (f64 DBM growth),
           find the best fjord window (empty 16x16 interior, adjacent
           to the cluster, max boundary max/min phi span — DBM fjords
           are 1-2 cells wide, so a window INSIDE a true deep fjord
           does not exist; the best empty bay mouth is the proxy), and
           emit dbm_zoom.ergo.
  (default) — parse WIN/TRACE lines (e.g. written by scan) and emit
           dbm_zoom.ergo.

The window boundary ring is baked in twice: raw f64 values (solve A)
and affine-remapped [floor,ceil]->[0,1] values mapped in f64 here
(solve B — so B's boundary carries no f32 mapping error).

Usage: python3 make_zoom.py scan dbm_zoom_gen.out
       python3 make_zoom.py [trace.out]
"""
import sys

MODE = "build"
args = sys.argv[1:]
if args and args[0] == "scan":
    MODE = "scan"
    args = args[1:]

if MODE == "scan":
    path = args[0] if args else "dbm_zoom_gen.out"
    NX = NY = 257
    phi = [0.0] * (NX * NY + 1)
    clus = [0.0] * (NX * NY + 1)
    for line in open(path):
        p = line.split()
        if p and p[0] == "FIELD":
            phi[int(p[1])] = float(p[2])
            clus[int(p[1])] = float(p[3])

    def K(i, j):
        return i + (j - 1) * NX

    WN = 16
    best = None
    for j0 in range(3, NY - WN - 1):
        for i0 in range(3, NX - WN - 1):
            empty = True
            near = False
            pmin, pmax = 1e30, 0.0
            for jw in range(WN):
                for iw in range(WN):
                    k = K(i0 + iw, j0 + jw)
                    edge = iw in (0, WN - 1) or jw in (0, WN - 1)
                    if not edge and clus[k] > 0.5:
                        empty = False
                    if edge:
                        pmin = min(pmin, phi[k])
                        pmax = max(pmax, phi[k])
            for jw in range(-2, WN + 2):
                for iw in range(-2, WN + 2):
                    ii, jj = i0 + iw, j0 + jw
                    if 1 < ii < NX and 1 < jj < NY and clus[K(ii, jj)] > 0.5:
                        near = True
            if empty and near and 1e-12 < pmin and 1e-4 < pmax < 0.9:
                sc = pmax / pmin
                if best is None or sc > best[0]:
                    best = (sc, i0, j0, pmin, pmax)
    if best is None:
        sys.exit("no fjord window found in " + path)
    sc, i0, j0, pmin, pmax = best
    trace = {(iw, jw): phi[K(i0 + iw, j0 + jw)]
             for jw in range(WN) for iw in range(WN)
             if iw in (0, WN - 1) or jw in (0, WN - 1)}
    floor, ceil = pmin, pmax
    wn = WN
    print(f"# window ({i0},{j0}) floor={floor:.3e} ceil={ceil:.3e} "
          f"span={sc:.1f}", file=sys.stderr)
else:
    path = args[0] if args else "dbm_zoom_gen.out"
    floor = ceil = None
    i0 = j0 = None
    wn = None
    trace = {}  # (iw, jw) -> float
    for line in open(path):
        p = line.split()
        if not p:
            continue
        if p[0] == "WIN":
            if len(p) > 7:  # WIN wn i0 j0 floor ceil score
                wn = int(p[1]); i0, j0 = int(p[2]), int(p[3])
                floor, ceil = float(p[5]), float(p[7])
            else:
                i0, j0 = int(p[1]), int(p[2])
                floor, ceil = float(p[4]), float(p[6])
        elif p[0] == "TRACE":
            trace[(int(p[1]), int(p[2]))] = float(p[3])

assert floor is not None and len(trace) > 0, "no WIN/TRACE in " + path
WN = wn if wn else 16
span = ceil - floor
assert span > 0

HEADER = f"""! dbm_zoom.ergo — GENERATED by make_zoom.py (scan mode) from a
! dbm_zoom_gen field dump. Do not edit; regenerate.
! Zoom/remap oracle (Inc-4 Part B): a {WN}x{WN} bay window of a grown DBM
! cluster (origin grid ({i0},{j0}), boundary phi in
! [{floor:.6e}, {ceil:.6e}], span {span/floor:.0f}x) solved three ways:
!   A — unremapped, production tolerance TOLG=1e-6
!   B — affine-remapped [floor,ceil]->[0,1], zoom tolerance 1e-11
!   C — reference solve, tol 1e-13 (meaningful in the f64 build)
! Laplace is linear, hence invariant under affine field maps: the
! remapped solve is the SAME PDE with rescaled BCs, exact in exact
! arithmetic — but [0,1] puts the bay's small-amplitude structure at
! full f32 precision instead of eps*A_ref noise (Spec
! Ergo_Activity_Bounds.md §6). Window note: DBM fjords are 1-2 cells
! wide (measured), so no empty 16x16 window sits INSIDE a true deep
! fjord (phi~1e-12 there); this is the deepest empty bay mouth.
! Boundary-trace error bounds the zoom (the frame is f64 here); remap
! back to global units is lossy on the global grid (analysis-only mode).
! Errors are computed in-program against the C field; the f64 build
! additionally validates A/C (tol truncation) and B (remap exactness).
!
!   python -m core min/dendrite/dbm_zoom.ergo -o /tmp/zoom64
!   python -m core min/dendrite/dbm_zoom.ergo --precision f32 -o /tmp/zoom32
"""

DECLS = f"""IMPLICIT NONE
INTEGER, PARAMETER :: NW = {WN}, NPTS = {WN*WN}, SWMAX = 30000
REAL, PARAMETER :: FL = {floor:.17e}, CE = {ceil:.17e}
REAL, PARAMETER :: TOLG = 1.0E-6, TOLZ = 1.0E-11, TOLR = 1.0E-13
STATIC REAL :: PA(NPTS), QA(NPTS), PB(NPTS), QB(NPTS), PC(NPTS), QC(NPTS)
STATIC REAL :: MB(NPTS)
REAL :: DN, MAXD, ERR, ERRB, REL, RELB, WMAX
INTEGER :: I, J, K, SW, CONVA, CONVB, CONVC, SWA, SWB, SWC
"""

body = [HEADER, DECLS]

# Init: interior zero, mask, boundaries baked
body.append("""
DO K = 1, NPTS
  PA(K) := 0.0
  QA(K) := 0.0
  PB(K) := 0.0
  QB(K) := 0.0
  PC(K) := 0.0
  QC(K) := 0.0
  MB(K) := 1.0
ENDDO
DO J = 1, NW
  DO I = 1, NW
    K := I + (J - 1) * NW
    IF (I == 1) THEN
      MB(K) := 0.0
    ENDIF
    IF (I == NW) THEN
      MB(K) := 0.0
    ENDIF
    IF (J == 1) THEN
      MB(K) := 0.0
    ENDIF
    IF (J == NW) THEN
      MB(K) := 0.0
    ENDIF
  ENDDO
ENDDO

! Baked f64 boundary trace (solve A raw, solve C raw, solve B remapped
! by the driver in f64 — no f32 mapping error on the frame).""")

for (iw, jw), v in sorted(trace.items()):
    i = iw + 1
    j = jw + 1
    k = i + (j - 1) * WN
    z = (v - floor) / span
    body.append(f"PA({k}) := {v:.17e}")
    body.append(f"QA({k}) := {v:.17e}")
    body.append(f"PC({k}) := {v:.17e}")
    body.append(f"QC({k}) := {v:.17e}")
    body.append(f"PB({k}) := {z:.17e}")
    body.append(f"QB({k}) := {z:.17e}")

body.append("""
! Solve A: raw field, production tol (masked Jacobi ping-pong).
CONVA := 0
SWA := SWMAX
DO SW = 1, SWMAX
  IF (CONVA == 0) THEN
    MAXD := 0.0
    DO K = NW + 2, NPTS - NW - 1
      DN := MB(K) * (0.25 * (PA(K - 1) + PA(K + 1) &
        + PA(K - NW) + PA(K + NW)) - PA(K))
      QA(K) := PA(K) + DN
      MAXD := MAX(MAXD, ABS(DN))
    ENDDO
    DO K = 1, NPTS
      PA(K) := QA(K)
    ENDDO
    IF (MAXD < TOLG) THEN
      CONVA := 1
      SWA := SW
    ENDIF
  ENDIF
ENDDO

! Solve B: remapped [0,1] field, zoom tol.
CONVB := 0
SWB := SWMAX
DO SW = 1, SWMAX
  IF (CONVB == 0) THEN
    MAXD := 0.0
    DO K = NW + 2, NPTS - NW - 1
      DN := MB(K) * (0.25 * (PB(K - 1) + PB(K + 1) &
        + PB(K - NW) + PB(K + NW)) - PB(K))
      QB(K) := PB(K) + DN
      MAXD := MAX(MAXD, ABS(DN))
    ENDDO
    DO K = 1, NPTS
      PB(K) := QB(K)
    ENDDO
    IF (MAXD < TOLZ) THEN
      CONVB := 1
      SWB := SW
    ENDIF
  ENDIF
ENDDO

! Solve C: raw field, reference tol.
CONVC := 0
SWC := SWMAX
DO SW = 1, SWMAX
  IF (CONVC == 0) THEN
    MAXD := 0.0
    DO K = NW + 2, NPTS - NW - 1
      DN := MB(K) * (0.25 * (PC(K - 1) + PC(K + 1) &
        + PC(K - NW) + PC(K + NW)) - PC(K))
      QC(K) := PC(K) + DN
      MAXD := MAX(MAXD, ABS(DN))
    ENDDO
    DO K = 1, NPTS
      PC(K) := QC(K)
    ENDDO
    IF (MAXD < TOLR) THEN
      CONVC := 1
      SWC := SW
    ENDIF
  ENDIF
ENDDO

! Remap B back to raw units, then errors vs C.
WMAX := 0.0
DO K = 1, NPTS
  IF (ABS(PC(K)) > WMAX) THEN
    WMAX := ABS(PC(K))
  ENDIF
ENDDO
ERR := 0.0
ERRB := 0.0
REL := 0.0
RELB := 0.0
DO K = 1, NPTS
  IF (ABS(PA(K) - PC(K)) > ERR) THEN
    ERR := ABS(PA(K) - PC(K))
  ENDIF
  IF (ABS(FL + (CE - FL) * PB(K) - PC(K)) > ERRB) THEN
    ERRB := ABS(FL + (CE - FL) * PB(K) - PC(K))
  ENDIF
  IF (ABS(PC(K)) > 1.0e-30) THEN
    IF (ABS(PA(K) - PC(K)) / ABS(PC(K)) > REL) THEN
      REL := ABS(PA(K) - PC(K)) / ABS(PC(K))
    ENDIF
    IF (ABS(FL + (CE - FL) * PB(K) - PC(K)) / ABS(PC(K)) > RELB) THEN
      RELB := ABS(FL + (CE - FL) * PB(K) - PC(K)) / ABS(PC(K))
    ENDIF
  ENDIF
ENDDO

WRITE(*, "zoom win floor %.6e ceil %.6e  wmax %.6e") FL, CE, WMAX
WRITE(*, "sweeps A %d B %d C %d") SWA, SWB, SWC
WRITE(*, "errA %.3e errB %.3e  (max abs vs C)") ERR, ERRB
WRITE(*, "relA %.3e relB %.3e  (max rel vs C)") REL, RELB""")

open("min/dendrite/dbm_zoom.ergo", "w").write("\n".join(body) + "\n")
print(f"wrote min/dendrite/dbm_zoom.ergo  win=({i0},{j0}) "
      f"floor={floor:.3e} ceil={ceil:.3e} trace={len(trace)} cells")
